### PR TITLE
use micromamba instead of mamba

### PR DESCRIPTION
**Pull request by keewis**
I'm not sure if this is exactly equal to what we had before, but we might be able to save 3-4 minutes of CI time with this.

- [x] supersedes and closes #6544

### CODE REVIEW

**Comment by keewis** [comment]
we still have to properly verify the environments, but so far I'd say this was very much worth it, even without the environment caching (the environment creation takes usually <2 minutes)

**Comment by keewis** [comment]
now that the cache conflict issue seems to have been solved, this should be ready for reviews. Note that while I did check _some_ environments, I did not check all of them. It should result in the same environments as `mamba`, though.

**Comment by max-sixty** [comment]
Looks great @keewis !

**Review by andersy005 — APPROVED** [review]
👍🏽  for the micromamba time improvements + caching.... Great addition!! 🚀

**Pull request merged**
