### PR TITLE
Make chunk manager an option in `set_options`

### PR DESCRIPTION
**Pull request by tomwhite**
It would be useful to have a way to choose a chunk manager if more than one is found (see https://docs.xarray.dev/en/latest/internals/chunked-arrays.html#user-interface for how it works). The use case I have is a codebase that uses Xarray and Dask (and has lots of Dask imports), and which I'd like to be able to run on Cubed too (as well as Dask). Rather than converting it all in one go, it would be easier to convert it to use Xarray-only APIs gradually. The changes involve moving `da.map_blocks` to `xr.apply_ufunc`, for example.

Using the the current PR I can have both Dask and Cubed packages installed and switch to use Cubed with `xr.set_option(chunk_manager="cubed")`. This allows me to run a subset of the tests on Cubed while not having to worry about the rest of the Dask imports in the codebase.

Does this look like a good way to achieve this @TomNicholas?

- [ ] Closes #xxxx
- [x] Tests added
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [ ] New functions/methods are listed in `api.rst`

### CODE REVIEW

**Review by dcherian — APPROVED** [review]

**Comment by TomNicholas** [comment]
Good idea! I think this should be documented and tested though. It can be documented in the paragraph you linked to, and tested using the options context manager in a simple new test.

**Comment by Illviljan** [comment]
Please add a line in the docstring of `xr.set_option` as well.

**Review by TomNicholas — APPROVED** [review]
Sorry I should have mentioned to add a whatsnew entry - then happy to merge!

**Comment by tomwhite** [comment]
> Sorry I should have mentioned to add a whatsnew entry - then happy to merge!

Done - thanks @TomNicholas

**Pull request merged**
