### PR TITLE
Improve non-nanosecond warning

### LINKED ISSUE #7237: The new NON_NANOSECOND_WARNING is not very nice to end users
### What is your issue?

The new nanosecond warning doesn't really point anybody to where they should change their code.

Nor does it really tell them how to fix it.

```
import xarray as xr
import numpy as np
xr.DataArray(np.zeros(1, dtype='datetime64[us]'))
```
yields

```
xarray/core/variable.py:194: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values.
```

https://github.com/pydata/xarray/blob/f32d354e295c05fb5c5ece7862f77f19d82d5894/xarray/core/variable.py#L194

I think at the very least, the stacklevel should be specified when calling the `warn` function.

It isn't really pretty, but I've been passing a parameter when I expect to pass up a warning to the end user:
eg. https://github.com/vispy/vispy/pull/2405

However, others have not liked that approach.

### PR DESCRIPTION
**Pull request by spencerkclark**
Thanks for the feedback @hmaarrfk.  Is this what you had in mind?

- [x] Closes #7237

For example running this script:
```python
import numpy as np
import xarray as xr

times = [np.datetime64("2000-01-01", "us")]
var = xr.Variable(["time"], times)
da = xr.DataArray(times)
```
leads to the following warnings:
```
$ python test_warning.py
test_warning.py:6: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
  var = xr.Variable(["time"], times)
test_warning.py:7: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
  da = xr.DataArray(times)
```

### CODE REVIEW

**Comment by spencerkclark** [comment]
Hmm...I was kind of hoping we could avoid something like adding a `_stacklevel_increment` argument, but hardcoding the `stacklevel` obviously doesn't work in the case that fields are converted to variables within xarray, e.g. in the case of passing coordinates to the DataArray constructor:

```python
import numpy as np
import xarray as xr

times = [np.datetime64("2000-01-01", "us")]
da = xr.DataArray([1], dims=["time"], coords=[times])
```

```
$ python test_warning.py
/Users/spencer/software/xarray/xarray/core/dataarray.py:148: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
  var = as_variable(coord, name=dim)
```

**Comment by hmaarrfk** [comment]
> Hmm...I was kind of hoping we could avoid something like adding a _stacklevel_increment argument.

Right. thank you for finding that example. I was going to try to construct one.

**Comment by dcherian** [comment]
> .I was kind of hoping we could avoid something like adding a _stacklevel_increment argument, 

:( I don't know of any other way.

**Comment by mathause** [comment]
Pandas has a `find_stack_level` function (https://github.com/pandas-dev/pandas/blob/0106c26529900bad0561efb9c9180f7f016365b0/pandas/util/_exceptions.py#L28). But I am not sure if this would fix the problem?

**Comment by spencerkclark** [comment]
Nice find @mathause!  That seems to work.  I added a version of that function to `utils`.  The warning from [my example above](https://github.com/pydata/xarray/pull/7238#issuecomment-1296235033) now looks like:
```
test_warning.py:5: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
  da = xr.DataArray([1], dims=["time"], coords=[times])
```

**Comment by spencerkclark** [comment]
It looks like I've stumbled upon some new upstream test failures related to https://github.com/pandas-dev/pandas/pull/49101.

**Comment by keewis** [comment]
> It looks like I've stumbled upon some new upstream test failures

it's not really [new](https://github.com/pydata/xarray/actions/runs/3390263562/jobs/5634192550) (the CI has been failing since about 4 days ago), but because so many tests fail we're hitting the size limit for new issues:
```
{"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}
```

Not sure if we can do something about that in the action?

cc @andersy005

**Review by dcherian — APPROVED** [review]
LGTM

**Pull request merged**
