### PR TITLE
Install numba & numbagg in upstream install

### PR DESCRIPTION
**Pull request by max-sixty**

### CODE REVIEW

**Comment by max-sixty** [comment]
This fixes the upstream error from no numbagg library being available, though there are other failures

**Comment by max-sixty** [comment]
This will need to wait until the next numba release, which supports numpy 2.0...

**Comment by max-sixty** [comment]
> from what I remember, in #7311 we decided not to install `numba` in the upstream-dev CI because it can't handle any version upgrade of `numpy`. Do we want to revisit that?

Yes, that's a good point — I think this is intractable unless numba tries to be forward-compatible with numpy. So will close.

We'll need another solution for the upstream mypy error, though it's one of many many there...

**Comment by keewis** [comment]
yeah, someone will have to have a look at the `mypy` upstream-dev CI at some point. Though now that we actually test the released `numpy>=2` in the normal `mypy` CI, these are also failing now.

**Comment by max-sixty** [comment]
> yeah, someone will have to have a look at the `mypy` upstream-dev CI at some point.

Yes, mostly tracked in https://github.com/pydata/xarray/issues/9155 — most of the failures are a change in mypy versions rather than our library versions...

**Pull request closed without merging**
