### PR TITLE
Reduce length of cftime resample tests

### LINKED ISSUE #2874: xarray/tests/test_cftimeindex_resample.py::test_resampler is way too slow
Some profiling results from pytest:
```
$ pytest -k cftime --durations=50
...
============================================= slowest 50 test durations ==============================================
7.92s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-None-right-700T]
7.45s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-None-None-700T]
7.17s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-None-right-700T]
7.12s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-None-None-700T]
7.12s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-right-right-700T]
7.03s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-right-None-700T]
6.88s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-right-None-700T]
6.70s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-right-right-700T]
5.88s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-right-right-12H]
5.69s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-None-None-12H]
5.55s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-None-None-12H]
5.44s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-None-right-12H]
5.44s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-right-None-12H]
5.32s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-None-right-12H]
5.21s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-right-right-12H]
5.08s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-right-None-12H]
1.56s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-31-right-None-700T]
1.36s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-31-right-right-700T]
1.22s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-31-None-right-700T]
1.19s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-24-None-None-700T]
1.16s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-31-None-None-700T]
1.15s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-24-None-right-700T]
1.11s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-24-right-None-700T]
1.09s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-24-right-right-700T]
0.96s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-31-None-None-12H]
0.93s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-31-None-right-12H]
0.93s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-31-right-None-12H]
0.91s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-24-None-None-12H]
0.91s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-31-right-right-12H]
0.89s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-24-right-None-12H]
0.88s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-24-None-right-12H]
0.86s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3Q_AUG-24-right-right-12H]
0.69s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-right-None-8001T]
0.69s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-None-right-8001T]
0.66s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-None-None-8001T]
0.65s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-right-right-8001T]
0.64s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-None-right-8D]
0.62s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-None-right-8D]
0.62s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-None-right-8001T]
0.60s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-None-None-8001T]
0.59s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-right-right-8D]
0.59s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-right-right-8001T]
0.57s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-right-right-8D]
0.57s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-right-None-8001T]
0.38s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[41987T-31-None-None-700T]
0.36s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-None-None-8D]
0.36s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-None-None-8D]
0.34s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-24-right-None-8D]
0.33s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[3AS_JUN-31-right-None-8D]
0.33s call     xarray/tests/test_cftimeindex_resample.py::test_resampler[41987T-31-right-right-700T]
```

This is a heavily parametrized test, and many of these test cases take 5+ seconds to run! Are there ways we could simplify these tests to make them faster?

On my laptop, this test alone roughly doubles the runtime of our entire test suite, increasing it from about 2 minutes to 4 minutes.

@jwenfai @spencerkclark Any ideas?

### PR DESCRIPTION
**Pull request by spencerkclark**
The main issue is that we were resampling the same time indexes across a large range of frequencies, in some cases producing very long results, e.g. resampling an index that spans 27 years to a frequency of 12 hours.

This modifies the primary test so that it constructs time indexes whose ranges are based on the frequencies we resample to.  Now in total the tests in `test_cftimeindex_resample.py` take around 6 seconds.

@jwenfai I did some coverage analysis offline, and these tests produce the same coverage that we had before (I found it necessary to be sure to test cases where the reference index had either a shorter or longer frequency than the resample frequency).  Do you think what I have here is sufficient?  I think we could potentially shorten things even more, but I'm not sure if it's worth the effort.

 - [x] Closes #2874 

See below for the new profiling results; now the longest cftime tests are no longer associated with resample.

```
$ pytest -k cftime --durations=50
...
0.18s call     xarray/tests/test_backends.py::TestScipyInMemoryData::test_roundtrip_cftime_datetime_data
0.11s call     xarray/tests/test_backends.py::TestScipyFilePath::test_roundtrip_cftime_datetime_data
0.10s call     xarray/tests/test_backends.py::TestNetCDF4Data::test_roundtrip_cftime_datetime_data
0.09s call     xarray/tests/test_backends.py::TestNetCDF4ClassicViaNetCDF4Data::test_roundtrip_cftime_datetime_data
0.09s call     xarray/tests/test_backends.py::TestNetCDF4ViaDaskData::test_roundtrip_cftime_datetime_data
0.08s teardown xarray/tests/test_cftime_offsets.py::test_add_year_end_onOffset[julian-(2, 12)-()-<YearEnd: n=-1, month=12>-(1, 12)-()]
0.06s call     xarray/tests/test_backends.py::TestNetCDF3ViaNetCDF4Data::test_roundtrip_cftime_datetime_data
0.06s call     xarray/tests/test_backends.py::TestGenericNetCDFData::test_roundtrip_cftime_datetime_data
0.05s call     xarray/tests/test_backends.py::TestScipyFileObject::test_roundtrip_cftime_datetime_data
0.04s call     xarray/tests/test_conventions.py::TestCFEncodedDataStore::test_roundtrip_cftime_datetime_data
0.03s call     xarray/tests/test_dataset.py::test_differentiate_cftime[True]
0.03s call     xarray/tests/test_dataset.py::test_trapz_datetime[cftime-True]
0.02s call     xarray/tests/test_coding_times.py::test_contains_cftime_datetimes_dask_3d[standard]
0.02s call     xarray/tests/test_backends.py::test_use_cftime_standard_calendar_default_out_of_range[2500-gregorian]
0.02s call     xarray/tests/test_dataset.py::test_differentiate_cftime[False]
0.02s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-24-right-None-4A-MAY]
0.02s call     xarray/tests/test_backends.py::test_use_cftime_standard_calendar_default_in_range[gregorian]
0.02s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-24-None-right-11Q-JUN]
0.02s call     xarray/tests/test_backends.py::test_use_cftime_standard_calendar_default_out_of_range[2500-proleptic_gregorian]
0.02s call     xarray/tests/test_backends.py::test_use_cftime_true[1500-gregorian]
0.02s call     xarray/tests/test_backends.py::test_use_cftime_true[2500-proleptic_gregorian]
0.01s call     xarray/tests/test_backends.py::test_use_cftime_true[2000-gregorian]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-31-None-right-4A-MAY]
0.01s call     xarray/tests/test_backends.py::test_use_cftime_standard_calendar_default_out_of_range[2500-standard]
0.01s call     xarray/tests/test_backends.py::test_use_cftime_true[1500-julian]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-31-left-right-4A-MAY]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-24-right-None-11Q-JUN]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-24-None-right-4A-MAY]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-31-left-None-7M]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-24-left-None-4A-MAY]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-24-left-right-4A-MAY]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-31-None-None-11Q-JUN]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-24-right-right-4A-MAY]
0.01s call     xarray/tests/test_backends.py::test_use_cftime_standard_calendar_default_out_of_range[1500-proleptic_gregorian]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-24-left-None-11Q-JUN]
0.01s call     xarray/tests/test_backends.py::test_use_cftime_true[2500-julian]
0.01s call     xarray/tests/test_backends.py::test_use_cftime_standard_calendar_default_out_of_range[1500-gregorian]
0.01s call     xarray/tests/test_backends.py::test_use_cftime_true[1500-proleptic_gregorian]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-31-left-right-11Q-JUN]
0.01s call     xarray/tests/test_backends.py::test_use_cftime_true[2000-standard]
0.01s call     xarray/tests/test_backends.py::test_use_cftime_true[2500-standard]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-31-None-None-4A-MAY]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-31-right-right-11Q-JUN]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-24-right-right-7M]
0.01s call     xarray/tests/test_backends.py::test_use_cftime_true[2500-gregorian]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-24-left-right-7M]
0.01s call     xarray/tests/test_backends.py::test_use_cftime_true[2000-proleptic_gregorian]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-31-right-None-7M]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-31-None-right-7M]
0.01s call     xarray/tests/test_cftimeindex_resample.py::test_resample[longer_da_freq-31-left-None-11Q-JUN]
```

### CODE REVIEW

**Comment by shoyer** [comment]
Looks good to me. Thank you for looking into this promptly!

Let's wait for @jwenfai to review before merging.

**Comment by jwenfai** [comment]
Thanks for taking on the task of shortening test times! If the coverage is the same, I think the rewritten tests should be good.

Just two things I feel I should mention:
- _Testing even and odd multiples for resampling frequencies for a frequency class (e.g., '11MS' and '12M' for monthlies)_
I don't quite remember what the issue was but there were tests that passed for even/odd resampling frequencies but fail for the other. Perhaps the tests could be rewritten to (1) switch `da_freq` and `freq` and (2) use odd frequencies for constructing the DataArray so that when `* 2` and `\\ 2` operations are performed, even and odd resampling frequencies are obtained. There were some issues with resampling to `12H` so maybe use a frequency that multiplies or divides to `12H`.
- _Testing resampling from one freq type to another (e.g., from '3Q' to '11MS')_
Again I don't remember the details other than that a problem exists/existed. Perhaps something to do with `_get_range_edges` since that's the part of the code where the original index of a DataArray interacts with the resampling frequency.

Both of the problems I mentioned might have been from the earliest iteration of CFTimeIndex resampling so they might have no relevance now.

**Comment by spencerkclark** [comment]
Thanks for having a look @jwenfai!  I updated my PR following your suggestions; this added some more tests so now the total time is around 9 seconds.

I opted for listing the pairs of initial and resample frequencies explicitly rather than use a function to dynamically set one based on the other (I feel like it makes the tests easier to understand; also writing a function that converts one type of frequency to another similar-length-but-different-type frequency is messy).

**Comment by jwenfai** [comment]
Wow, that's quick. The updated tests look fine to me so go ahead and merge it.

**Comment by spencerkclark** [comment]
I'm going to go ahead and merge this; we can revisit things again if we want to continue to speed these tests up.

**Pull request merged**
