### PR TITLE
Enable subclassing the netCDF4 backend, changing the dataset class

### PR DESCRIPTION
**Pull request by ZedThree**
See #8288

- [ ] Closes #xxxx
- [ ] Tests added
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [ ] New functions/methods are listed in `api.rst`

These changes allow me to make a pretty minimal subclass that just swaps out the `netCDF4.Dataset` class for my version:

```python
from xarray.backends.netCDF4_ import NetCDF4BackendEntrypoint, NetCDF4DataStore
from ._wrapper import Dataset  # This is my netCDF extension


class NcComplexDataStore(NetCDF4DataStore):
    @classmethod
    def DatasetClass(self) -> type:
        return Dataset


class NcComplexBackendEntrypoint(NetCDF4BackendEntrypoint):
    DataStore = NcComplexDataStore
```

### CODE REVIEW

**Comment by ZedThree** [comment]
Failing with lots of timeouts in the MacOS py3.11 build, and all in `TestNetCDF4ViaDaskData`, `TestZarrDirectoryStore`, `TestZarrDictStore` -- plausibly related to this change?

**Comment by kmuehlbauer** [comment]
@ZedThree I've restarted CI, let's see if it was just flaky.

**Comment by ZedThree** [comment]
Thanks! Looks like it was just flaky

**Review by headtr1ck — COMMENTED** [review]
This change feels a bit weird, and only to support easy subclassing.
I'm in favor of optimizing for simpler subclassing but not if it makes code less readable.

Also this breaks several type checks (which in this case doesn't matter because netCDF4 is still untyped).

Maybe instead you could factor out the parts that require netCDF4 such that you can easily override these in the subclass?

**Comment by ZedThree** [comment]
Sorry, this is no longer needed, as we're now going to add the functionality straight to the netCDF4 Python library. xarray will then need only need a new argument adding here, instead of needing a whole new backend

**Pull request closed without merging**
