### PR TITLE
Move to micromamba 2

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- [ ] Closes #xxxx
- [ ] Tests added
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [ ] New functions/methods are listed in `api.rst`

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
So, not sure what's going on but this looks like an real issue. Closing for now.

**Comment by keewis** [comment]
I think there's something wrong with `setup-micromamba`. Maybe try pinning to `v2.0.0`?

**Comment by kmuehlbauer** [comment]
I've tried with one of my projects. There it works for linux and macosx with v2.0.1 but fails with all versions for windows. Here it seems it won't work at all. I'm hesitant to purge the caches as possible cause of trouble.

**Comment by keewis** [comment]
you can definitely purge the caches, they will just be recreated – it's a lot of (manual?) work, though

**Comment by kmuehlbauer** [comment]
Yes, did that, no change. Would need to find out the difference between here and https://github.com/wradlib/wradlib/actions/runs/11703040981

**Comment by keewis** [comment]
looks like that was it. @kmuehlbauer, would you report this to the `micromamba` issue tracker ([mamba-org/mamba](https://github.com/mamba-org/mamba/issues))?

**Comment by kmuehlbauer** [comment]
libmambapy seems not drop-in for conda.api :-1:

**Comment by kmuehlbauer** [comment]
@keewis https://github.com/mamba-org/mamba/issues/3576

**Comment by kmuehlbauer** [comment]
For the minimum version policy, this didn't work out. Did not find an solution, yet.

**Pull request merged**
