### PR TITLE
Fix Codecov

### LINKED ISSUE #7141: Coverage shows reduced value since mypy flag was added
### What is your issue?

The coverage was reduced from ~94% to ~68% after merging #7126 
See https://app.codecov.io/gh/pydata/xarray or our badge

I _think_ this is because the unittests never included the tests directory while mypy does. And codecov uses the sum of both coverage reports to come up with its number.

Adding the flag to the badge also does not seem to help?

Not sure how or even if that is possible to solve, maybe we need to ask in codecov?

### PR DESCRIPTION
**Pull request by headtr1ck**
- [x] Closes #7141

### CODE REVIEW

**Comment by headtr1ck** [comment]
@shoyer @max-sixty do you know who has rights to change the default branch to main on codecov.io?

**Comment by headtr1ck** [comment]
See also issue on codecov:
https://community.codecov.com/t/wrong-coverage-number-in-badge-with-flags/3975

**Comment by max-sixty** [comment]
> @shoyer @max-sixty do you know who has rights to change the default branch to main on codecov.io?

I just did this (and ofc happy to give you permission if it's helpful)

Though I still see the issue on `main` — https://app.codecov.io/gh/pydata/xarray/tree/main?displayType=list (not sure if we're expecting this to be better or not already?)

**Comment by rabernat** [comment]
I just noticed our very low coverage rating and found this PR. Did this PR work? Should we update it and merge?

It would be great to have our coverage back in the 90s rather than the 50s 😝 .

**Comment by headtr1ck** [comment]
Unfortunately it does not work :/
It seems that something is going wrong with the flags.
I have opened an issue of codecov for this, but no results so far:
https://community.codecov.com/t/wrong-coverage-number-in-badge-with-flags/3975

Feel free to push the issue :)

**Comment by headtr1ck** [comment]
I'm currently on holidays and mobile only.

@andersy005 thanks for looking into this, did your changes fix things?

You can also talk to Tom over at https://community.codecov.com/t/wrong-coverage-number-in-badge-with-flags

**Comment by andersy005** [comment]
the badge is now displaying accurate coverage, although I'm not sure what fixed the issue

[Code coverage](https://codecov.io/gh/pydata/xarray)

**Review by andersy005 — APPROVED** [review]

**Review by rabernat — APPROVED** [review]

**Comment by headtr1ck** [comment]
> the badge is now displaying accurate coverage, although I'm not sure what fixed the issue
> 
> [Code coverage](https://codecov.io/gh/pydata/xarray)

But this is even fixed on the main branch? How is this possible?

**Pull request merged**
