### PR TITLE
Convert attribute and dimension names to strings when generating HTML repr

### PR DESCRIPTION
**Pull request by bcbnz**
The standard repr() already handled non-string attribute names, but the HTML formatter failed when trying to escape HTML entitites in non-string names. This just calls str() before escape(). It also includes tests for Dataset, DataArray and Variable.

Reported in #5146. ~~Note that there may be a need to do the same for dimension names if they are allowed to be strings. Currently dimensions must be created as strings but can later be renamed to non-strings, see #5148.~~ Dimensions can be non-str, updated.

- [x] Tests added
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by bcbnz** [comment]
I guess to be safe we could convert dimension names to string when formatting. The repr() of datasets with non-strings will still fail (arrays will work though).

**Comment by bcbnz** [comment]
Added conversion of dimension names since non-string dimensions are intended to be supported. This will still fail for datasets as the dimension sorting does not yet support this.

**Comment by keewis** [comment]
thanks, @bcbnz. You could add a entry to `whats-new.rst` (bug fixes), but otherwise this should be ready.

**Comment by max-sixty** [comment]
Looks like other people are hitting this given #5240. 

Would be great to get this in for 0.18.0 https://github.com/pydata/xarray/issues/5232

**Comment by shoyer** [comment]
`whats-new.rst` is really optional (nice to have)... I would vote for just merging at this point! I will probably do so tomorrow :)

**Comment by shoyer** [comment]
Thanks @bcbnz !

**Pull request merged**
