### PR TITLE
Fix name loss when masking

### LINKED ISSUE #2457: name of array disappear when apply "where" filter with Datarray but not with np.array
I was trying to select by non dimensional coordinate, and I found that "where" works well, but it erase the name of my datarray only if filtering is done with another datarray as a non dimensional coordinate
```
import xarray as xr
temp = 15 + 8 * np.random.randn(2, 2, 3)

precip = 10 * np.random.rand(2, 2, 3)

lon = [[-99.83, -99.32], [-99.79, -99.23]]

lat = [[42.25, 42.21], [42.63, 42.59]]
ds = xr.Dataset({'temperature': (['x', 'y', 'time'],  temp)},
                 coords={'lon': (['x', 'y'], lon),
                         'lat': (['x', 'y'], lat),
                         'precipitation': (['x', 'y', 'time'], precip),
                         'time': pd.date_range('2014-09-06', periods=3),
                         'reference_time': pd.Timestamp('2014-09-05')})

ds["temperature"].where(ds.precipitation>5).sum(axis=2).plot()
```
this line would produce a label near color bar
but only using a numpy array this happens as here
```
ds["temperature"].where(ds.precipitation.values>5).sum(axis=2).plot()
```

#### Expected Output
I think that selecting with a datarray should  not change the label of the data.
Further I was expecting that as for  "sel", "where" should change the title of the graph
so that I know from the title that I performed a selection with where with a non dimensional  coordinate

### PR DESCRIPTION
**Pull request by yohai**
- [x] Closes #2457 #2748
 - [x] Tests added
 - [x] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

I took a simple-minded strategy to fix: just mask and then rename the result to `self.name`. This is a slight overkill since the renaming will be done on every masking, not just on the edge cases when it's needed, but this is really a very small computational cost and it's much easier and bulletproof.

### CODE REVIEW

**Comment by shoyer** [comment]
This looks fine, though I'd rather fix this at a lower level, if possible.

This line in `computation.py` sets the name on result DataArray objects:
https://github.com/pydata/xarray/blob/0dfc0e63650deb3da1fb1cba48cda88a704c2d60/xarray/core/computation.py#L210

If `keep_attrs=True` (you'll need to thread the argument into `apply_dataarray_ufunc` from `apply_ufunc`), then we should just copy the name from the first argument instead, e.g., `name = args[0].name if keep_attrs else result_name(args)`.

**Comment by yohai** [comment]
I agree that my solution is a bit hacky, but from a computational cost viewpoint they are identical (or almost. I don't think there's a way to avoid one if statement per call of `where`). I thought my solution is good because catching this at a high level captures all possible edge cases that we might miss at lower ones. But I can try to do what you suggested to.

**Comment by yohai** [comment]
@shoyer your fix works. I think it's ready to merge.

**Comment by shoyer** [comment]
thanks Yohai!

**Pull request merged**
