### PR TITLE
CI: Pin scientific-python/upload-nightly-action to release sha

### PR DESCRIPTION
**Pull request by matthewfeickert**
* For security best practices, use the action from known commit shas that correspond to tagged releases. These can be updated via dependabot.
   - Amends PR https://github.com/pydata/xarray/pull/7865

c.f. https://github.com/scientific-python/upload-nightly-action/pull/13 for additional context.

I'll suggest @martinfleis and @keewis for reviewers.

- [N/A] Closes #xxxx
- [N/A] Tests added
- [N/A] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [N/A] New functions/methods are listed in `api.rst`

### CODE REVIEW

**Review by martinfleis — APPROVED** [review]
I suppose it doesn't hurt to specify commit hash but why not just pointing to the version tag like with practically any other action?

**Comment by matthewfeickert** [comment]
> I suppose it doesn't hurt to specify commit hash but why not just pointing to the version tag like with practically any other action?

This is discussed in the linked PR in the PR body (here again: https://github.com/scientific-python/upload-nightly-action/pull/13) but the 1 liner answer is that `@main` is not good security practice and should just be generally avoided, and anytime you're touching the open source packaging supply chain you want to take additional security measures to make sure it is as hard as possible for an upstream mistake to cause a lot of pain. The https://github.com/pypa/gh-action-pypi-publish team asks that people take additional precautions as well, and we've taken a lot of recommendations from them on the subject, though I will admit that their README has a softened stance to tag name over commit sha.

**Comment by max-sixty** [comment]
I would vote to use the version number. We want to keep up-to-date, and we're not going to be able to audit the uploader on each change — so I don't see a significant benefit from using the hash, and we lose dependabot.

**Comment by matthewfeickert** [comment]
> so I don't see a significant benefit from using the hash, and we lose dependabot.

c.f. https://github.com/dependabot/dependabot-core/issues/4691

**Comment by max-sixty** [comment]
> > so I don't see a significant benefit from using the hash, and we lose dependabot.
> 
> c.f. [dependabot/dependabot-core#4691](https://github.com/dependabot/dependabot-core/issues/4691)

Oh — so dependabot will update the hash? Great!! Thanks for finding this

**Review by keewis — APPROVED** [review]

**Comment by keewis** [comment]
thanks, @matthewfeickert

**Comment by matthewfeickert** [comment]
> Oh — so dependabot will update the hash? Great!! Thanks for finding this

@max-sixty @martinfleis Yes, sorry for the short replies &mdash; was moving between things. :grimacing: 

Yeah, this was actualy a recent find for me too, but I've been pretty impressed so far.

If anything here goes screwy though in the future, please feel free to just ping me as I'm more than happy to try to help out on anything that I've introduced. But I hope this is all super smooth sailing, and thanks for being users of the uploader and thanks to the team for `xarray`! :rocket:

**Comment by max-sixty** [comment]
Awesome, thank you very much @matthewfeickert !

**Comment by matthewfeickert** [comment]
For posterity, here's a recent example of Dependabot bumping the pinned `upload-nightly-action` from `0.2.0` to `0.3.0` for `networkx`: https://github.com/networkx/networkx/pull/7266

**Pull request merged**
