### PR TITLE
attempt to fix #497

### LINKED ISSUE #497: Better error message when reading netCDF4 file and netCDF4 not installed
Trying to load a file without netcdf4 dependency:

```
xray.open_dataset('20150629_ave_mrr.nc')

...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/clark.fitzgerald/projects/mrr/june29_analysis.py in <module>()
      7 import xray
      8
----> 9 mrr = xray.open_dataset('20150629_ave_mrr.nc')

/Users/clark.fitzgerald/anaconda/envs/xray_dev/lib/python2.7/site-packages/xray-0.5.2_98_g69f7386-py2.7.egg/xray/backends/api.pyc in open_dataset(filename_or_obj, group, decode_cf, mask_and_scale, decode_times, concat_characters, decode_coords, engine, chunks, lock)
    166                 store = backends.NetCDF4DataStore(filename_or_obj, group=group)
    167             elif engine == 'scipy':
--> 168                 store = backends.ScipyDataStore(filename_or_obj)
    169             elif engine == 'pydap':
    170                 store = backends.PydapDataStore(filename_or_obj)

/Users/clark.fitzgerald/anaconda/envs/xray_dev/lib/python2.7/site-packages/xray-0.5.2_98_g69f7386-py2.7.egg/xray/backends/scipy_.pyc in __init__(self, filename_or_obj, mode, format, group, writer, mmap)
     95             filename_or_obj = BytesIO(filename_or_obj)
     96         self.ds = scipy.io.netcdf_file(
---> 97             filename_or_obj, mode=mode, mmap=mmap, version=version)
     98         super(ScipyDataStore, self).__init__(writer)
     99

/Users/clark.fitzgerald/anaconda/envs/xray_dev/lib/python2.7/site-packages/scipy/io/netcdf.pyc in __init__(self, filename, mode, mmap, version)
    216
    217         if mode == 'r':
--> 218             self._read()
    219
    220     def __setattr__(self, attr, value):

/Users/clark.fitzgerald/anaconda/envs/xray_dev/lib/python2.7/site-packages/scipy/io/netcdf.pyc in _read(self)
    506         if not magic == b'CDF':
    507             raise TypeError("Error: %s is not a valid NetCDF 3 file" %
--> 508                             self.filename)
    509         self.__dict__['version_byte'] = fromstring(self.fp.read(1), '>b')[0]
    510

TypeError: Error: 20150629_ave_mrr.nc is not a valid NetCDF 3 file
```

It would be more helpful to suggest that the user install netcdf4.

### PR DESCRIPTION
**Pull request by gidden**
- [x] closes #497
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry

This is a suggested fix to #497. I am happy to clean it up, etc., if the maintainers think it is worthwhile.

### CODE REVIEW

**Comment by shoyer** [comment]
This seems like an improvement over what we have now. So yes, please do clean it up and we can merge it!

**Comment by gidden** [comment]
ok, should be cleaned up and ready to go @shoyer

**Comment by gidden** [comment]
hey @shoyer, this is failing one each of a dataset and dataarray test. I am not sure why, could you please assist? thanks!

**Comment by shoyer** [comment]
@gidden this isn't you -- pytest broke us (I'll merge https://github.com/pydata/xarray/pull/1423 with a fix shortly)

**Comment by gidden** [comment]
sounds good!

**Comment by shoyer** [comment]
Thanks @gidden!

**Comment by gidden** [comment]
Very welcome, @shoyer!

**Pull request merged**
