### PR TITLE
Add doctests to release notes

### PR DESCRIPTION
**Pull request by max-sixty**
Any other changes?

### CODE REVIEW

**Comment by dcherian** [comment]
LGTM. thanks Max

**Comment by keewis** [comment]
first of all, current `master` fails to build on RTD, which is because of a title underline being too short, and a typo in the new dev version section: https://github.com/pydata/xarray/blob/788cd605d8270c6aeb6435eb0760eb5f2d97228a/doc/whats-new.rst#L18-L22

Other than that, I noticed we had a few PRs that merged into `stable`, which means that these commits were lost during the release. I guess these PRs were opened using RTD's `Edit on Github` links while viewing the `stable` docs, so a fix would be related to #2821.

**Comment by max-sixty** [comment]
Thanks for spotting those @keewis , let me fix

**Comment by keewis** [comment]
I cherry-picked the commits to `master`, so only the fix for the `Edit on Github` is left

**Comment by max-sixty** [comment]
Ah great! I was just trying to figure out why I couldn't find them! Thanks!

**Comment by max-sixty** [comment]
In lieu of fixing https://github.com/pydata/xarray/issues/2821, we could add a step to the release doc to merge stable into master — would that fix the problem?

**Comment by keewis** [comment]
it should, but I'm not sure if we'd have other issues instead. I guess we could do both?

**Pull request merged**
