### PR TITLE
Allow all interp methods in typing

### PR DESCRIPTION
**Pull request by Illviljan**
Follow up from #6637.

### CODE REVIEW

**Comment by Illviljan** [comment]
Was just a typo @headtr1ck right? I'm not missing something?

**Comment by headtr1ck** [comment]
> Was just a typo @headtr1ck right? I'm not missing something?

I was not sure about that when I started the typing additions. I took the ones listed in the docstring.
But if mypy does not complain and the underlying functions support that it should be fine.
Thats the nice thing about typing ;)

**Comment by headtr1ck** [comment]
@Illviljan you should enable pre-commit hooks :)

**Comment by Illviljan** [comment]
pre-commit hooks doesn't play nicely with Github Desktop, so that's why I don't use it.

**Pull request merged**
