### PR TITLE
remove requirement for setuptools.pkg_resources

### LINKED ISSUE #5676: Do not require on pkg_resources as it drastically increases import time.
**Is your feature request related to a problem? Please describe.**
Most of the import time of xarray is wasted by importing pkg_resources. As far as I could see, the module is used to set the version number of xarray. So importing xarray takes like 0.275s (old machine) and of this 0.17s are just spent in importing pkg_resources.

**Describe the solution you'd like**
There are better approaches to set the version number than to use this heavy weight module. For instance `setuptools_scm`.

**Describe alternatives you've considered**

**Additional context**
xarray-version 0.19.0

### PR DESCRIPTION
**Pull request by marscher**
Fixes #5676

Now depends on importlib-metadata for Python major version < 3.8

- [x] Closes #5676
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by keewis** [comment]
> is there any reason not to merge this?

the issue is that with `conda` we can either always install `importlib_metadata` or not at all: `conda` doesn't support `noarch_python` packages with preprocessing selectors (see the comments around https://github.com/pydata/xarray/issues/4295#issuecomment-667657310 for more discussion).

`importlib.metadata` is included in `python>=3.8`, which we can officially require from end of December this year.

All of this means that if we want to merge this now we have to decide between not releasing until we can drop `python=3.7` or always installing on `importlib_metadata` (which is what the `pint` feedstock does). However, I guess the cleanest way would be to wait until we can require `python>=3.8`.

**Comment by marscher** [comment]
I don't think that noarch packages are restricted to python version selectors any more. I've tested this locally with a dummy recipe like this:
```yaml
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - importlib_metadata # [ py < 38]
```
This creates a noarch package as expected with a recent conda/build version.

**Comment by dcherian** [comment]
Thanks @marscher This is a great change.

I see this is your first PR. Welcome to Xarray!

**Comment by marscher** [comment]
> Thanks @marscher This is a great change.
> 
> I see this is your first PR. Welcome to Xarray!

Thanks for the warm welcome.

**Pull request merged**
