### PR TITLE
Handle bool in NetCDF4 conversion

### PR DESCRIPTION
**Pull request by khaeru**
I am working on some code that creates `xray.Datasets` with a 'bool' dtype.

Trying to call `Dataset.to_netcdf()` on this code causes `_nc4_values_and_dtype()` to raise a `ValueError`, so I added these few lines to force the storage of these variables as 1-byte integers.

Perhaps it should be 'u1' instead; I can change that if need be.

### CODE REVIEW

**Comment by jhamman** [comment]
How does this handle the round trip conversion from `Dataset` to `netCDF` and back to `Dataset`.  Do you now get an array of `u1`?

Also, it may be good to add a unit test addressing your previous `ValueError`.

**Comment by shoyer** [comment]
This seems like a pragmatic choice -- but I agree, it's unfortunate that we can't roundtrip this faithfully. 

One option would be to add the attribute `dtype` with the value `'bool'` to the netCDF variable, and then teach xray to interpret that attribute when loading data. We already do some pretty similar things to handle datetime64 variables according to the CF conventions. If you're interested in doing this, the right place to put this would be `conventions.py`:
https://github.com/xray/xray/blob/eed58d5cb4274f262e77277bc8fcf394a9fae77c/xray/conventions.py#L632 (for decode, put decoding dtypes after decoding times at the bottom)
https://github.com/xray/xray/blob/eed58d5cb4274f262e77277bc8fcf394a9fae77c/xray/conventions.py#L603 (for encoding, write another little helper function and call it at the bottom here)

The other advantage of putting this in conventions is that then it works with all netCDF backends (including scipy and h5netcdf).

Also, this definitely needs tests :). This could be as simple as verifying that it works to roundtrip a Dataset with boolean data to disk and back. Here's an example of what those look like:
https://github.com/xray/xray/blob/eed58d5cb4274f262e77277bc8fcf394a9fae77c/xray/test/test_backends.py#L156

**Comment by khaeru** [comment]
Thanks—putting this up was evidently the fastest ways to get pointers to those examples in the code!

I'll add those items and comment again once I have.

**Comment by jhamman** [comment]
@khaeru - do you think you're going to come back to this?

**Comment by klapo** [comment]
I also ran into this problem -- I wanted to save a netcdf with a boolean array. Casting the booleans as ints worked for my application.

**Comment by shoyer** [comment]
Karl -- if you or anyone else wants to pick up and finish this PR, that
would be awesome. It is very close to being done.

**Comment by jhamman** [comment]
@shoyer - reading back in this thread (https://github.com/pydata/xarray/pull/401#issuecomment-96085330) you mentioned moving this fix to `conventions.py` and writing a `dtype: bool` attribute for `bool` typed variables.  Do you still think that makes since?  

Alternatively, we could just raise a warning when typecasting on write.  This is the lazy but less intrusive way of operating.

**Comment by shoyer** [comment]
Yes, I still think that makes sense. I don't like issuing warnings other
than for deprecation cycles.

**Comment by khaeru** [comment]
@jhamman thanks for taking this up and finishing it!

**Pull request closed without merging**
