### PR TITLE
Coordinate -> IndexVariable and other deprecations

### LINKED ISSUE #727: DataArray creation prone to errors when data shares dimension shapes
It seems like there would be unexpected behavior whenever someone creates a DataArray using data with some subset of dimensions that have the same shape, and when supplying coords as a dictionary of `coord_name: coords` pairs. Since the dictionary isn't ordered, won't it be unclear which dimension it is referring to?

Maybe that's not such a good description, here's an example:
```python
data = np.random.randn(20, 5, 5)
da = xarray.DataArray(data, {'1': np.arange(20),
                             '2': np.arange(15, 20),
                             '3': np.arange(5, 10)})
print(da.coords)

da = xarray.DataArray(data, {'10': np.arange(20),
                             '11': np.arange(15, 20),
                             '12': np.arange(5, 10)})
print(da.coords)
```

For the first dimension it's no problem, since it's the only one with length 20. For the 2nd and 3rd dimensions since they are the same shape, the coordinates will be assigned depending on which order python takes the keys, which means they could sometimes be flipped depending on something arbitrary like what you named a dimension.

It seems like this could be addressed by doing a quick check (when supplying coordinates in this fashion) to see if any of the dimensions of the coordinates are the same, and throwing a warning that behavior might be unstable. Or maybe it throws an error and says "if data coordinates are same length, please supply coordinate values in a tuple or list instead"?

### PR DESCRIPTION
**Pull request by shoyer**
- Renamed the ``Coordinate`` class from xarray's low level API to
  ``IndexVariable``. xref https://github.com/pydata/xarray/pull/947#issuecomment-238549129
- Deprecated supplying ``coords`` as a dictionary to the ``DataArray``
  constructor without also supplying an explicit ``dims`` argument. The old
  behavior encouraged relying on the iteration order of dictionaries, which is
  a bad practice (fixes #727).
- Removed a number of methods deprecated since v0.7.0 or earlier:
  ``load_data``, ``vars``, ``drop_vars``, ``dump``, ``dumps`` and the
  ``variables`` keyword argument alias to ``Dataset``.

### CODE REVIEW

**Comment by shoyer** [comment]
> Maybe we should also rename Variable.to_coord() and IndexVariable.to_coord()?

Good catch, I meant to include this.

**Comment by shoyer** [comment]
@benbovy any preference on whether I should submit this before or after your PR?

**Comment by benbovy** [comment]
@shoyer feel free to merge this when you want. I can rebase my branch and resolve conflicts if needed.

**Comment by shoyer** [comment]
OK, in it goes!

**Pull request merged**
