### PR TITLE
COMPAT: Adjust CFTimeIndex.get_loc for pandas 2.0 deprecation enforcement

### PR DESCRIPTION
**Pull request by mroeschke**
With the upcoming pandas 2.0 release, we are enforcing a deprecation in `pd.Index.get_loc` to remove `method` and `tolerance`.  Just in case `get_loc` isn't 100% compatible with `get_indexer`, I structured the `elif` to use `get_loc` as much as possible. Let me know if any other adjustments are needed

### CODE REVIEW

**Review by spencerkclark — COMMENTED** [review]
Thanks for looking out for this @mroeschke!

I wonder if it's appropriate to simply remove these arguments altogether following pandas?  Since we were calling `Index.get_loc` under the hood, the deprecation warning would have already been raised for anyone who used them (I suppose except in the case that a string key was provided, where the arguments would be ignored):

```
>>> import cftime; import xarray as xr
>>> times = xr.cftime_range("2000", periods=3)
>>> times.get_loc(cftime.DatetimeGregorian(2000, 1, 1), method="nearest")
/Users/spencer/software/xarray/xarray/coding/cftimeindex.py:468: FutureWarning: Passing method to CFTimeIndex.get_loc is deprecated and will raise in a future version. Use index.get_indexer([item], method=...) instead.
  return pd.Index.get_loc(self, key, method=method, tolerance=tolerance)
0
```

I don't think this would break anything internally (I believe we already use `get_indexer` in `Dataset.sel` for instance).

**Comment by mroeschke** [comment]
> I wonder if it's appropriate to simply remove these arguments altogether following pandas?

Sure, happy to remove this `method` and `tolerance` from `CFTimeIndex.get_loc`. Would that require a deprecation in xarray or can they simply be removed if `CFTimeIndex.get_loc` is "private"?

**Comment by spencerkclark** [comment]
Technically I think we would consider `get_loc` to be public (both due to how it is named and in that [it is at least primitively documented](https://docs.xarray.dev/en/stable/generated/xarray.CFTimeIndex.get_loc.html#xarray.CFTimeIndex.get_loc)).  That said, I don't know how many people use the lower level methods of CFTimeIndexes like `get_loc` outside of xarray data structures.

My inclination is that it would not require a deprecation cycle, given the warning had already been being raised as in the example above.  It's true though that this warning was not being emitted in the case that `key` was a string, so perhaps it's a little borderline.  Maybe @dcherian or @mathause, do you have any thoughts?

**Comment by dcherian** [comment]
>  I don't know how many people use the lower level methods of CFTimeIndexes like get_loc outside of xarray data structures.

I sometimes do this with a general `pd.Index` but it's pretty rare. In any case, I think any user using `get_loc` would be fairly advanced and can figure out the workaround pretty easily.

@aulemahal does `xclim` or its related packages use `CFTimeIndex.get_loc` at all to convert a label to an integer index?

**Comment by mroeschke** [comment]
I guess this could be a "Breaking Change" in the next release's What's New. Let me know if that's the direction you're still leaning

**Comment by spencerkclark** [comment]
Yes, I think that's what we'll end up going with @mroeschke.  Thanks for your patience as we worked it out.

**Comment by mroeschke** [comment]
Great added the whatsnew note and just removed the arguments

**Review by spencerkclark — APPROVED** [review]
Looks good.  Thanks!

**Comment by mathause** [comment]
Thanks @mroeschke

**Pull request merged**
