### PR TITLE
Ensure group names are preserved on update.

### LINKED ISSUE #9285: DataTree.update can cause multiple root groups.
### What happened?

Reviewing documentation for hierarchical-data.rst I saw the abe/herbert example didn't look right, updated the `abe.assign()` -> `abe = abe.assign()` and it still looked wrong

``` 
>>> abe = xr.DataTree(name="abe")
>>> herbert = xr.DataTree(name="Herb")

>>> abe.update({"herbert": herbert})

>>> print(abe)
<xarray.DataTree 'abe'>
Group: /
└── Group: /
>>> print(abe.groups)
('/', '/')
```

### What did you expect to happen?

I expected not to see two root groups.

### Minimal Complete Verifiable Example

```Python
abe = xr.DataTree(name="abe")
herbert = xr.DataTree(name="Herb")

abe.update({"herbert": herbert})
print(abe)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Relevant log output

_No response_

### Anything else we need to know?

it is failing the update or the assign (but because assign uses update)

### Environment

<details>

/Users/savoie/.pyenv/versions/miniconda3-4.7.12/envs/xarray-tests/lib/python3.11/site-packages/_distutils_hack/__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit: 9e4b737ee0907e16703dab79e118e51b1fc36d46
python: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:45:13) [Clang 16.0.6 ]
python-bits: 64
OS: Darwin
OS-release: 23.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.14.3
libnetcdf: 4.9.2

xarray: 2024.6.1.dev88+g068bab28b.d20240724
pandas: 2.2.2
numpy: 1.26.4
scipy: 1.13.0
netCDF4: 1.6.5
pydap: installed
h5netcdf: 1.3.0
h5py: 3.11.0
zarr: 2.17.2
cftime: 1.6.3
nc_time_axis: 1.4.1
iris: 3.9.0
bottleneck: 1.3.8
dask: 2024.4.2
distributed: 2024.4.2
matplotlib: 3.8.4
cartopy: 0.23.0
seaborn: 0.13.2
numbagg: 0.8.1
fsspec: 2024.3.1
cupy: None
pint: 0.23
sparse: 0.15.1
flox: 0.9.6
numpy_groupies: 0.10.2
setuptools: 69.5.1
pip: 24.0
conda: None
pytest: 8.1.1
mypy: 1.8.0
IPython: 8.25.0
sphinx: None

</details>

### PR DESCRIPTION
**Pull request by flamingbear**
- [X] Closes #9285
- [X] Tests added

### CODE REVIEW

**Comment by flamingbear** [comment]
Closing because #9297 will be done soon.

**Comment by TomNicholas** [comment]
This fixes the problem and adds a regression test, so I think we should just merge this too.

**Comment by TomNicholas** [comment]
Wait this is now a zero-line PR?!? Guess we don't need it anymore then haha

**Comment by flamingbear** [comment]
> Wait this is now a zero-line PR?!? Guess we don't need it anymore then haha

Yup, looks like @eni-awowale added these changes too. 🙃

**Comment by flamingbear** [comment]
Unless you want to merge no changes to close the issue

**Pull request closed without merging**
