### PR TITLE
Fix bulleted list indentation in docstrings

### LINKED ISSUE #5248: Appearance of bulleted lists in docs
**What happened**:

The new docs are looking great! One small issue — the lists don't appear as lists; e.g. 
image

from https://xarray.pydata.org/en/latest/generated/xarray.Dataset.query.html

Do we need to change the rst convention?

**What you expected to happen**:

As bullets, with linebreaks

### PR DESCRIPTION
**Pull request by andersy005**
- [x] Closes #5248
- [x] Passes `pre-commit run --all-files`

As I understand it, the issue described in #5248 is caused by bad indentation... With this PR, we get the following:

Screen Shot 2021-05-02 at 11 06 41 PM

@max-sixty, let me know if there are other instances that need to be fixed as part of this PR....

### CODE REVIEW

**Comment by max-sixty** [comment]
That looks great! Thanks!

If there's a way of auto-failing anything that violates this, that would keep it good. But maybe the previous text is indistinguishable from normal prose...

Not worth worry about at all — really — FYI this looks a tiny bit inconsistent:
image

**Comment by andersy005** [comment]
@max-sixty, the inconsistencies are now fixed...

**Comment by andersy005** [comment]
> If there's a way of auto-failing anything that violates this, that would keep it good. But maybe the previous text is indistinguishable from normal prose...

Not sure there's a way to automatically detecting these issues :(

**Review by max-sixty — APPROVED** [review]
Perfect!

**Comment by keewis** [comment]
the initial issue, at least, would have been caught by `velin`

**Comment by andersy005** [comment]
> the initial issue, at least, would have been caught by velin

Right... In a previous comment https://github.com/pydata/xarray/pull/4872#issue-568848688 you mentioned that the primary reason the `velin` hook was deactivated is because of the package maturity. Have you had a chance to test drive it lately? Is there a timeline on when we should activate it?

https://github.com/pydata/xarray/blob/9f118624e7924c80fc305f351fa9621d2b58514c/.pre-commit-config.yaml#L27-L30

**Comment by max-sixty** [comment]
Maybe it's time to let Velin spring free! @keewis up to you, as ever

**Comment by max-sixty** [comment]
@andersy005 I'll hit the button here, if that's OK with you?

**Comment by andersy005** [comment]
Thanks, @max-sixty

**Comment by max-sixty** [comment]
Thank you @andersy005 !

**Comment by keewis** [comment]
> Have you had a chance to test drive it lately?

> Maybe it's time to let Velin spring free!

no, not recently. I'll need to investigate more, but I think we should probably do that soon. There should be standard rst linters, too, but those might need more configuration: `sphinx` adds a lot of new directives.

**Pull request merged**
