### PR TITLE
Implement @ operator for DataArray

### PR DESCRIPTION
**Pull request by max-sixty**
- [x] Closes https://github.com/pydata/xarray/issues/1053
 - [x] Tests added
 - [x] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

Is it really this easy? What am I missing?

### CODE REVIEW

**Comment by max-sixty** [comment]
Any thoughts, team?

**Comment by shoyer** [comment]
This looks good to me!

In general, it's a good idea to also define reflexive methods, e.g., `__rmatmul__` in this case. But I'm not sure we actually need that, given that `dot` only supports operations with xarray.DataArray at present.

I guess this could be useful for people writing subclasses, or other objects that override arithmetic with xarray objects. So you might as well add something like:
```
def __rmatmul__(self, other):
    return xarray.dot(other, dot)
```

**Comment by dcherian** [comment]
Do we need a line here? https://xarray.pydata.org/en/stable/computation.html#basic-array-math

**Comment by shoyer** [comment]
It might be worth using @ instead of dot() in the docs in a few places, but
I don't think it's essential to mention it specifically.

**Comment by max-sixty** [comment]
Great - I added `rmatmul` and a v short example in the basic-array-math section. LMK if good to merge

**Comment by max-sixty** [comment]
LMK if good to merge! 

(coming from the person with a terrible record of finishing PRs... 😉 )

**Pull request merged**
