### PR TITLE
passing missing arguments when opening zarr, hdf5 and netcdft4 datatrees

### LINKED ISSUE #9427: arguments not passed to `open_groups_as_dict` function when opening a datatree
### What is your issue?

Hi everyone, 

I am trying to open a datatree I created, which looks as follows.

```python
Group: /
├── Group: /group_0
│   │   Dimensions:  (x: 4, y: 5)
│   │   Coordinates:
│   │     * x        (x) int64 32B 10 20 30 40
│   │     * y        (y) datetime64[ns] 40B 2000-01-01 2000-01-02 ... 2000-01-05
│   │   Data variables:
│   │       foo      (x, y) float64 160B ...
│   ├── Group: /group_0/subgroup_1
│   └── Group: /group_0/subgroup_2
│       │   Dimensions:  (x: 4, y: 5, dim_0: 9)
│       │   Coordinates:
│       │     * x        (x) int64 32B 10 20 30 40
│       │     * y        (y) datetime64[ns] 40B 2000-01-01 2000-01-02 ... 2000-01-05
│       │   Dimensions without coordinates: dim_0
│       │   Data variables:
│       │       a        (dim_0) int64 72B ...
│       └── Group: /group_0/subgroup_2/subsubgroup_1
│           │   Dimensions:  (x: 4, y: 5, dim_0: 9)
│           │   Coordinates:
│           │     * x        (x) int64 32B 10 20 30 40
│           │     * y        (y) datetime64[ns] 40B 2000-01-01 2000-01-02 ... 2000-01-05
│           │   Dimensions without coordinates: dim_0
│           │   Data variables:
│           │       a        (dim_0) int64 72B ...
│           └── Group: /group_0/subgroup_2/subsubgroup_1/subsubsubn
│                   Dimensions:  (x: 4, y: 5, dim_0: 9)
│                   Coordinates:
│                     * x        (x) int64 32B 10 20 30 40
│                     * y        (y) datetime64[ns] 40B 2000-01-01 2000-01-02 ... 2000-01-05
```

However, if I wanted to select and specific groups as follows 

```python
path = "/path/to/datatree/hdf_dtree_10.h5"
dtree = open_datatree(path, engine='h5netcdf', group="subgroup_1")

```
The output is the whole `datatree`. Digging around. I found out that some parameters passed to https://github.com/pydata/xarray/blob/a8c989673d0ea0cd099ede136efa117eaeb7ae1d/xarray/backends/h5netcdf_.py#L454 are missing, including the `group` parameter. A similar situation happens with netcdf4 datatrees

### PR DESCRIPTION
**Pull request by aladinor**
- [x] Closes #9427
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Review by TomNicholas — COMMENTED** [review]
@kmuehlbauer or @keewis would you mind just confirming that this is the correct way to handle these kwargs?

**Comment by kmuehlbauer** [comment]
@TomNicholas Yes, I think this is correct. I'm not sure if this can be restructured and would rely on @keewis expertise.

**Comment by keewis** [comment]
sorry for the delay, I've been far away from any computer for the past two weeks.

I'd say short of adding the arguments to `**kwargs` that's the only thing we can do, as really we're just forwarding to `open_groups_as_dict` (which by the way I thought we wanted to call just `open_groups`? Maybe I missed some discussion on that).

**Comment by keewis** [comment]
this should be pretty uncontroversial, so I'm merging this now

**Pull request merged**
