### PR TITLE
Add HDF5 Section to read/write docs page

### PR DESCRIPTION
**Pull request by rwegener2**
## Overview

This PR adds an HDF5 section to the "Reading and Writing Files" section of the documentation. It discusses the features and limitations of opening HDF5 data in xarray.

PR spun out of discussion #6299.

- [x] Adds documentation

## Discussion 
To keep in line with other sections it would make sense to speak to xarray's ability to write HDF5 data. The `.to_netcdf()` function does write files that can be read with HDF5 cli tools, which makes sense given that (as I understand it) a netCDF4 file is a slightly stricter implementation of the HDF5 data model. The [netCDF4 docs](https://docs.unidata.ucar.edu/netcdf-c/current/interoperability_hdf5.html) even say:

> The HDF5 Files produced by netCDF-4 are perfectly respectable HDF5 files, and can be read by any HDF5 application

Still, it seems odd to recommend users write HDF5 files with a function called `.to_netcdf()`. What do others think the proper tone is to take for writing files? Encourage `.to_netcdf()`? Mention it cautiously? Ignore it all together?

### CODE REVIEW

**Comment by dcherian** [comment]
Thanks @rwegener2  This is a great first PR! Welcome.

>  it seems odd to recommend users write HDF5 files with a function called .to_netcdf(). What do others think the proper tone is to take for writing files? Encourage .to_netcdf()?

I think its OK to encourage `to_netcdf`. Xarray is built around the netCDF4 model.

**Review by TomNicholas — APPROVED** [review]

**Comment by rwegener2** [comment]
> I think its OK to encourage to_netcdf. Xarray is built around the netCDF4 model.

Sounds good @dcherian! I added a sentence for writing HDF5 data.

Let me know if there is anything else that should change, otherwise I think it's done.

**Comment by dcherian** [comment]
I think this is great. Thanks @rwegener2! This is a great first contribution, and it address one of the top 3 questions new users ask about Xarray (in my experience).

Welcome to Xarray

**Comment by rwegener2** [comment]
Thanks @dcherian! Happy to be here and so happy my first PR could be a useful one!

**Pull request merged**
