### PR TITLE
Add persist method to DataSet

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes https://github.com/pydata/xarray/issues/1344

 - [x] closes #xxxx
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry  (not sure what to do here, is there a new section?  It looks like the last release was yesterday)

### CODE REVIEW

**Comment by mrocklin** [comment]
I suspect that there is more to do here, but I wanted to get the ball rolling on this.

cc @shoyer @rabernat @pwolfram

**Comment by rabernat** [comment]
Would it make sense to have `persist` for DataArrays as well? My opinion is: yes.

**Comment by shoyer** [comment]
Thanks @mrocklin! This is a great start.

Yes, it would be great to have this on `DataArray` as well. The implementation would be a two liner:
```
    def persist(self):
        ds = self._to_temp_dataset().persist()
        return self._from_temp_dataset(ds)
```

I just pushed a commit to master adding a "what's new" template for v0.9.3.

**Comment by mrocklin** [comment]
Added DataArray.persist and a whats new entry

**Comment by rabernat** [comment]
Would also probably be good to document this a bit in the section on dask:
https://github.com/pydata/xarray/blob/master/doc/dask.rst

**Comment by mrocklin** [comment]
Added docs.  Also removed section on dask.array not providing automatic chunk alignment (this is now supported)

**Comment by rabernat** [comment]
This looks good to go from my point of view!

**Comment by shoyer** [comment]
Thanks @mrocklin!

I'm glad to see your first commit on the xarray side :).

**Comment by mrocklin** [comment]
Happy to contribute :)

**Comment by rabernat** [comment]
> I'm glad to see your first commit on the xarray side :).

Hopefully the first of many!

**Pull request merged**
