### PR TITLE
Removed skipna argument from count, any, all [GH755]

### LINKED ISSUE #755: count docstring mistakenly includes skipna
Is this a mistake or am I missing something?

http://xray.readthedocs.org/en/stable/generated/xarray.DataArray.count.html?highlight=count#xarray.DataArray.count

> skipna : bool, optional
> If True, skip missing values (as marked by NaN). By default, only skips missing values for float dtypes; other dtypes either do not have a sentinel missing value (int) or skipna=True has not been implemented (object, datetime64 or timedelta64).

### PR DESCRIPTION
**Pull request by sjvrijn**
- [x] Closes #755
 - [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

Could not confirm in the web-based documentation (see #4257), but manually confirmed to work:
```python
>>> import xarray as xr
>>> help(xr.DataArray.count)
Help on function count in module xarray.core.common:

count(self, dim=None, axis=None, **kwargs)
    Reduce this DataArray's data by applying `count` along some dimension(s).

    Parameters
    ----------
    dim : str or sequence of str, optional
        Dimension(s) over which to apply `count`.
    axis : int or sequence of int, optional
        Axis(es) over which to apply `count`. Only one of the 'dim'
        and 'axis' arguments can be supplied. If neither are supplied, then
        `count` is calculated over axes.
    keep_attrs : bool, optional
        If True, the attributes (`attrs`) will be copied from the original
        object to the new one.  If False (default), the new object will be
        returned without attributes.
    **kwargs : dict
        Additional keyword arguments passed on to the appropriate array
        function for calculating `count` on this object's data.

    Returns
    -------
    reduced : DataArray
        New DataArray object with `count` applied to its data and the
        indicated dimension(s) removed.
```

### CODE REVIEW

**Comment by sjvrijn** [comment]
Btw, is there a reason why the functional kwarg `keep_attrs` has an explanation listed, but isn't listed in the signature? I was unable to find how to update that in the docs when working on this PR.

**Comment by dcherian** [comment]
Thanks @sjvrijn can you merge the master branch to fix the RTD build? Then we can double check the docs.

**Comment by sjvrijn** [comment]
@dcherian Docs seem to be correct: `skipna` is removed from [`DataArray.count`](https://xray--4258.org.readthedocs.build/en/4258/generated/xarray.DataArray.count.html), [`DataArray.any`](https://xray--4258.org.readthedocs.build/en/4258/generated/xarray.DataArray.any.html), [`DataArray.all`](https://xray--4258.org.readthedocs.build/en/4258/generated/xarray.DataArray.all.html) while still there in e.g. [`DataArray.sum`](https://xray--4258.org.readthedocs.build/en/4258/generated/xarray.DataArray.sum.html)

**Comment by max-sixty** [comment]
Thanks @sjvrijn !

**Pull request merged**
