### PR TITLE
fix: transpose non-linked coordinates in 2d plots

### PR DESCRIPTION
**Pull request by fmaussion**
Should fix https://github.com/pydata/xarray/issues/788

### CODE REVIEW

**Comment by fmaussion** [comment]
(I don't think my PR has something to do with the py2.6 test failure)

**Comment by jhamman** [comment]
you are right.  The failure is on master as well and seems to be coming from a dask change.

**Comment by shoyer** [comment]
This looks great -- thanks!

Could you please add a brief note on the bug fix to the What's New page?

**Comment by fmaussion** [comment]
I added something to the What's New page and squashed the commits. I didn't really know how to describe the problem, I hope it's ok like this. Don't hesitate to correct me if needed!

**Comment by shoyer** [comment]
Looks good to me -- thanks!

**Pull request merged**
