### PR TITLE
BUG: Allow arbitrary objects to be Dataset values

### PR DESCRIPTION
**Pull request by MaximilianR**
Closes https://github.com/pydata/xarray/issues/847

The method here might be a bit sweeping. Let me know your thoughts

### CODE REVIEW

**Comment by MaximilianR** [comment]
@shoyer do you recognize this failure? I don't think it's related to this PR (it's also on my other outstanding PR), but not sure?

**Comment by shoyer** [comment]
Yeah, definitely unrelated. I think this is a bug in my h5netcdf project -- I just issued a new release there (should have tested against xarray first!).

**Comment by MaximilianR** [comment]
OK, in which case - let me know feedback here!

**Comment by MaximilianR** [comment]
@shoyer tests pass! Feedback welcome!

**Comment by shoyer** [comment]
This is remarkably simple. I'm pleasantly surprised that it works!

**Pull request merged**
