### PR TITLE
Add create_test_data to public testing API

### LINKED ISSUE #2686: Is `create_test_data()` public API?
We want to encourage people to use and extend xarray, and we already provide testing functions as public API to help with this.

One function I keep using when writing code which uses xarray is `xarray.tests.test_dataset.create_test_data()`. This is very useful for quickly writing tests for the same reasons that it's useful in xarray's internal tests, but it's not explicitly public API. This means that there's no guarantee it won't change/disappear, which is [not ideal](https://github.com/boutproject/xBOUT/issues/26) if you're trying to write a test suite for separate software. But so many tests in xarray rely on it that presumably it's not going to get changed. 

Is there any reason why it shouldn't be public API? Is there something I should use instead?

### PR DESCRIPTION
**Pull request by TomNicholas**
- [x] Closes #2686 and #1839
 - [x] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

### CODE REVIEW

**Comment by shoyer** [comment]
I am slightly reluctant about this because it would mean effectively freezing the output of this helper function. I guess that would probably be OK, but the design was never quite fully considered!

**Comment by max-sixty** [comment]
> it would mean effectively freezing the output of this helper function

We could add a `param` or `version` arg so we can make changes in the future, if this is a concern?

**Comment by TomNicholas** [comment]
> it would mean effectively freezing the output of this helper function

Or we could have a public `create_example_data`, and an internal `create_test_data`? That way to begin with `create_example_data` is just an alias to the internal `create_test_data`, but if we end up needing to change the internal one (to test for some new type of common indexing edge case for example) then we can just separate them?

**Comment by max-sixty** [comment]
The reason I had liked this was that I'm often creating a dataset manually, either in a repl or as a fixture in a test, and that added an overhead in both time and reduced consistency.
I recently started using the tutorial data, but that requires a network connection (and I kept forgetting the name...)

But I can empathize re compatibility issues; I defer to @shoyer on the balance, or whether `xarray.testing.dummy_dataset('some_name')` would be feasible

**Comment by shoyer** [comment]
Maybe having a simple example available under just `xarray.testing.dummy_dataset()` is a good idea after all. If we do ever want to change it for xarray's own testing purposes, that would be quite easy.

That said... if we're going to emesh this in our API lets at least think a little bit to make sure we cover most of the special cases we care about. I think we cover most of the dtypes we care about, but let's also add at least:
- Some global attributes
- A scalar data variable (it's easy to forget about these)

Anything else?

We might also consider tweaking the names -- `dim1`, `dim2` and `dim3` is not very descriptive. Even `x`, `y` and `z` would be better.

**Comment by max-sixty** [comment]
😁 

The only other features I could imagine adding would be a coord over multiple dimensions, and a multi-indexed dimension (but potentially we leave the latter out until we're completely confident about the conventions)

Agree on the names!

@TomNicholas if you want to split this up at all lmk

**Comment by keewis** [comment]
this has been unintentionally closed while renaming `main`, probably because the feature branch was removed. Feel free to reopen if you want to work on this in the future.

**Pull request closed without merging**
