### PR TITLE
Expose options for axis sharing between subplots

### PR DESCRIPTION
**Pull request by hoonhout**
Typical usage for xarray.DataArray's for us is to store directional wave data (time, location, direction and frequency). In order to plot directional data stored in DataArray's it would be convenient to use a combination of FacetGrid and polar projections.

Currently, this is not possible with the xarray.plot modules as axes are hard-coded set to be shared among subplots, which conflicts with the fact that polar axes are by definition "box"-adjustable. Therefore we need the ability to turn off axes sharing.

The simple modification attached exposes the sharex/y options to the xarray.plot routines.

### CODE REVIEW

**Comment by shoyer** [comment]
This seems pretty safe to me. I think this just needs a "what's new" entry, though tests are also always appreciated!

@fmaussion can you take a look?

**Comment by fmaussion** [comment]
Yes, this looks quite straight forward! Tests would be good but I expect this to be difficult to do in the current testing framework, so no pressure on that.

What would be nice is to have an example of your usage of FacetGrid. You can either post it here or wait until I get to add https://github.com/pydata/xarray/issues/1061 to the docs!

**Comment by hoonhout** [comment]
Here is an example of a random spectral plot that doesn't work without the suggested modification:

```python
import xarray
import numpy as np
from collections import OrderedDict
from datetime import datetime

# define dimensions
dims = OrderedDict([
    ('time',      [datetime(2016,12,1,1,0,0), datetime(2016,12,1,1,20,0)]),
    ('location',  np.arange(3)),
    ('frequency', np.linspace(.1, .5, 20)),
    ('direction', np.linspace(0., 2.*np.pi, 50)),
])

# create random data
E = np.random.rand(*[len(x) for x in dims.itervalues()])

# construct DataArray
darray = xarray.DataArray(E, dims=dims, coords=dims)

# plot data
darray.plot.pcolormesh(col='time', row='location',
                       subplot_kws=dict(projection='polar'),
                       sharex=False, sharey=False)
```

**Comment by fmaussion** [comment]
Great example, thanks!

Actually this would make a good test since failing to set the new kwargs to False would raise an error. Maybe you could add this simple test [here](https://github.com/pydata/xarray/blob/master/xarray/test/test_plot.py#L918)?

**Comment by ocefpaf** [comment]
Would it make sense to set the default to False? I believe false is used in mpl.

**Comment by fmaussion** [comment]
This would likely brake existing code, so @shoyer has to decide upon this. The current defaults are probably inherited from [seaborn](http://seaborn.pydata.org/generated/seaborn.FacetGrid.html)

**Comment by ocefpaf** [comment]
Ignore what I said. looking closer it makes sense to set the default to
True.

On Dec 2, 2016 12:18 PM, "Fabien Maussion" <notifications@github.com> wrote:

This would likely brake existing code, so @shoyer
<https://github.com/shoyer> has to decide upon this. The current defaults
are probably inherited from seaborn
<http://seaborn.pydata.org/generated/seaborn.FacetGrid.html>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pydata/xarray/pull/1148#issuecomment-264463656>, or mute
the thread

**Comment by hoonhout** [comment]
Sure, I'll make my example into a test.

BTW, I would recommend to keep the default True.

Seaborn's default is indeed shared axes. This makes sense as a FacetGrid is intended to visualize single-source data.

MPL's default is indeed not to share axes. This also makes sense as MPL doesn't have any constraints on the data source.

**Comment by fmaussion** [comment]
Thanks @hoonhout ! We're still missing an entry on [whats-new.rst](https://github.com/pydata/xarray/blob/master/doc/whats-new.rst) ;)

**Comment by hoonhout** [comment]
I think this request is now ready to be pulled, right?
Otherwise I keep merging these what's new lines :-)

**Comment by fmaussion** [comment]
Thanks @hoonhout !

**Pull request merged**
