### PR TITLE
Dataset.chunk() and DataArray.chunk() now set encoding attribute

### LINKED ISSUE #8062: Dataset.chunk() does not overwrite encoding["chunks"]
### What happened?

When using the `chunk` function to change the chunk sizes of a Dataset (or DataArray, which uses the Dataset implementation of `chunk`), the chunk sizes of the Dask arrays are changed, but the "chunks" entry of the `encoding` attributes are not changed accordingly. This causes the raising of a NotImplementedError when attempting to write the Dataset to a zarr (and presumably other formats as well).

Looking at the implementation of `chunk`, every variable is rechunked using the `_maybe_chunk` function, which actually has the parameter `overwrite_encoded_chunks` to control just this behavior. However, it is an optional parameter which defaults to False, and the call in `chunk` does not provide a value for this parameter, nor does it offer the caller to influence it (by having an `overwrite_encoded_chunks` parameter itself, for example).

I do not know why this default value was chosen as False, or what could break if it was changed to True, but looking at the documentation, it seems the opposite of the intended effect. From the documentation of `to_zarr`:

> Zarr chunks are determined in the following way:
>    From the chunks attribute in each variable’s encoding (can be set via Dataset.chunk).

Which is exactly what it doesn't. 

### What did you expect to happen?

I would expect the "chunks" entry of the `encoding` attribute to be changed to reflect the new chunking scheme.

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import numpy as np

# Create a test Dataset with dimension x and y, each of size 100, and a chunksize of 50
ds_original = xr.Dataset({"my_var": (["x", "y"], np.random.randn(100, 100))})
# Since 'chunk' does not work, manually set encoding
ds_original .my_var.encoding["chunks"] = (50, 50)
# To best showcase the real-life example, write it to file and read it back again.
# The same could be achieved by just calling .chunk() with chunksizes of 25, but this feels more 'complete'
filepath = "~/chunk_test.zarr"
ds_original.to_zarr(filepath)
ds = xr.open_zarr(filepath)

# Check the chunksizes and "chunks" encoding
print(ds.my_var.chunks)
# >>> ((50, 50), (50, 50))
print(ds.my_var.encoding["chunks"])
# >>> (50, 50)

# Rechunk the Dataset
ds = ds.chunk({"x": 25, "y": 25})
# The chunksizes have changed
print(ds.my_var.chunks)
# >>> ((25, 25, 25, 25), (25, 25, 25, 25))
# But the encoding value remains the same
print(ds.my_var.encoding["chunks"])
# >>> (50, 50)

# Attempting to write this back to zarr raises an error
ds.to_zarr("~/chunk_test_rechunked.zarr")
# NotImplementedError: Specified zarr chunks encoding['chunks']=(50, 50) for variable named 'my_var' would overlap multiple dask chunks ((25, 25, 25, 25), (25, 25, 25, 25)). Writing this array in parallel with dask could lead to corrupted data. Consider either rechunking using `chunk()`, deleting or modifying `encoding['chunks']`, or specify `safe_chunks=False`.
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

_No response_

### Anything else we need to know?

_No response_

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
python-bits: 64
OS: Linux
OS-release: 5.10.16.3-microsoft-standard-WSL2
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.10.7
libnetcdf: 4.8.1

xarray: 2023.7.0
pandas: 1.5.3
numpy: 1.24.2
scipy: 1.10.0
netCDF4: 1.5.8
pydap: None
h5netcdf: 0.12.0
h5py: 3.6.0
Nio: None
zarr: 2.14.1
cftime: 1.5.2
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: 1.3.6
dask: 2022.01.0+dfsg
distributed: 2022.01.0+ds.1
matplotlib: 3.5.1
cartopy: None
seaborn: None
numbagg: None
fsspec: 2023.1.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 59.6.0
pip: 23.2.1
conda: None
pytest: 7.2.2
mypy: 1.1.1
IPython: 7.31.1
sphinx: None

</details>

### PR DESCRIPTION
**Pull request by Metamess**
- [x] Closes #8062 
- [x] Tests added
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

This PR aims to fix the bug identified in Issue #8062 , where calling the `.chunk()` function on a `DataArray` or `Dataset` would change the chunking of the underlying data, but not change the `"chunks"` entry in the `encoding` attribute. This would lead to Datasets that cannot be written to file (zarr) without raising an error. The setting of the `encoding` attribute via the `.chunk()` function is part of the expected behavior based on the docstring of `Dataset.to_zarr`:

> Zarr chunks are determined in the following way:
        - From the ``chunks`` attribute in each variable's ``encoding`` (can be set via `Dataset.chunk`).

### CODE REVIEW

**Comment by Metamess** [comment]
Through the tests in test_backend.py I encountered an error in the zarr library when setting attempting to write a Dataset with a dimension of length 0. While the size of the Dask chunk can be 0, the value in the encoding attribute can not. In the zarr code, it can be found that they default to a chunksize of 1 when the dimension has length 0. 

It can be debated whether `encoding = {"chunks": (0, )}` should be a valid value and Zarr should support this, or if 0 is not a sensible value and xarray should set the value to 1 in these cases. For now I have chosen the latter, and edited the code in `_maybe_await()` to set the value in encoding to 1 if the given chunksize is 0. Please let me know if this would be considered the desired behavior!

**Comment by Metamess** [comment]
There is still one test that fails, and which actually challenges the current state of the proposed fix:
The way the test `test_backends.py::TestZarrDictStore::test_chunk_encoding_with_dask` is written, it is clear that here it is assumed that calling `.chunk()` does _not_ set any encoding. I did not want to overrule this by rewriting this test without further input.

From my current understanding, I see three ways forward:
- `chunk()` should always set encoding, as implied by the docstring of `to_zarr`. The test should be rewritten with the assumption that encoding is set by `chunk()`. This option could be acceptable, unless use cases are identified where setting the encoding when calling `chunks()` is undesirable.
- `chunk()` should not set encoding. The to_zarr docstrings should be updated to no longer suggest this. Ideally, a new function is added to `Dataset` and `DataArray` to set the "chunks" in the encoding. This sounds like the least desirable option to me, as it actively creates situations where changing the chunksizes on a Dataset leaves the change only half done.
- `chunk()` should get another optional keyword argument, equal to or similar to `overwrite_encoded_chunks` of `_maybe_await`, that is passed on to `_maybe_await` and influences whether or not the encoding attribute is changed when calling `chunk()`. I would suggest the default value of this argument to be `True`, since this seems to be the commonly desirable case. This option would keep supporting the assumptions present in the test, and keep support for use cases where changing the encoding attribute is considered undesirable. Would change the signature of the `chunk()` function.

In all cases, I would suggest to add a line to the docstring of the `chunk()` function to explicitly specify what happens to the encoding attribute.

**Comment by TomNicholas** [comment]
@Metamess thank you for opening this PR! We really appreciate your initiative here.

> The way the test test_backends.py::TestZarrDictStore::test_chunk_encoding_with_dask is written, it is clear that here it is assumed that calling .chunk() does not set any encoding.

Is it? My reading (which may well be wrong) is that the test assumes that encoding is set by calling `.chunk()`, but an error should be raised when trying to write this particular dataset to Zarr, because Zarr currently does not support non-uniform chunks. That interpretation does not explain why we get a different error raised than the one the test expects though.

@jhamman we would appreciate a comment on this if you have time

**Comment by max-sixty** [comment]
@pydata/xarray I don't know encoding well, but what should we do next on this?

**Comment by max-sixty** [comment]
Does someone have a clear vision of how we're evolving the `encoding` attribute? I'm regretfully out of the loop here, and I worry we lose the energy of folks such as @Metamess without offering direction...

**Comment by dcherian** [comment]
Yeah unfortunately we are all agreed on deleting `encoding` ASAP. So this should be closed.

Thanks for trying @Metamess I'm sorry that your first PR can't make it through. We hope to see you back soon!

**Pull request closed without merging**
