### PR TITLE
Explicitly list all reductions in api.rst

### PR DESCRIPTION
**Pull request by dcherian**
This PR makes a number of updates to `api.rst`. The main goal is to make it easier to navigate using the right-side "Contents" menu. By moving things from `api-hidden.rst` to `api.rst` many methods are now easier-to-discover.

### list all reduction methods in their own subsection under "Dataset" and "DataArray".

**before**

image

**after**
image

### List reductions for groupby etc

I've also added sections for rolling, coarsen, groupby, resample that again list available reductions. These were previously hidden

image

### Class method names are much more readable.

**Before**
image

**after**
image

### CODE REVIEW

**Comment by Illviljan** [comment]
This looks great!

The only thing I noticed is that when I click on the headers in the content table to the right, the above header is exploded:
image
This behavior doesn't feel intuitive to me. It does happen on the stable version as well so it isn't related to this PR. Tested on windows 10 and Firefox.

**Comment by dcherian** [comment]
Yeah I noticed that too on Firefox and Chrome (ubuntu)

cc @andersy005

**Comment by dcherian** [comment]
@pydata/xarray I'd like to merge this to stable since it is doc-only and a pretty nice improvement

**Comment by keewis** [comment]
I think we should add the commit to both `main` and `stable` by cherry-picking to the other branch. A commit that is only on `stable` can be accidentally dropped on a new release.

**Comment by andersy005** [comment]
> This behavior doesn't feel intuitive to me. It does happen on the stable version as well so it isn't related to this PR. Tested on windows 10 and Firefox.

I'll look into this... It appears to be a CSS issue

**Pull request merged**
