### PR TITLE
Added test for issue #6002 (currently fails)

### PR DESCRIPTION
**Pull request by RubendeBruin**
- [ ] Closes #xxxx
- [X] Tests added

### CODE REVIEW

**Comment by max-sixty** [comment]
Great! If you add an `xfail` we can merge...

**Comment by RubendeBruin** [comment]
Hi @max-sixty , what is a `xfail` ?

Also, the issue turned out to be bottleneck-bug , ref: https://github.com/pydata/bottleneck/issues/393#issuecomment-978017397 (fix available)

**Comment by max-sixty** [comment]
> Hi @max-sixty , what is a `xfail` ?

https://docs.pytest.org/en/6.2.x/skipping.html — it marks the test as "expected failure".

> Also, the issue turned out to be bottleneck-bug , ref: pydata/bottleneck#393 (comment) (fix available)

Great that it's fixed upstream! We can either wait for it to be released and then merge this, or merge this now with the `xfail`

**Comment by RubendeBruin** [comment]
I've added xfail , thanks for the link.

**Comment by max-sixty** [comment]
@RubendeBruin it seems my guidance was bad — the test failures suggest that because this is a segfault `xfail` doesn't work, because the whole program crashes.

So instead, let's leave this open until bottleneck does a release, and then merge this as a passing test — does that work on your end?

**Comment by RubendeBruin** [comment]
"does that work on your end?"

yes it does. Will remove the xfail and then we can merge once https://github.com/pydata/bottleneck/pull/382 is merged.

**Comment by jhamman** [comment]
closing as stale / upstream issue. Feel free to reopen if there is more to do here.

**Pull request closed without merging**
