### PR TITLE
Use sphinx-accessors-autosummary

### LINKED ISSUE #3361: Recommendations for domain-specific accessor documentation
Hi,

I'm currently working on an ocean domain specific accessor for a machine learning technique (https://github.com/gmaze/pyxpcm/tree/nfeatures).  
I implemented an xarray.DataSet accessor (name space ``pyxpcm``) that I'd like to document.

I thus wonder whether the xarray/pangeo community has recommendations about how to do this appropriately ?

Right now, I simply have an API auto-generated page, see:
https://pyxpcm-dev.readthedocs.io/en/latest/api.html#xarray-dataset-accessor-the-pyxpcm-name-space

### LINKED ISSUE #4152: signature in accessor methods
With the merge of #3988 we're now properly documenting the `str`, `dt` and `plot` accessors, but the signatures of the plotting methods are missing a few parameters. For example, `DataArray.plot.contour` is missing the parameter `x` (it's properly documented in the parameters section, though).

Also, we need to remove the `str` and `dt` accessors from `Computing` and try to figure out how to fix the summary of `DataArray.plot` (the plotting method).

### PR DESCRIPTION
**Pull request by keewis**
Since I released a initial version of `sphinx-accessors-autosummary` (to `PyPI`, `conda-forge` requires a bit more work), I think we can start using it in `xarray`, too.

This also extends the docs on accessors to mention that package.

 - [x] Closes #4152, closes #3361
 - [x] Passes `isort . && black . && mypy . && flake8`
 - [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
 - [ ] New functions/methods are listed in `api.rst`

### CODE REVIEW

**Comment by keewis** [comment]
it seems that worked: the signature and the summary of `DataArray.plot` are visible

**Comment by max-sixty** [comment]
Thanks @keewis !

**Comment by keewis** [comment]
let's merge, then?

**Comment by dcherian** [comment]
Thanks @keewis

**Pull request merged**
