### PR TITLE
Avoid use of deprecated get= parameter in tests

### PR DESCRIPTION
**Pull request by mrocklin**
- [x] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API (remove if this change should not be visible to users, e.g., if it is an internal clean-up, or if this is part of a larger project that will be documented later)

### CODE REVIEW

**Comment by max-sixty** [comment]
Thanks @mrocklin 

Anyone have any idea why Travis isn't running? Is it the GH issues from this morning? Looks like the latest run was a couple of days ago: https://travis-ci.org/pydata/xarray/pull_requests

**Comment by mrocklin** [comment]
Yes, github is still having issues.  https://status.github.com/messages

We are working through the backlogs of webhook deliveries and Pages builds.
We continue to monitor as the site recovers.

**Comment by mrocklin** [comment]
I'm not sure that I understand the failure here.  Can someone verify that this is related to these changes?

```
=================================== FAILURES ===================================
_____________________________ TestCfGrib.test_read _____________________________
self = <xarray.tests.test_backends.TestCfGrib object at 0x7fd47fc30b00>
    def test_read(self):
        expected = {'number': 2, 'time': 3, 'air_pressure': 2, 'latitude': 3,
                    'longitude': 4}
        with open_example_dataset('example.grib', engine='cfgrib') as ds:
>           assert ds.dims == expected
E           AssertionError: assert Frozen(Sorted...ngitude': 4})) == {'air_pressure...mber': 2, ...}
E             Full diff:
E             - Frozen(SortedKeysDict({'number': 2, 'time': 3, 'isobaricInhPa': 2, 'latitude': 3, 'longitude': 4}))
E             + {'air_pressure': 2, 'latitude': 3, 'longitude': 4, 'number': 2, 'time': 3}
xarray/tests/test_backends.py:2473: AssertionError
_____________________ TestCfGrib.test_read_filter_by_keys ______________________
self = <xarray.tests.test_backends.TestCfGrib object at 0x7fd4904b12b0>
    def test_read_filter_by_keys(self):
        kwargs = {'filter_by_keys': {'shortName': 't'}}
        expected = {'number': 2, 'time': 3, 'air_pressure': 2, 'latitude': 3,
                    'longitude': 4}
        with open_example_dataset('example.grib', engine='cfgrib',
                                  backend_kwargs=kwargs) as ds:
>           assert ds.dims == expected
E           AssertionError: assert Frozen(Sorted...ngitude': 4})) == {'air_pressure...mber': 2, ...}
E             Full diff:
E             - Frozen(SortedKeysDict({'number': 2, 'time': 3, 'isobaricInhPa': 2, 'latitude': 3, 'longitude': 4}))
E             + {'air_pressure': 2, 'latitude': 3, 'longitude': 4, 'number': 2, 'time': 3}
xarray/tests/test_backends.py:2483: AssertionError
```

**Comment by alexamici** [comment]
@shoyer you are right, I had to make a user-visible backward-incompatible change in cfgrib and Travis is getting the latest version.

I'll make a PR to fix the test.

Note that I don't expect to do any other backward-incompatible change this big and the test is going to be robust ti version change from now on.

**Pull request merged**
