### PR TITLE
Build documentation on TravisCI

### LINKED ISSUE #1898: zarr RTD docs broken
This is what is getting rendered on RTD 
http://xarray.pydata.org/en/latest/io.html#zarr

```
In [26]: ds = xr.Dataset({'foo': (('x', 'y'), np.random.rand(4, 5))},
   ....:                 coords={'x': [10, 20, 30, 40],
   ....:                         'y': pd.date_range('2000-01-01', periods=5),
   ....:                         'z': ('x', list('abcd'))})
   ....: 

In [27]: ds.to_zarr('path/to/directory.zarr')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-8c5f1b00edbc> in <module>()
----> 1 ds.to_zarr('path/to/directory.zarr')

/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/latest/lib/python3.5/site-packages/xarray-0.10.0+dev55.g1d32399-py3.5.egg/xarray/core/dataset.py in to_zarr(self, store, mode, synchronizer, group, encoding)
   1165         from ..backends.api import to_zarr
   1166         return to_zarr(self, store=store, mode=mode, synchronizer=synchronizer,
-> 1167                        group=group, encoding=encoding)
   1168 
   1169     def __unicode__(self):

/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/latest/lib/python3.5/site-packages/xarray-0.10.0+dev55.g1d32399-py3.5.egg/xarray/backends/api.py in to_zarr(dataset, store, mode, synchronizer, group, encoding)
    752     # I think zarr stores should always be sync'd immediately
    753     # TODO: figure out how to properly handle unlimited_dims
--> 754     dataset.dump_to_store(store, sync=True, encoding=encoding)
    755     return store

/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/latest/lib/python3.5/site-packages/xarray-0.10.0+dev55.g1d32399-py3.5.egg/xarray/core/dataset.py in dump_to_store(self, store, encoder, sync, encoding, unlimited_dims)
   1068 
   1069         store.store(variables, attrs, check_encoding,
-> 1070                     unlimited_dims=unlimited_dims)
   1071         if sync:
   1072             store.sync()

/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/latest/lib/python3.5/site-packages/xarray-0.10.0+dev55.g1d32399-py3.5.egg/xarray/backends/zarr.py in store(self, variables, attributes, *args, **kwargs)
    378     def store(self, variables, attributes, *args, **kwargs):
    379         AbstractWritableDataStore.store(self, variables, attributes,
--> 380                                         *args, **kwargs)
    381 
    382 

/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/latest/lib/python3.5/site-packages/xarray-0.10.0+dev55.g1d32399-py3.5.egg/xarray/backends/common.py in store(self, variables, attributes, check_encoding_set, unlimited_dims)
    275         variables, attributes = self.encode(variables, attributes)
    276 
--> 277         self.set_attributes(attributes)
    278         self.set_dimensions(variables, unlimited_dims=unlimited_dims)
    279         self.set_variables(variables, check_encoding_set,

/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/latest/lib/python3.5/site-packages/xarray-0.10.0+dev55.g1d32399-py3.5.egg/xarray/backends/zarr.py in set_attributes(self, attributes)
    341 
    342     def set_attributes(self, attributes):
--> 343         self.ds.attrs.put(attributes)
    344 
    345     def encode_variable(self, variable):

AttributeError: 'Attributes' object has no attribute 'put'
```

### PR DESCRIPTION
**Pull request by jhamman**
- [x] Closes #1898 (remove if there is no corresponding issue, which should only be the case for minor changes)
 - [x] Tests added (for all bug fixes or enhancements)
 - [ ] Tests passed (for all non-documentation changes)
 - [ ] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API (remove if this change should not be visible to users, e.g., if it is an internal clean-up, or if this is part of a larger project that will be documented later)

### CODE REVIEW

**Comment by jhamman** [comment]
I think we've talked about doing this a number of times in the past. It seems that we've been running into a number of uncaught build failures (e.g. #1898, #1881). This is one way of testing that the documentation build will pass on read the docs. If someone has a better of idea of how to do this, I'm all ears.

**Comment by shoyer** [comment]
This is really good idea, thanks!

**Comment by shoyer** [comment]
The build is failing with an error message about upgrading ruby?!?

**Comment by jhamman** [comment]
Well isn't that nice. CI is a two edged sword! I'll take a look.

**Comment by shoyer** [comment]
It looks like the doc build fails when it hits a warning:
```
Warning, treated as error:
/home/travis/build/pydata/xarray/doc/api.rst:1: WARNING: Inline emphasis start-string without end-string.
```

We should either fix these warnings or stop them from failing the build :)

**Comment by fmaussion** [comment]
> We should either fix these warnings or stop them from failing the build :)

It's really hard to get rid of all of them - I'd rather try option B ;)

**Comment by fmaussion** [comment]
Currently we have 106 warnings at doc build on my system

**Comment by jhamman** [comment]
I had the fail-on-warning option turned on. I agree we should drop that for now. After we merge this, I'll open an issue to track cleaning those up at some point. I don't have time to fix them right now.

**Pull request merged**
