### PR TITLE
One-off isort run

### PR DESCRIPTION
**Pull request by crusaderky**

### CODE REVIEW

**Comment by dcherian** [comment]
Something messed up the docs build

```
WARNING: [autosummary] failed to import 'xarray.core.accessor_dt.TimedeltaAccessor': no module named xarray.core.accessor_dt.TimedeltaAccessor
WARNING: [autosummary] failed to import 'xarray.core.rolling.DataArrayCoarsen.all': no module named xarray.core.rolling.DataArrayCoarsen.all
WARNING: [autosummary] failed to import 'xarray.core.rolling.DataArrayCoarsen.any': no module named xarray.core.rolling.DataArrayCoarsen.any
WARNING: [autosummary] failed to import 'xarray.core.rolling.DataArrayCoarsen.count': no module named xarray.core.rolling.DataArrayCoarsen.count
WARNING: [autosummary] failed to import 'xarray.core.rolling.DatasetCoarsen.all': no module named xarray.core.rolling.DatasetCoarsen.all
WARNING: [autosummary] failed to import 'xarray.core.rolling.DatasetCoarsen.any': no module named xarray.core.rolling.DatasetCoarsen.any
WARNING: [autosummary] failed to import 'xarray.core.rolling.DatasetCoarsen.count': no module named xarray.core.rolling.DatasetCoarsen.count

```

**Comment by max-sixty** [comment]
This may be causing the doc break: https://github.com/pydata/xarray/pull/3705/files#diff-684a0ceb2878d48b19612ca360e277efR23

**Comment by crusaderky** [comment]
fixed

**Comment by dcherian** [comment]
Great. thanks!

**Pull request merged**
