### PR TITLE
Fix type annotations for `get_axis_num` (GH 9822)

### LINKED ISSUE #9822: DataArray.get_axis_num is incorrectly typed
### What happened?

When using mypy to check my code, I'm getting a spurious error. When passing a single string to `get_axis_num`, the return type is determined to be `tuple[int, ...]` instead of `int`.

### What did you expect to happen?

I expected the return type to be `int` when passing a single single.

### Minimal Complete Verifiable Example

```Python
# Note: to be run through mypy
import xarray as xr

def foo(x: xr.DataArray) -> None:
    reveal_type(x.get_axis_num("time"))
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Relevant log output

```Python
# Output from mypy
test.py:4: note: Revealed type is "builtins.tuple[builtins.int, ...]"
Success: no issues found in 1 source file
```

### Anything else we need to know?

From a quick look at the code, I'm guessing this is because `str` is iterable and so is matching the first `@overload`.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]
python-bits: 64
OS: Linux
OS-release: 6.8.0-49-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: ('C', 'UTF-8')
libhdf5: 1.14.2
libnetcdf: None

xarray: 2024.11.0
pandas: 2.1.4
numpy: 1.26.2
scipy: 1.11.4
netCDF4: None
pydap: None
h5netcdf: None
h5py: 3.11.0
zarr: None
cftime: None
nc_time_axis: None
iris: None
bottleneck: None
dask: 2023.12.0
distributed: None
matplotlib: 3.9.1
cartopy: None
seaborn: None
numbagg: None
fsspec: 2023.12.1
cupy: 13.2.0
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 75.1.0
pip: 24.3.1
conda: None
pytest: 8.2.2
mypy: 1.11.1
IPython: 8.18.1
sphinx: 7.2.6

</details>

### PR DESCRIPTION
**Pull request by bmerry**
Explicitly annotate that a single `str` argument leads to an `int` return, overriding the match against Iterable.

- [x] Closes #9822
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

I haven't added tests since I didn't spot any existing tests of type annotations, but let me know if I missed them.

### CODE REVIEW

**Comment by bmerry** [comment]
Hmm, seems mypy isn't liking that in CI, although it didn't complain when I used it to verify my MCVE. I'll investigate and re-open when I've figured out why.

**Comment by bmerry** [comment]
Ok, the mypy error is explained in more detail [here](https://mypy.readthedocs.io/en/stable/more_types.html#type-checking-the-variants). The problem is that when passing a variable that's statically known to be `Iterable[str]`, you get back either `str` or `tuple[str, ...]` depending on the run-time type. Thus, to be technically correct, one should annotate the return type in this case to be `str | tuple[str, ...]`. However, that's not very pragmatic, because for most practical uses, the argument type will be known more specifically (e.g. list[str] or tuple[str]), and so you know you're getting back a tuple.

So I've done the pragmatic thing and just suppressed the mypy error. The documentation linked above says

> Note that in cases where you ignore the overlapping overload error, mypy will usually still infer the types you expect at callsites.

**Review by headtr1ck — COMMENTED** [review]
Would it not be enough to reverse the order of the existing overloads?

Or will that mess up tuples (which are hashable)?

**Comment by bmerry** [comment]
> Would it not be enough to reverse the order of the existing overloads?
> 
> Or will that mess up tuples (which are hashable)?

I haven't tested it, but I assume you'd run into that problem.

**Comment by max-sixty** [comment]
Thanks a lot for the contribution @bmerry !

Would it be possible to add a test function which uses these? If the test function is annotated with `def test_foo() -> None`, then mypy will check it. That way we can test that this fixes the issue, and other can try improving it (like the swapping overload order above) and we can be confident it won't regress.

**Comment by bmerry** [comment]
> Thanks a lot for the contribution @bmerry !
> 
> Would it be possible to add a test function which uses these? If the test function is annotated with `def test_foo() -> None`, then mypy will check it. That way we can test that this fixes the issue, and other can try improving it (like the swapping overload order above) and we can be confident it won't regress.

If I have time I'll give it a go, but to be honest I'm not sure I will. The test itself should be fairly easy to write, but setting up a test environment will have a learning curve since I've not used conda before and I don't want to risk it getting into a fight with pyenv over my PYTHON_PATH.

**Comment by max-sixty** [comment]
Yeah that's fair. Being able to make small contributions is important, and I think this is a good enough win that it's worth merging.

If you manage to set up an environment feel free to add a test to immortalize your contribution! (and I use pip to avoid the overhead, you might find it easier...)

**Comment by bmerry** [comment]
> and I use pip to avoid the overhead, you might find it easier...

That sounds good. What arguments are you passing to pip to install all the right dependencies?

**Comment by headtr1ck** [comment]
> `pip install .[dev]` works!

Try `pip install -e .[dev]` if you intend to develop xarray and not just use it.

**Pull request merged**
