### PR TITLE
Bump minimum versions for 0.16 release

### PR DESCRIPTION
**Pull request by dcherian**

### CODE REVIEW

**Comment by dcherian** [comment]
Here's the output from our min_deps script for a double check
```
Package       Required             Policy               Status
------------- -------------------- -------------------- ------
python        3.6     (2016-12-23) 3.7     (2018-06-27) <
boto3         1.9     (2018-09-10) 1.11    (2020-01-10) <
bottleneck    1.2     (2017-09-18) 1.2     (2017-09-18) =
cartopy       0.17    (2018-11-17) 0.18    (2020-05-04) <
cdms2         3.1     (2018-11-02) 3.1     (2018-11-02) =
cfgrib        0.9     (2019-02-25) 0.9     (2019-02-25) =
cftime        1.0     (2018-04-27) 1.1     (2020-03-15) <
dask          2.5     (2019-09-27) 2.10    (2020-01-28) <
distributed   2.5     (2019-09-27) 2.10    (2020-01-28) <
h5netcdf      0.7     (2019-02-27) 0.8     (2020-02-05) <
h5py          2.9     (2018-12-20) 2.9     (2018-12-20) =
hdf5          1.10    (2017-09-18) 1.10    (2017-09-18) =
iris          2.2     (2018-10-12) 2.4     (2020-02-21) <
lxml          4.4     (2019-07-27) 4.5     (2020-01-29) <
matplotlib    3.1     (2019-05-18) 3.2     (2020-03-04) <
msgpack-python 0.6     (2018-11-30) 1.0     (2020-02-18) <
nc-time-axis  1.2     (2019-01-25) 1.2     (2019-01-25) =
netcdf4       1.4     (2018-05-08) 1.4     (2018-05-08) =
numba         0.44    (2019-06-18) 0.47    (2020-01-09) <
numpy         1.15    (2018-07-27) 1.15    (2018-07-27) =
pandas        0.25    (2019-07-18) 0.25    (2019-07-18) =
pseudonetcdf  3.0     (2019-07-18) 3.0     (2019-07-18) =
pydap         3.2     (2018-10-16) 3.2     (2018-10-16) =
pynio         1.5     (2017-12-01) 1.5     (2017-12-01) =
rasterio      1.0     (2018-12-21) 1.0     (2018-12-21) =
scipy         1.3     (2019-05-28) 1.4     (2019-12-19) <
seaborn       0.9     (2018-07-17) 0.10    (2020-01-31) <
setuptools    41.2    (2019-08-21) 44.0    (2020-01-02) <
toolz         0.10    (2019-07-12) 0.10    (2019-07-12) =
zarr          2.3     (2019-03-25) 2.4     (2020-01-11) <
```

**Comment by shoyer** [comment]
cc @crusaderky 

Something seems to be going wrong with the dates in our version checking script.

Our policy is to not to require any release of SciPy within the past 12 months, but SciPy 1.4.0 was released on Dec 16, 2019 (only 7 months ago): https://github.com/scipy/scipy/tree/v1.4.0

**Comment by shoyer** [comment]
I've attempted a fix in https://github.com/pydata/xarray/pull/4178. This requires rolling back to older versions of NumPy and pandas -- we'll see if that works!

**Comment by shoyer** [comment]
Actually, I'm just bad at reading. Our policy is "the minor version (X.Y) initially published no more than N months ago", which is correctly implemented by the code.

I think we might want to _change_ the policy, but that's a different matter....

**Comment by crusaderky** [comment]
> Actually, I'm just bad at reading. Our policy is "the minor version (X.Y) initially published no more than N months ago", which is correctly implemented by the code.
> 
> I think we might want to _change_ the policy, but that's a different matter....

Yes, the policy works well in NEP-29 for numpy and python, but can be problematic for seldom-updated packages

**Comment by dcherian** [comment]
I removed the scipy bump. Now it's just dask, distributed and numba.

**Comment by shoyer** [comment]
Looks good to me!

**Comment by dcherian** [comment]
Thanks!

**Pull request merged**
