### PR TITLE
DOC: add initial draft of a development roadmap for xarray

### PR DESCRIPTION
**Pull request by shoyer**
See here for the rendered version:
https://github.com/shoyer/xarray/blob/4dd4463d5f79c07eb3a01f67b7329f2f4a60dd31/doc/roadmap.rst

### CODE REVIEW

**Comment by fmaussion** [comment]
Any comment/suggestion from the larger xarray community?

**Comment by jhamman** [comment]
I think we merge this to make it more visible. 

@fmaussion - we got a few comments asking if/how the core changes proposed in xarray would make using the library more difficult. Those worries seemed to be easily put to rest. Beyond that, things seemed mostly positive/quite.

**Comment by shoyer** [comment]
Here are the responses on Twitter: https://twitter.com/shoyer/status/1021788358048010240

**Comment by aseyboldt** [comment]
This roadmap sounds great!
We plan on using xarray to store all traces in pymc4.
The biggest item on my wish list for that is better support for plotting. I regularly convert traces to pandas and use the plotting functions there, or I convert it so that I can use seaborn.
Better support for hierarchical indexes sounds useful as well. They can be a bit surprising right now, and they can't be serialised to netCDF.
The documentation is quite important our use case. As it is, we are asking our users to learn Bayesian stats, diagnosing sampler issues and possibly some theano or tensorflow. When we switch to xarray, our users have to learn the basics of that as well. Most won't even have heard about netCDF. One thing in particular that I noticed is that many people seem to get confused about the difference between coordinates and dimensions at some point.

**Comment by shoyer** [comment]
Thanks for the feedback!

@dcherian and @yohai have been making some nice improvements to plotting recently. It seems like each release has a few new features. Fortunately plotting goes in the category of "straightforward to improve without a major refactoring", which is probably why we didn't put it on the roadmap!

**Comment by aseyboldt** [comment]
I noticed and appreciate those plotting additions :-)

**Comment by dcherian** [comment]
@aseyboldt Thanks! Please file issues for any feature requests you might have.

**Pull request merged**
