### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by fmaussion**
This PR fixes a problem we had with ipython on RTD: https://github.com/ipython/ipython/issues/8733 

We this simple workaround we can now use the latest ipython version. Thanks to @takluyver for his help!

### CODE REVIEW

**Comment by takluyver** [comment]
I'm still a bit puzzled why this is necessary. I couldn't reproduce it when building the docs locally.

**Comment by takluyver** [comment]
I just made ipython/ipython#10186 - if you've got time, could you try with that branch and see if it works without the config?

**Comment by fmaussion** [comment]
@takluyver thanks, just tried it: seems to work fine! (logs: https://readthedocs.org/projects/xray/builds/4918881/)

**Comment by fmaussion** [comment]
Merged this with the workaround for now, we can get rid of it when the next ipython version is out

**Comment by shoyer** [comment]
Thanks @fmaussion!

**Pull request merged**
