### PR TITLE
Various fixes for explicit Dataset.indexes

### LINKED ISSUE #2854: Assign values to DataArray after interpolating Dataset produces an error
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import xarray as xr

da = xr.DataArray(
    np.random.random((3, 4)),
    dims=["assets", "year"],
    coords={"year": range(2010, 2018, 2)}
)

# Interpolate directly the DataArray
new_da = da.interp(year=[2011, 2015])
new_da.loc[{"year": 2015}] = 42    # WORKS!
print(new_da)

# Interpolate DataArray as part of a Dataset
dset = xr.Dataset({"my_array": da.copy()}).interp(year=[2011, 2015])
new_da = dset.my_array
new_da.loc[{"year": 2015}] = 42    # DOESN'T WORK!
print(new_da)
```
#### Problem description

Assigning a value to some locations of a DataArray after it has been interpolated raises an IndexError. This does not occur when the DataArray is interpolated independently, only occurs when the DataArray has been interpolated as part of a Dataset.

This problem is not present in xarray<0.12.0

#### Expected Output

The above example should print `new_da` in both cases, with the values corresponding to year 2015 replaced by 42. That works in the first case, but fails in the second raising IndexError. 

Although I am not sure if it is the cause of this error, I have found that in the first case the array indexes are present and contain [2011, 2015], but they are an empty OrderDict in the second case. 

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1 (default, Nov  6 2018, 18:46:03) 
[Clang 10.0.0 (clang-1000.11.45.5)]
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: en_GB.UTF-8
libhdf5: 1.10.2
libnetcdf: 4.4.1.1
xarray: 0.12.0
pandas: 0.23.4
numpy: 1.15.4
scipy: 1.1.0
netCDF4: 1.4.2
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.0.3.4
nc_time_axis: None
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.2.1
dask: None
distributed: None
matplotlib: 3.0.2
cartopy: None
seaborn: 0.9.0
setuptools: 40.5.0
pip: 18.1
conda: None
pytest: 4.0.2
IPython: 7.1.1
sphinx: None

</details>

### LINKED ISSUE #2856: Roundtripping between a dimension coordinate and scalar coordinate on a Dataset
#### Code Sample, a copy-pastable example if possible

In xarray 0.12.0 the following example produces a Dataset with no indexes:
```
In [1]: import xarray as xr

In [2]: da = xr.DataArray([1], [('x', [0])], name='a')

In [3]: da.to_dataset().isel(x=0).expand_dims('x').indexes
Out[3]:
```

#### Expected Output

In xarray 0.11.3 the roundtrip sequence above properly recovers the initial index along the `'x'` dimension:
```
In [1]: import xarray as xr

In [2]: da = xr.DataArray([1], [('x', [0])], name='a')

In [3]: da.to_dataset().isel(x=0).expand_dims('x').indexes
Out[3]: x: Int64Index([0], dtype='int64', name='x')
```

#### Output of ``xr.show_versions()``

<details><p>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 02:16:08)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.1
libnetcdf: 4.6.1

xarray: 0.12.0
pandas: 0.24.2
numpy: 1.13.1
scipy: 0.19.1
netCDF4: 1.4.0
pydap: None
h5netcdf: 0.5.1
h5py: 2.8.0
Nio: None
zarr: None
cftime: 1.0.0
nc_time_axis: None
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.2.0
dask: 0.17.5
distributed: 1.21.8
matplotlib: 2.0.2
cartopy: None
seaborn: None
setuptools: 40.5.0
pip: 9.0.1
conda: None
pytest: 3.10.0
IPython: 6.4.0
sphinx: 1.7.4
```

</p></details>

### PR DESCRIPTION
**Pull request by shoyer**
I've added internal consistency checks to the uses of ``assert_equal`` in our
test suite, so this shouldn't happen again.

 - [x] Closes #2856, closes #2854
 - [x] Tests added
 - [x] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

### CODE REVIEW

**Comment by shoyer** [comment]
@pydata/xarray it would be great if someone could review this. I'd like to submit this and then issue the 0.12.1 bug fix release.

**Comment by max-sixty** [comment]
I had a look through the code. I'm struggling a bit to be a good reviewer given my current understanding of how the goals connect to to the implementation. With that disclaimer, the code looks good. So if anyone knows this better, maybe have a look.
I did look at the index invariant tests with more detail, and they look 👍

**Comment by shoyer** [comment]
> I did look at the index invariant tests with more detail, and they look

Yes, this is the main part I was hoping for someone to take a look at. I would not trust my fixes if I did not believe the tests :).

The rest of it are various smaller changes, mostly correcting my previously mistaken (and untested) implementations.

**Comment by spencerkclark** [comment]
Thanks @shoyer and @max-sixty 👍.

**Pull request merged**
