### PR TITLE
cumulative_integrate() method

### PR DESCRIPTION
**Pull request by johnomotani**
Provides the functionality of `scipy.integrate.cumulative_trapezoid`.

- [x] Tests added
- [x] Passes `pre-commit run --all-files`
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by dcherian** [comment]
There's a `cumtrapz` in https://github.com/fujiisoup/xr-scipy/blob/master/xrscipy/integrate.py. Does that help?

**Comment by johnomotani** [comment]
> There's a cumtrapz in https://github.com/fujiisoup/xr-scipy/blob/master/xrscipy/integrate.py. Does that help?

I did a quick check and it seems like applying `scipy.integrate.cumtrapz` to a dask array returns a numpy array, whereas the `duck_array_ops.cumulative_trapezoid` that I copied from `duck_array_ops.trapz` does return a dask array (so I assume it must not force a compute?). Maybe @fujiisoup has thoughts though?

BTW the test failures are in `test_cftimeindex.py` so I assume they're unrelated to these changes.

**Comment by fujiisoup** [comment]
> There's a cumtrapz in https://github.com/fujiisoup/xr-scipy/blob/master/xrscipy/integrate.py. Does that help?

Now most of xr-scipy functionalities are already implemented in xarray and also I couldn't take time to maintain this package.

I think basic functionalities would be better to be integrated into xarray itself and cumulative_trapezoid would be a good candidate, as `integrate` is already there.

The implementation looks good to me. 
I didn't find any edge cases where `duck_array_ops.cumulative_trapezoid` behaves differently from `scipy.integrate.cumtrapz`.

**Comment by max-sixty** [comment]
If we had a `.expanding` method (we only have `.rolling` at the moment), then I guess this could be `.expanding(dim).integrate()`. Is that right?

(but given we don't yet, no need to delay this)

**Comment by max-sixty** [comment]
Great — shall we merge?

**Comment by shoyer** [comment]
This is definitely welcome functionality! My only question is whether it should be a flag in the existing `integrate` method or a new method altogether, e.g., `cumulative_integrate`?

I would lean towards a new method because the function signature is different (not removing a dimension).

**Comment by johnomotani** [comment]
The vote seems to be for a separate `cumulative_integrate` method - I've made that change.

**Comment by max-sixty** [comment]
Thanks a lot @johnomotani !

**Pull request merged**
