### PR TITLE
Add to_pandas method for Dataset

### LINKED ISSUE #255: Add Dataset.to_pandas() method
This would be the complement of the DataArray constructor, converting an xray.DataArray into a 1D series, 2D DataFrame or 3D panel, whichever is appropriate.

`to_pandas` would also makes sense for Dataset, if it could convert 0d datasets to series, e.g., `pd.Series({k: v.item() for k, v in ds.items()})` (there is currently no direct way to do this), and revert to to_dataframe for higher dimensional input.
- [x] DataArray method
- [ ] Dataset method

### PR DESCRIPTION
**Pull request by gcaria**
- [x] Closes #255
- [x] Tests added
- [x] Passes `pre-commit run --all-files`
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [x] New functions/methods are listed in `api.rst`

### CODE REVIEW

**Comment by max-sixty** [comment]
Seems very reasonable to me; others' thoughts?

**Comment by shoyer** [comment]
The model we have with `DataArray.to_pandas()` is that it converts into a corresponding pandas object _without changing the number of dimensions_. `to_dataframe()`/`to_series()` will flatten multiple dimensions into a MultiIndex, but that isn't the role of `to_pandas()`.

Thus:

- 0D xarray.DataArray -> 0D NumPy scalar
- 1D xarray.DataArray -> 1D pandas.Series
- 2D xarray.DataArray -> 2D pandas.DataFrame
- 3D or higher xarray.DataArray -> error

If we treat a `Dataset` like a `DataArray` with one extra dimension (corresponding to variables), then it would make sense to have:

- 0D xarray.Dataset -> 1D pandas.Series
- 1D xarray.Dataset -> 2D pandas.DataFrame (same as `to_dataframe()`)
- 2D or higher xarray.Dataset -> error

I guess this is basically what you have here, except for raising an error in the final case (the error message should mention `to_dataframe()`.

**Review by shoyer — APPROVED** [review]
Looks great, thank you!

**Comment by mathause** [comment]
Thanks @gcaria!

**Pull request merged**
