### PR TITLE
Add python 3.10 to CI

### PR DESCRIPTION
**Pull request by Illviljan**
Waiting on 
* https://github.com/ContinuumIO/anaconda-issues/issues/12669
* https://github.com/conda/conda/pull/10970
* https://github.com/conda-forge/python-feedstock/pull/511
* https://github.com/conda-forge/numba-feedstock/pull/86
* https://github.com/pydap/pydap/pull/210

- [ ] Closes #xxxx
- [ ] Tests added
- [ ] Passes `pre-commit run --all-files`
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [ ] New functions/methods are listed in `api.rst`

### CODE REVIEW

**Comment by Illviljan** [comment]
```
Looking for: ['aiobotocore', 'boto3', 'bottleneck', 'cartopy', 'cdms2', 'cfgrib', 'cftime', 'dask', 'distributed', 'fsspec!=2021.7.0', 'h5netcdf', 'h5py', 'hdf5', 'hypothesis', 'iris', 'lxml', 'matplotlib-base', 'nc-time-axis', 'netcdf4', 'numba', 'numexpr', 'numpy', 'pandas', 'pint', 'pip', 'pooch', 'pre-commit', 'pseudonetcdf', 'pydap', 'pytest', 'pytest-cov', 'pytest-env', 'pytest-xdist', 'rasterio', 'scipy', 'seaborn', 'setuptools', 'sparse', 'toolz', 'typing_extensions', 'zarr']


Encountered problems while solving:
  - package rasterio-1.1.7-py39h645c05b_1 requires python >=3.9,<3.10.0a0, but none of the providers can be installed
```
rasterio doesn't allow 3.10?

**Comment by Illviljan** [comment]
Codecov seems to take a while:
```
   Codecov report uploader 0.1.15
[2022-01-19T21:20:41.230Z] ['info'] => Project root located at: /Users/runner/work/xarray/xarray
[2022-01-19T21:20:41.236Z] ['info'] -> No token specified or token is empty
[2022-01-19T21:20:41.246Z] ['info'] Searching for coverage files...
[2022-01-19T21:20:41.281Z] ['info'] => Found 1 possible coverage files:
  ./coverage.xml
[2022-01-19T21:20:41.282Z] ['info'] Processing ./coverage.xml...
[2022-01-19T21:20:41.294Z] ['info'] Detected GitHub Actions as the CI provider.
[2022-01-19T21:20:41.296Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=github-action-2.1.0-uploader-0.1.15&token=*******&branch=python310&build=1720207030&build_url=https%3A%2F%2Fgithub.com%2Fpydata%2Fxarray%2Factions%2Fruns%2F1720207030&commit=a4f32ed728765145eedf727c98a9e7aef26049c0&job=CI&pr=5844&service=github-actions&slug=pydata%2Fxarray&name=codecov-umbrella&tag=&flags=unittests&parent=
[2022-01-19T21:20:53.209Z] ['info'] Uploading...
```
How important is it?

**Comment by Illviljan** [comment]
I think this is ready now. Only had to temporarily comment out pydap until it supports 3.10.

**Review by andersy005 — APPROVED** [review]

**Comment by Illviljan** [comment]
Merging, thanks!

**Pull request merged**
