### PR TITLE
Added suppport for geotiff colormap() colorinterp to be loaded into attrs

### PR DESCRIPTION
**Pull request by alando46**
This is tangentially related to the [`to_geotiff()` discussion](https://github.com/pydata/xarray/issues/2042).

We're using [intake-xarray](https://github.com/intake/intake-xarray) to read a year's worth of Sentinel-2 Scene Classification Layers into a DataArray, doing some processing, and then writing the output to a single band GeoTIFF. When writing the output, we'd like to preserve the colormap of the original underlying data. `xarray-intake` uses `xarray` to read the dataset, so thought it might be useful to add support in `open_rasterio()` to read and load `src.colormap(1)` and `src.colorinterp` into the attributes of the DataArray. My thinking is that if in the future the community ends up wanting to add a `to_geotiff()` method, reading the `src` colormap and colorinterp might be useful.

Before adding tests, I thought I'd submit the PR to see what others thought about adding this functionality. If there's support for this, I'm happy to add any needed tests or documentation.

 - [ ] Tests added
 - [ ] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

### CODE REVIEW

**Comment by dcherian** [comment]
I think we'd like to load all possible attrs and make them accessible if it's easy to do so. 

Is there a way to do that without having to explicitly add each one?

**Comment by alando46** [comment]
@dcherian that makes sense to me and shouldn't be difficult to do. I basically just tried to follow the existing design pattern for the other attributes.

**Comment by keewis** [comment]
this is related to #4697: now that we consider deprecating `xr.open_rasterio` in favor of `xr.open_dataset(..., engine="rasterio")` (implemented by `rioxarray`), should this be moved there?

**Comment by snowman2** [comment]
Related: https://github.com/corteva/rioxarray/issues/191

**Comment by dcherian** [comment]
Should be fixed in rioxarray since we've now deprecated open_raserio.

**Pull request closed without merging**
