### PR TITLE
Disallow commits to main via pre-commit-hooks

### PR DESCRIPTION
**Pull request by headtr1ck**
- [x] Towards #8209

### CODE REVIEW

**Comment by max-sixty** [comment]
LGTM. I have a tiny bit of pause that someone just starting out in git is going to get really confused, but that's quite minor...

**Comment by max-sixty** [comment]
(Also to confirm — this won't fail when run on main outside of a commit, in particular on CI?)

**Comment by keewis** [comment]
I guess while this can be confusing, it is also partly a blessing: especially people just starting out will open a pull request from `main` and then run into all sorts of issues. Though in my experience people starting out don't tend to use `pre-commit`, so this might not be an issue.

**Comment by headtr1ck** [comment]
> (Also to confirm — this won't fail when run on main outside of a commit, in particular on CI?)

I think it will fail... The hook has no way of knowing why it was invoked.
Although, we could change it into a pre-push stage?
I just find it better to fail before committing, so you don't have to clean up your local main history later...

**Comment by keewis** [comment]
does `pre-commit.ci` even run on `main`?

**Comment by headtr1ck** [comment]
> does `pre-commit.ci` even run on `main`? Edit: yes, it does. Though as a `push` even instead of a `pr` event.

Now it does not anymore ;)

**Comment by max-sixty** [comment]
> > does `pre-commit.ci` even run on `main`? Edit: yes, it does. Though as a `push` even instead of a `pr` event.
> 
> Now it does not anymore ;)

Presumably this precludes us from using this?

Same if someone run `pre-commit run -a` on an up-to-date `main` locally — it's important that passes...

**Comment by headtr1ck** [comment]
> Presumably this precludes us from using this?

why? Now it only runs locally.

> Same if someone run `pre-commit run -a` on an up-to-date `main` locally — it's important that passes...

Not sure why this has to pass, or why someone would even run that.

But hey, no strong feelings about this!

**Comment by max-sixty** [comment]
I just tried it and it *does* pass — I'm guessing it doesn't trigger unless it's committing.

So all good from my side (+ could even reenable the `push` check if we want)

**Comment by max-sixty** [comment]
Unless there are supporters, I would vote to close :'(

**Pull request closed without merging**
