### PR TITLE
size and aspect arguments for plotting methods even without faceting

### PR DESCRIPTION
**Pull request by shoyer**
I was finding myself writting `plt.figure(figsize=(x, y))` way too
often. This will be a convenient shortcut.

Still needs tests.

### CODE REVIEW

**Comment by shoyer** [comment]
Ugh -- the `aspect` argument in matplotlib uses the opposite convention from Seaborn (https://github.com/mwaskom/seaborn/issues/746). So we'll have to break with at least one of those libraries to make this consistent.

**Comment by jhamman** [comment]
Bummer.   I'll just say I think we need to stay with the `matplotlib` convention. We require `matplotlib` as a dependency for plotting, not `seaborn`.  We are also passing the `aspect` argument to a `matplotlib` function/class.  I don't think it makes sense to say the `aspect` argument is passed to the `matplotlib` figure creator... after we revere itss order.

**Comment by robintw** [comment]
Coming here from #897, it seems that we just need to decide to go with matplotlib's version, and therefore switch round the tuple given as `figsize` at https://github.com/pydata/xarray/pull/637/commits/400b1ef1d142c3c0dec1ff3c9f3cdfffa2229c10#diff-4ee153eb90c5207a5ed2e2b997bf6ce9R212, and then update the docs to go with it.

Does that make sense?

**Comment by shoyer** [comment]
@robintw The challenge is that we want to handle `aspect` consistently even if we're doing a multi-faceted plot. Right now, we use the opposite convention (to matplotlib) for multi-faceted plots. So either:

1. We change the existing behavior for muilt-panel plots (and become inconsistent with Seaborn).
2. We change the existing behavior of `aspect` for single panel plots (and become inconsistent with matplotlib).

I would lean toward (2), currently implemented in this PR given that I think `aspect` is used more often for muilt-panel plots, but I'm OK with either option. If we pick (1), then we'll need to adjust both this PR and the existing behavior for multi-panel plots.

**Comment by fmaussion** [comment]
closed via https://github.com/pydata/xarray/pull/1168

**Pull request closed without merging**
