### PR TITLE
[skip-ci] Add  @Illviljan to  core team

### PR DESCRIPTION
**Pull request by dcherian**

### CODE REVIEW

**Comment by max-sixty** [comment]
Congrats and welcome @Illviljan !

**Comment by Illviljan** [comment]
Thanks! :)

**Review by andersy005 — APPROVED** [review]
This looks great! Welcome 🎉 @Illviljan

**Comment by andersy005** [comment]
Readthedocs build is failing due to timeout. It appears that our doc builds have been failing for the last few hours, and my hunch is that somehow we are exceeding [the 15 minutes build time limit](https://docs.readthedocs.io/en/stable/builds.html) 

Screen Shot 2021-09-24 at 1 35 41 PM

**Pull request merged**
