### PR TITLE
Fix multiindex level serialization after reset_index

### LINKED ISSUE #8628: objects remain unserializable after reset_index
### What happened?

With the 2024.1 release, I am unable to write objects to netCDF after having stacked dimensions with `.stack()` and called `.reset_index()` to get rid of the multi-index

### What did you expect to happen?

_No response_

### Minimal Complete Verifiable Example

```Python
import numpy as np 
import xarray as xr 
da = xr.DataArray(np.zeros([2, 3]), dims=["x", "y"])
da = da.stack(point=("x", "y"))
da = da.reset_index("point")
da.to_netcdf("test.nc")
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Relevant log output

```Python
86 def ensure_not_multiindex(var: Variable, name: T_Name = None) -> None:
     87     if isinstance(var._data, indexing.PandasMultiIndexingAdapter):
---> 88         raise NotImplementedError(
     89             f"variable {name!r} is a MultiIndex, which cannot yet be "
     90             "serialized. Instead, either use reset_index() "
     91             "to convert MultiIndex levels into coordinate variables instead "
     92             "or use https://cf-xarray.readthedocs.io/en/latest/coding.html."
     93         )

NotImplementedError: variable 'x' is a MultiIndex, which cannot yet be serialized. Instead, either use reset_index() to convert MultiIndex levels into coordinate variables instead or use https://cf-xarray.readthedocs.io/en/latest/coding.html.
```

### Anything else we need to know?

Creating the stacked object from scratch and saving it to netCDF works fine. The difference is that `type(da.x.variable._data)` is `xarray.core.indexing.PandasMultiIndexingAdapter` if it was stacked and reset and `numpy.ndarray` if it's created from scratch

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:43:09) [GCC 12.3.0]
python-bits: 64
OS: Linux
OS-release: 5.15.133.1-microsoft-standard-WSL2
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.14.3
libnetcdf: 4.9.2

xarray: 2024.1.0
pandas: 2.1.4
numpy: 1.26.3
scipy: 1.11.4
netCDF4: 1.6.5
pydap: None
h5netcdf: 1.2.0
h5py: 3.10.0
Nio: None
zarr: 2.16.1
cftime: 1.6.3
nc_time_axis: None
iris: None
bottleneck: 1.3.7
dask: 2024.1.0
distributed: None
matplotlib: 3.8.2
cartopy: 0.22.0
seaborn: 0.13.1
numbagg: None
fsspec: 2023.12.2
cupy: None
pint: 0.23
sparse: None
flox: None
numpy_groupies: None
setuptools: 69.0.3
pip: 23.3.2
conda: None
pytest: 7.4.4
mypy: None
IPython: 8.20.0
</details>

### PR DESCRIPTION
**Pull request by benbovy**
- [x] Closes #8628
- [x] Tests added
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Review by dcherian — APPROVED** [review]
Don't fully understand but happy to defer to you.

**Comment by slevang** [comment]
This does not seem to have fixed https://github.com/xarray-contrib/xeofs/issues/148, which worked prior to 2024.1.0

**Comment by benbovy** [comment]
@slevang could you provide an example (MVCE), please?

**Comment by slevang** [comment]
An MCVE with `xeofs` is:
```python
import xarray as xr
import xeofs

data = xr.tutorial.open_dataset('air_temperature').air
model = xeofs.models.EOF(n_modes=10)
model.fit(data, "time")
model.save("test.zarr")
```
```
File ~/xarray/xarray/conventions.py:92, in ensure_not_multiindex(var, name)
     90     name = var.name
     91 if var.dims == (name,):
---> 92     raise NotImplementedError(
     93         f"variable {name!r} is a MultiIndex, which cannot yet be "
     94         "serialized. Instead, either use reset_index() "
     95         "to convert MultiIndex levels into coordinate variables instead "
     96         "or use https://cf-xarray.readthedocs.io/en/latest/coding.html."
     97     )

NotImplementedError: variable 'feature' is a MultiIndex, which cannot yet be serialized. Instead, either use reset_index() to convert MultiIndex levels into coordinate variables instead or use https://cf-xarray.readthedocs.io/en/latest/coding.html.
```

I'm trying to figure out a pure xarray version though. We should just be doing the same `stack(feature=[...])` and `reset_index("feature")` ops as in #8628 but there must be something else in there.

**Comment by slevang** [comment]
Looks like the key difference is that in the previous issue, `isinstance(var, IndexVariable)` evaluates to `False`, then `True` in my case so `name` gets set and trips the error. Not sure how we get there.

**Comment by benbovy** [comment]
Ok, we are still raising that error (and we shouldn't do so) in the case where a reset multi-index level coordinate has been renamed to its dimension:

```python
import pandas as pd
import xarray as xr

midx = pd.MultiIndex.from_product([["a", "b"]], names=["foo"])
coords = xr.Coordinates.from_pandas_multiindex(midx, "x")

ds = xr.Dataset(coords=coords)
ds_reset = ds.reset_index("x").rename_vars(foo="x")

type(ds_reset.x.variable._data)
# xarray.core.indexing.PandasMultiIndexingAdapter

ds_reset.to_netcdf("test.nc")
# error
```

Instead of adding more checks like in the PR, I think that a proper fix would be to unwrap the multi-index level coordinate variable data from `xarray.core.indexing.PandasMultiIndexingAdapter` (e.g., convert it to numpy arrays) after resetting or dropping the multi-index.

**Comment by slevang** [comment]
@benbovy any more guidance on how to go about fixing this edge case? I can try a PR but am pretty unfamiliar with the new indexers.

**Pull request merged**
