### PR TITLE
Handle empty containers in zarr chunk checks

### LINKED ISSUE #4084: write/read to zarr subtly changes array with non-dim coord
With an array containing a non-dimension coordinate, I do "where+squeeze" selection and can write the array to zarr without problem.  However, if I write out and read back in the array prior to doing the selection, the array no longer writes properly.

The problem may stem from the non-dimension coordinate being read back as a dask array (which I can see by printing the coordinate).

The problem goes away if [this line](https://github.com/pydata/xarray/blob/732b6cd6248ce715da74f3cd7a0e211eaa1d0aa2/xarray/backends/zarr.py#L72) is altered to check for empty tuples in addition to None:
```
if (var_chunks is None or not len(var_chunks)) and (enc_chunks is None or not len(enc_chunks)):
```

However, I'm not sure if the subtle change in the array will cause other issues, so I don't know if the above modification is a band-aid or a real solution.

#### MCVE Code Sample
```python
# Your code here
import xarray as xr
import numpy as np
import dask.array as da

def create():
    image = da.zeros((2,2))
    return xr.DataArray(image, dims=['y', 'x'], 
                        coords={'x': [0, 1], 'y': [0, 1], 'xname': ('x', ['apple', 'banana'])})

def select_and_write(arr, fname):
    arr = arr.where(arr.coords['xname'] == 'apple', drop=True)
    arr = arr.squeeze('x')
    arr.to_dataset(name='foo').to_zarr(fname, mode='w')

    
def ok():
    print('ok')
    arr = create()
    select_and_write(arr, '/tmp/ok.zarr')
    
def error():
    print('error')
    arr = create()
    arr.to_dataset(name='foo').to_zarr('/tmp/error_intermediate.zarr', mode='w')
    arr2 = xr.open_zarr('/tmp/error_intermediate.zarr')['foo']
    select_and_write(arr2, '/tmp/error.zarr')

ok()
error()
```

#### Expected Output
No stacktrace.

#### Problem Description
<details><summary>Stacktrace</summary>

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-0db8ba1ef466> in <module>
     27 
     28 ok()
---> 29 error()

<ipython-input-1-0db8ba1ef466> in error()
     24     arr.to_dataset(name='foo').to_zarr('/tmp/error_intermediate.zarr', mode='w')
     25     arr2 = xr.open_zarr('/tmp/error_intermediate.zarr')['foo']
---> 26     select_and_write(arr2, '/tmp/error.zarr')
     27 
     28 ok()

<ipython-input-1-0db8ba1ef466> in select_and_write(arr, fname)
     11     arr = arr.where(arr.coords['xname'] == 'apple', drop=True)
     12     arr = arr.squeeze('x')
---> 13     arr.to_dataset(name='foo').to_zarr(fname, mode='w')
     14 
     15 

~/.local/share/virtualenvs/starmap2-kOR7I2hi/lib/python3.7/site-packages/xarray/core/dataset.py in to_zarr(self, store, mode, synchronizer, group, encoding, compute, consolidated, append_dim)
   1632             compute=compute,
   1633             consolidated=consolidated,
-> 1634             append_dim=append_dim,
   1635         )
   1636 

~/.local/share/virtualenvs/starmap2-kOR7I2hi/lib/python3.7/site-packages/xarray/backends/api.py in to_zarr(dataset, store, mode, synchronizer, group, encoding, compute, consolidated, append_dim)
   1341     writer = ArrayWriter()
   1342     # TODO: figure out how to properly handle unlimited_dims
-> 1343     dump_to_store(dataset, zstore, writer, encoding=encoding)
   1344     writes = writer.sync(compute=compute)
   1345 

~/.local/share/virtualenvs/starmap2-kOR7I2hi/lib/python3.7/site-packages/xarray/backends/api.py in dump_to_store(dataset, store, writer, encoder, encoding, unlimited_dims)
   1133         variables, attrs = encoder(variables, attrs)
   1134 
-> 1135     store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
   1136 
   1137 

~/.local/share/virtualenvs/starmap2-kOR7I2hi/lib/python3.7/site-packages/xarray/backends/zarr.py in store(self, variables, attributes, check_encoding_set, writer, unlimited_dims)
    385         self.set_dimensions(variables_encoded, unlimited_dims=unlimited_dims)
    386         self.set_variables(
--> 387             variables_encoded, check_encoding_set, writer, unlimited_dims=unlimited_dims
    388         )
    389 

~/.local/share/virtualenvs/starmap2-kOR7I2hi/lib/python3.7/site-packages/xarray/backends/zarr.py in set_variables(self, variables, check_encoding_set, writer, unlimited_dims)
    434             else:
    435                 # new variable
--> 436                 encoding = _extract_zarr_variable_encoding(v, raise_on_invalid=check)
    437                 encoded_attrs = {}
    438                 # the magic for storing the hidden dimension data

~/.local/share/virtualenvs/starmap2-kOR7I2hi/lib/python3.7/site-packages/xarray/backends/zarr.py in _extract_zarr_variable_encoding(variable, raise_on_invalid)
    188 
    189     chunks = _determine_zarr_chunks(
--> 190         encoding.get("chunks"), variable.chunks, variable.ndim
    191     )
    192     encoding["chunks"] = chunks

~/.local/share/virtualenvs/starmap2-kOR7I2hi/lib/python3.7/site-packages/xarray/backends/zarr.py in _determine_zarr_chunks(enc_chunks, var_chunks, ndim)
    108     if len(enc_chunks_tuple) != ndim:
    109         # throw away encoding chunks, start over
--> 110         return _determine_zarr_chunks(None, var_chunks, ndim)
    111 
    112     for x in enc_chunks_tuple:

~/.local/share/virtualenvs/starmap2-kOR7I2hi/lib/python3.7/site-packages/xarray/backends/zarr.py in _determine_zarr_chunks(enc_chunks, var_chunks, ndim)
    104         enc_chunks_tuple = ndim * (enc_chunks,)
    105     else:
--> 106         enc_chunks_tuple = tuple(enc_chunks)
    107 
    108     if len(enc_chunks_tuple) != ndim:

TypeError: 'NoneType' object is not iterable
```

</details>

#### Versions

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]
python-bits: 64
OS: Linux
OS-release: 5.3.0-51-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: None

xarray: 0.15.1
pandas: 1.0.3
numpy: 1.18.4
scipy: 1.4.1
netCDF4: None
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: 2.4.0
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.15.0
distributed: 2.15.2
matplotlib: 3.2.1
cartopy: None
seaborn: 0.10.1
numbagg: None
setuptools: 46.1.3
pip: 20.0.2
conda: None
pytest: 5.4.1
IPython: 7.14.0
sphinx: None

</details>

### PR DESCRIPTION
**Pull request by chrisroat**
- [x] Closes #4084
- [x] Tests added
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by chrisroat** [comment]
In putting this together, I noted that the behavior of `open_zarr` triggers this bug, while `open_dataset` does not.  I'm not sure if my proposed fix is a band-aid, or if something in `open_zarr` is the real culprit.

**Comment by chrisroat** [comment]
I do not see the failures in my client that are seen in the checks, so there must be some mismatch in the environments.

**Comment by chrisroat** [comment]
Is this solution desired, or is there a deeper fix?

**Comment by max-sixty** [comment]
@chrisroat sorry this fell through the cracks; we're working on making out process more robust.

@pydata/xarray any thoughts?

**Comment by jhamman** [comment]
@keewis - did we mean to close this or was this related to the switch to `main` (#5516)?

**Comment by keewis** [comment]
yes, that was indeed unintentional. I didn't intentionally close anything today so every PR that was closed should be reopened (somehow)

**Comment by keewis** [comment]
the originating repository has been deleted, though, so we might have trouble to reopen

**Comment by jhamman** [comment]
@chrisroat - apologies for letting this sit for so long without a review. If you are interested in finishing it up, we may need to open a new PR to account for the closure here. If so, please ping me directly and I'll get on the review asap.

**Comment by chrisroat** [comment]
Sure thing.  I'll revive it.

**Pull request closed without merging**
