### PR TITLE
Speed up _mapping_repr

### PR DESCRIPTION
**Pull request by Illviljan**
Creating a ordered list for filtering purposes using `.items()` turns out being rather slow. Use `.keys()` instead as that doesn't trigger a bunch of dataarray initializations.

- [x] Passes `pre-commit run --all-files`

Test case:

```python
import numpy as np
import xarray as xr

a = np.arange(0, 2000)
data_vars = dict()
for i in a:
    data_vars[f"long_variable_name_{i}"] = xr.DataArray(
        name=f"long_variable_name_{i}",
        data=np.arange(0, 20),
        dims=[f"long_coord_name_{i}_x"],
        coords={f"long_coord_name_{i}_x": np.arange(0, 20) * 2},
    )
ds0 = xr.Dataset(data_vars)
ds0.attrs = {f"attr_{k}": 2 for k in a}
```

Before:
```python
%timeit print(ds0)
14.6 s ± 215 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

After:
```python
%timeit print(ds0)
120 ms ± 2.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

### CODE REVIEW

**Comment by max-sixty** [comment]
Wow, that's quite the speed up! I haven't had time to understand why it's so dramatic, but let's merge unless there are any objections. Feel free to add a whatsnew @Illviljan

**Comment by dcherian** [comment]
> I haven't had time to understand why it's so dramatic

The old way creates all dataarrays (2000 in this case). This version creates `first_rows+last_rows` dataarrays. Very nice idea @Illviljan !

**Comment by dcherian** [comment]
I pushed a benchmark...

this branch:
[ 31.25%] ··· repr.Repr.time_repr 14.8±0.3ms
[ 37.50%] ··· repr.Repr.time_repr_html 164±1ms

main:
[ 31.25%] ··· repr.Repr.time_repr 41.6±0.5ms
[ 37.50%] ··· repr.Repr.time_repr_html 188±1ms

**Comment by Illviljan** [comment]
The benchmark uses (only) 100 arrays so I suppose there isn't as big of difference at that point. Did you get similar values as me with 2000, @dcherian ?

**Comment by dcherian** [comment]
3x is good! I reduced the size so it would run faster, we can't run a 15s benchmark every time we benchmark an older commit...

Can you add a whats-new note please?

**Comment by Illviljan** [comment]
Ok, if you got 15 seconds as well I'm satisfied. I was just worried I had done something else affecting my results.

**Comment by max-sixty** [comment]
Another great one @Illviljan ! Thank you!

**Pull request merged**
