### PR TITLE
Python 3.8 CI

### PR DESCRIPTION
**Pull request by crusaderky**
- Run full-fat suite of tests for Python 3.8
- Move asv, MacOSX tests, readthedocs, binder, and more to Python 3.8
- Test windows against latest numpy version
- Windows tests remain on Python 3.7 because of a couple of Python 3.8 tests that fail exclusively in CI. Will investigate later.

### CODE REVIEW

**Comment by crusaderky** [comment]
I have no clue whatsoever what's going on with docs?!? I didn't change it in any way and it's just... freezing?!?

**Comment by dcherian** [comment]
There are some warnings:
```
[autosummary] generating autosummary for: README.rst, api-hidden.rst, api.rst, combining.rst, computation.rst, contributing.rst, dask.rst, data-structures.rst, examples.rst, examples/ERA5-GRIB-example.ipynb, ..., plotting.rst, quick-overview.rst, related-projects.rst, reshaping.rst, roadmap.rst, terminology.rst, time-series.rst, weather-climate.rst, whats-new.rst, why-xarray.rst
WARNING: [autosummary] failed to import 'xarray.CFTimeIndex.base': no module named xarray.CFTimeIndex.base
WARNING: [autosummary] failed to import 'xarray.CFTimeIndex.data': no module named xarray.CFTimeIndex.data
WARNING: [autosummary] failed to import 'xarray.CFTimeIndex.dtype_str': no module named xarray.CFTimeIndex.dtype_str
WARNING: [autosummary] failed to import 'xarray.CFTimeIndex.flags': no module named xarray.CFTimeIndex.flags
WARNING: [autosummary] failed to import 'xarray.CFTimeIndex.get_duplicates': no module named xarray.CFTimeIndex.get_duplicates
WARNING: [autosummary] failed to import 'xarray.CFTimeIndex.get_values': no module named xarray.CFTimeIndex.get_values
WARNING: [autosummary] failed to import 'xarray.CFTimeIndex.is_lexsorted_for_tuple': no module named xarray.CFTimeIndex.is_lexsorted_for_tuple
WARNING: [autosummary] failed to import 'xarray.CFTimeIndex.itemsize': no module named xarray.CFTimeIndex.itemsize
WARNING: [autosummary] failed to import 'xarray.CFTimeIndex.strides': no module named xarray.CFTimeIndex.strides
WARNING: [autosummary] failed to import 'xarray.CFTimeIndex.summary': no module named xarray.CFTimeIndex.summary

```

and an error?
```
Sphinx parallel build error:
RuntimeError: Non Expected warning in `/home/vsts/work/1/s/doc/dask.rst` line 136


>>>-------------------------------------------------------------------------
Warning in /home/vsts/work/1/s/doc/dask.rst at block ending on line 136
Specify :okwarning: as an option in the ipython:: block to suppress this message
----------------------------------------------------------------------------
/usr/share/miniconda/envs/xarray-tests/lib/python3.7/site-packages/dask/dataframe/_compat.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm  # noqa: F401
<<<-------------------------------------------------------------------------
```

**Comment by keewis** [comment]
Even if those were problems, the build should fail, not freeze. I think that's #3697, which freezes the build when trying to run `ds.to_netcdf("manipulated-example-data.nc")`.

**Comment by keewis** [comment]
the warning seems to be from `dask.dataframe` and I can't reproduce the autosummary warnings, which is probably because `pandas` removed those in `1.0.0`

**Comment by crusaderky** [comment]
Ready for review and merge.
TODO After merging in master:
- check rtd build
- check binder

**Comment by dcherian** [comment]
Thanks @crusaderky .

Merging hoping that this may fix our RTD issues

**Pull request merged**
