### PR TITLE
HTML repr fix for Furo Sphinx theme

### LINKED ISSUE #6500: HTML repr dark/light themes in Sphinx Furo
### What is your issue?

The Xarray HTML repr assumes that light vs dark theming is stored in the `html` element's `theme` attribute (i.e., `<html theme="dark">` or `<html theme="light">`).

However, the [Sphinx Furo theme](https://github.com/pradyunsg/furo) assumes that light vs dark theming is stored in the `body` element's `data-theme` attribute.  As a result, if you use the Sphinx Furo theme for documentation and use Xarray HTML reprs, the Xarray HTML reprs do not display properly.

In truth, it seems that this comes down to the light vs dark theming not being standardized, which presents a problem of how to support multiple (possibly innumerable) different ways of specifying light or dark themes.  That said, the Sphinx Furo theme has growing popularity, and I wonder if it could be supported as a special case (as is vscode dark themes).

To do this, one would need only modify one line of [xarray/static/css/style.css](https://github.com/pydata/xarray/blob/main/xarray/static/css/style.css):

https://github.com/pydata/xarray/blob/0db3440626721f8cdaf2f3e677d165061e870e26/xarray/static/css/style.css#L16-L17

to:

```css
html[theme=dark],
body[data-theme=dark],
body.vscode-dark {
```

If this is something that the Xarray community would support, I'm happy to put together a PR to do this.

### PR DESCRIPTION
**Pull request by kmpaul**
- [x] Closes #6500
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by dcherian** [comment]
Thanks  @kmpaul.  It's your first PR! 🥳

**Comment by kmpaul** [comment]
Isn't that sad that it is my first PR?  😄

**Comment by max-sixty** [comment]
It's always a happy day @kmpaul ! :)

**Comment by kmpaul** [comment]
😄 It's a good community to contribute to.

**Pull request merged**
