### PR TITLE
Update issue template to include a checklist

### PR DESCRIPTION
**Pull request by max-sixty**
This replaces https://github.com/pydata/xarray/pull/5787.

Please check out the previews in the [most recent comment there](https://github.com/pydata/xarray/pull/5787#issuecomment-1110385272)

### CODE REVIEW

**Comment by max-sixty** [comment]
Docs failure is unrelated! 

Any feedback? (Sorry I missed the dev call this morning — unfortunately that time slot has been difficult for the past few months. Hopefully I can move things around and attend more reliably)

**Comment by mathause** [comment]
There are two warnings from `issue_template.ipynb` (but I am not sure if they are responsible for the failure).

```
[...]/doc/examples/issue_template.ipynb:4: WARNING: Each notebook should have at least one section title
checking consistency...
[...]/doc/examples/issue_template.ipynb: WARNING: document isn't included in any toctree
```

**Comment by keewis** [comment]
I think the remaining error is this:
```
.../doc/examples/blank_template.ipynb: WARNING: document isn't included in any toctree
```
not sure how to fix that, though... maybe put it into a hidden toctree somewhere? Otherwise we would need to use `:orphan:`, but I don't know how to do that with notebooks. Does `nbsphinx` have a recommendation for that?

**Comment by max-sixty** [comment]
Merging but can make friendlier, or even revert, on feedback. Hope that's OK

**Comment by hollymandel** [comment]
It seems that the MCVE checklist is being interpreted by GitHub as "5 tasks done" which is very mildly confusing, e.g. [here](https://github.com/pydata/xarray/issues/9404) next to the "open" marker

**Comment by max-sixty** [comment]
> It seems that the MCVE checklist is being interpreted by GitHub as "5 tasks done" which is very mildly confusing, e.g. [here](https://github.com/pydata/xarray/issues/9404) next to the "open" marker

I agree, this is annoying. But I don't think there's much we can do, it's a GH default and I do think there's value in having folks positively affirm they've done those things. Very open to any alternatives....

**Pull request merged**
