### PR TITLE
How xarray handles missing values

### PR DESCRIPTION
**Pull request by harshitha1201**
Added methods for handling missing values in xarray (#1285)

### CODE REVIEW

**Comment by harshitha1201** [comment]
@TomNicholas please review

**Comment by TomNicholas** [comment]
Hi @harshitha1201 - thanks for this!

We do already have a section covering these methods in https://docs.xarray.dev/en/stable/user-guide/computation.html#missing-values. I suggest that we don't need to duplicate all of this information on the FAQ page. 

That said the examples and explanation you have written here are still useful! Perhaps they can either be used to improve the page I just linked, or go into the docstrings of those particular methods.

For the FAQ page instead I think we probably just want to provide a summary in a couple of sentences and a link to the more detailed information on specific methods. The summary should mention that 
- xarray can handle missing values, 
- it uses `np.NaN` to do so, 
- most computation methods will automatically handle missing values appropriately, 
- aggregation methods have a `skipna` argument,
- plotting will just leave them as blank spaces (link to [plotting page](https://docs.xarray.dev/en/stable/user-guide/plotting.html#missing-values)), 
- we have a set of special methods for manipulating missing and filling values ([link to here](https://docs.xarray.dev/en/stable/user-guide/computation.html#missing-values)).

**Comment by harshitha1201** [comment]
@TomNicholas I have added explanation on computation.rst
I have added a summary on faq.rst

**Comment by harshitha1201** [comment]
@headtr1ck Read the docs build is failing. Is it due to issue #7703. Or the fault is on my side.

**Comment by headtr1ck** [comment]
> @headtr1ck Read the docs build is failing. Is it due to issue #7703. Or the fault is on my side.

Yes, that is this issue.

**Comment by harshitha1201** [comment]
> > @headtr1ck Read the docs build is failing. Is it due to issue #7703. Or the fault is on my side.
> 
> Yes, that is this issue.

okay!

**Review by headtr1ck — APPROVED** [review]
That is a good addition and I imagine a quite common question.

I think we can improve this even more by
1) mentioning that you can end up with missing values by aligning data.
2) NaT (not a time) for cftime objects (actually I am not sure if/how xarray can handle that, haha)
3) not sure if it is worth mentioning the `where` method explicitly, which then allows the use of xarrays nice handling of nans.

**Pull request merged**
