### PR TITLE
Display coords' units for slice plots

### PR DESCRIPTION
**Pull request by caenrigen**
Hi, folks! Thank you for the awesome project!

Here is a minor enhancement for the plotting of slices.

Before this PR:

```python
import xarray as xr
import numpy as np

dset = xr.Dataset(
    data_vars=dict(
        var_a=(("a", "b"), np.array([[1,2], [3,4]]))
    ),
    coords=dict(
        a=("a", np.array([5, 6]), {"unit": "s"}),
        b=("b", np.array([7, 8]), {"unit": "s"})
    )
)
_ = dset.var_a.sel(a=5).plot(marker="o")
```

download-5

After this PR (note the title):

download-4

---

I did not add any tests, since this change did not break anything I am guessing it is not something being tested.

- [ ] Tests added
- [x] Passes `pre-commit run --all-files`
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by Illviljan** [comment]
That's rather annoying that the pint units are dropped:
```python
arr = xr.DataArray(
    name="var_a",
    data=np.array([[1, 2], [3, 4]]),
    # TODO make coord a Quantity once unit-aware indexes supported
    coords=dict(
        a=("a", pint.Quantity(np.array([5, 6]), "s")),
        b=("b", np.array([7, 8]), {"unit": "s"}),
    ),
    dims=("a", "b"),
)
C:\Users\J.W\Documents\GitHub\xarray\xarray\core\utils.py:118: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  index = pd.Index(np.asarray(array), **kwargs)
```
I think xarray could've at least moved the `pint unit` string to `arr.a.attrs["units"]` before downcasting it to ndarrays.

**Comment by keewis** [comment]
> but let it `xfail` for now with a nice explanation

yes, let's wait until the index refactor has progressed a bit more. I'd `skip` it, though: we know that the test will fail right now, so there's no point in running the test (and it's also what all the other tests do, so it's better to be consistent).

Do the slice plots work with non-dimension coordinates? If so, we should maybe add a test with `pint` for that, too: units in non-dimension coordinates are not stripped.

**Comment by TomNicholas** [comment]
I suspect that that `UnitStrippedWarning` is the same one that I apparently forgot to fix [in #5561](https://github.com/pydata/xarray/pull/5561#discussion_r664708280).

**Comment by dcherian** [comment]
Thanks @caenrigen

**Pull request merged**
