### PR TITLE
Automatic validation of your citation metadata

### PR DESCRIPTION
**Pull request by abelsiqueira**
Hello!

We noticed that your repository is using the Citation File Format to store citation metadata in `CITATION.cff`. This Pull Request automates validation of that file using the [cffconvert GitHub Action](https://github.com/marketplace/actions/cffconvert). That way, it's a little bit easier to be robust against future changes to the `CITATION.cff` file.

BTW it's perfectly fine if you don't feel like accepting this Pull Request for whatever reason -- we just thought it might be helpful is all.

We found your repository using a partially automated workflow; if you have any questions about that, feel free to create an issue over at https://github.com/cffbots/filtering/issues/

On behalf of the cffbots team,
@abelsiqueira / @fdiblen / @jspaaks

### CODE REVIEW

**Comment by max-sixty** [comment]
Have you considered making a pre-commit hook? That's our approach for consolidating these sorts of checks, to avoid a sprawl of checks, and to ensure they can be run locally.

**Comment by abelsiqueira** [comment]
It is also possible to validate with a pre-commit hook, although I don't have much experience with it. I think something like

```
  - repo: https://github.com/citation-file-format/cff-converter-python
    rev: ebf0b5e44d67f8beaa1cd13a0d0393ea04c6058d
    hooks:
    - id: validate-cff
```

**Comment by jspaaks** [comment]
Hi @max-sixty, thanks for the suggestion. I wasn't familiar with precommit hooks before, but recently @zmoon submitted a PR to add it to `cffconvert` (https://github.com/citation-file-format/cff-converter-python/blob/ebf0b5e44d67f8beaa1cd13a0d0393ea04c6058d/.pre-commit-hooks.yaml). It will be part of the next release.

**Comment by max-sixty** [comment]
Great! We would def take a PR to add that if you're up for modifying this.

Either way, thanks for contributing your tool to the community.

**Comment by abelsiqueira** [comment]
Following our discussion, I have created https://github.com/pydata/xarray/pull/6658.

**Comment by dcherian** [comment]
Thanks!

**Pull request closed without merging**
