### PR TITLE
FIX: handle NaT values in dt-accessor

### LINKED ISSUE #7928: .dt accessor returns int instead of float, resulting in misrepresentation of NaT values
### What happened?

With the latest xarray (this doesn't happen at least in version `2023.2.0`), accessing .dt parts returns a strict `int64` DataArray, resulting in wrongly presented missing values.

```python
In [2]: s = pd.to_datetime(pd.Series(['2021-12-01', pd.NaT]))

In [3]: s
Out[3]: 
0   2021-12-01
1          NaT
dtype: datetime64[ns]

In [4]: s.dt.year
Out[4]: 
0    2021.0
1       NaN
dtype: float64

In [5]: s.to_xarray()
Out[5]: 
<xarray.DataArray (index: 2)>
array(['2021-12-01T00:00:00.000000000',                           'NaT'],
      dtype='datetime64[ns]')
Coordinates:
  * index    (index) int64 0 1

In [6]: s.to_xarray().dt.year
Out[6]: 
<xarray.DataArray 'year' (index: 2)>
array([                2021, -9223372036854775808])
Coordinates:
  * index    (index) int64 0 1

```

Notice how:
1. The series and generated DataArray are both correctly `datetime64[ns]`
2. The series' `.dt.year` accessor returns a float64 to accommodate the missing value (it will use `int32` w/o the missing value).
3. The DataArray's `.dt.year` returns a negative integer instead of `nan`.

Additionally, compare with the same snippet's output with xarray 2023.2.0:
```python3
In [3]: s.to_xarray().dt.year
Out [3]:
<xarray.DataArray 'year' (index: 2)>
array([2021.,   nan])
Coordinates:
  * index    (index) int64 0 1
```

### What did you expect to happen?

The `.dt` accessor should return a float with missing values when needed.

### Minimal Complete Verifiable Example

```Python
import pandas as pd

s = pd.to_datetime(pd.Series(['2021-12-01', pd.NaT]))
s.to_xarray().dt.year
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

_No response_

### Anything else we need to know?

_No response_

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
python-bits: 64
OS: Linux
OS-release: 5.19.0-1025-aws
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: None
libnetcdf: None

xarray: 2023.5.0
pandas: 2.0.2
numpy: 1.23.4
scipy: 1.10.1
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: None
dask: 2023.6.0
distributed: 2023.6.0
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
fsspec: 2023.6.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 59.6.0
pip: 23.1.2
conda: None
pytest: None
mypy: None
IPython: 8.14.0
sphinx: None

</details>

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- [x] Closes #7928
- [ ] Tests added
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by keewis** [comment]
if I understand correctly, `pandas` will return `float` arrays / series if there's `NaT`, so checking the output dtypes might be faster?

**Comment by kmuehlbauer** [comment]
> if I understand correctly, `pandas` will return `float` arrays / series if there's `NaT`, so checking the output dtypes might be faster?

Thanks! Yes, indeed, so we only need to special case `isocalendar`.

**Comment by kmuehlbauer** [comment]
@keewis Do you have a recommendation how to retrieve resulting dtype for the dask-part?

**Comment by keewis** [comment]
right, with `dask` this could be tricky, since we cannot know if the data contains missing values or not... I really would like to have nullable integer dtypes in situations like these.

**Comment by kmuehlbauer** [comment]
> with `dask` this could be tricky, since we cannot know if the data contains missing values or not...

Even testing a small subset does not reveal the dtype in any case, since the NaT might be in any chunk we do not test. So we would have to know a priori to be on the safe side also for further processing in the dask world.

**Comment by kmuehlbauer** [comment]
One idea for the dask-part is to just keep current behaviour. On compute, this RuntimeError is raised:

```python
RuntimeWarning: invalid value encountered in cast
```

The user could then just use `.astype("float64")` before computation. No proper solution, but maybe sufficient? I'll add the needed changes in a day or two.

**Comment by kmuehlbauer** [comment]
The current solution works for most of the `.dt.accessor` out of the box (it just keeps `float64` if provided by pandas). For isocalendar it is more of a workaround until a proper fix is added upstream (proposed https://github.com/pandas-dev/pandas/issues/54657). The workaround checks for presence of <NA> in the pandas output and handles appropriately. This might introduce a performance penalty.

Note: This does not help for the dask part, which is left unchanged. Here we would somehow need a priory knowledge if NaT is involved or not.

Question: Should we add tests in this PR for handling in presence of NaT? This is currently not tested at all.

**Comment by kmuehlbauer** [comment]
@keewis I did not touch the dask part. I'd appreciate if you or others could have a final look for approval. Thanks.

**Comment by kmuehlbauer** [comment]
Will merging after tests are passing.

**Pull request merged**
