### PR TITLE
Skipping variables in datasets that don't have the core dim

### PR DESCRIPTION
**Pull request by max-sixty**
ref https://github.com/pydata/xarray/pull/2650#issuecomment-454164295

This seems an ugly way of accomplishing the goal; any ideas for a better way of doing this? 

And stepping back, do others think a) it's helpful to skip variables in a dataset, and b) `apply_ufunc` should do this?

### CODE REVIEW

**Comment by max-sixty** [comment]
Thanks a lot for the comments @shoyer , that's v clarifying 

Is there a conceptual overlap between the goals of `.reduce` and `apply_ufunc`? I had initially thought that `.reduce` strictly reduced a dimension, though that's not actually the case given `cumsum`

**Comment by shoyer** [comment]
> Is there a conceptual overlap between the goals of `.reduce` and `apply_ufunc`? I had initially thought that `.reduce` strictly reduced a dimension, though that's not actually the case given `cumsum`

Yes, I think so. `reduce()` is a simpler but complementary model to `apply_ufunc`.

Maybe we should rename `reduce()` to something like `apply_axis_func()` or `apply_over_dim`? I would use the name `apply_along_axis` but the numpy function of the same name does something different.

**Comment by shoyer** [comment]
It might also be clearer to split this functionality into two methods rather than the single `reduce()` method, e.g., `reduce()` and `transform()` in the model of pandas's groupby methods.

It's probably worth thinking about these APIs more systematically, see https://github.com/pydata/xarray/issues/1618, https://github.com/pydata/xarray/issues/1251, https://github.com/pydata/xarray/issues/1130

**Comment by max-sixty** [comment]
> It's probably worth thinking about these APIs more systematically, see #1618, #1251, #1130

Nice, thanks for finding those

> It might also be clearer to split this functionality into two methods rather than the single reduce() method, e.g., reduce() and transform() in the model of pandas's groupby methods.

Is the split needed? I had thought that the function either
- returned a reduced array, and the output dims should be reduced
- returned an array with the original dims, and then output dims shouldn't be reduced

**Comment by max-sixty** [comment]
Is there a next step for a function which:
- Is a drop-in replacement for `.reduce`
- Similar to https://github.com/pydata/xarray/issues/1618, though maybe even simpler, i.e. only operates on a single input at first
- Wraps `apply_ufunc`
- Would restore dim order https://github.com/pydata/xarray/issues/1739
- Could be used by @fujiisoup 's recent functions, ref https://github.com/pydata/xarray/pull/2650#issuecomment-454164295 (though some of these may require multiple inputs, even though there's only one output?)

I'd be happy to give this a go if we agree on the broad design

For names, it's a shame the current `apply` isn't called `map`, and this could be `apply`. I'm not a great fan of `apply_raw`, since I'm can't yet see why it's any more 'raw'.

**Pull request closed without merging**
