### PR TITLE
Revert "MNT: prepare h5netcdf backend for (coming) change in dimension handling"

### PR DESCRIPTION
**Pull request by mathause**
Reverts pydata/xarray#6200

### CODE REVIEW

**Comment by TomNicholas** [comment]
I don't really understand which line of this caused the packaging problem, but please revert what you need to to fix xarray main! We can just keep releasing new minor versions until we get it right, don't worry about that.

**Comment by mathause** [comment]
Did the tests run? Close/ reopen.

**Comment by s-weigand** [comment]
This didn't cause the `packaging` issue, the `packaging` issue was caused by #6096 and the good old "Wait this isn't a python builtin, but I have it in each environment!" 
Like ´pkg_resources´ which comes with `setuptools`, took me ages to find what was wrong back then (old `setuptools` version in that venv) 😅

**Comment by s-weigand** [comment]
Looks like [the same error was there two days ago](https://github.com/pydata/xarray/runs/4965336696?check_suite_focus=true) so it isn't `dask 2022.01.1` since it [only got released 16h ago](https://github.com/dask/dask/tags)

**Comment by kmuehlbauer** [comment]
That was an upstream-dev build, so it could still be a dark issue.

**Comment by mathause** [comment]
I am closing this because it was not the issue of the test failure you saw in #6207.

**Comment by s-weigand** [comment]
> That was an upstream-dev build, so it could still be a dask issue.

Ahhh I should have looked more closely.

Btw I installed an older dask version (`conda install -c conda-forge dask-core=2022.1.0`) and tests pass.
So I guess it is an issue with `dask 2022.01.1`.

**Comment by kmuehlbauer** [comment]
At least it helps to narrow down the time when this appeared in dask. AFAICT the first occurrence was in the nightly upstream-dev build #6197.

**Pull request closed without merging**
