### PR TITLE
Update issue template to include a checklist

### PR DESCRIPTION
**Pull request by max-sixty**
This may be overly prescriptive. We've had a number of recent issues which aren't minimal and link to external data, and then these languish on the Issue Tracker unanswered. That's a loss of time for all involved — the reporter of the issue as well as the maintainers.

To the extent we can predict which issues will languish, it would be better to give that guidance up front, and encourage examples which are easier to engage with. So this introduces a checklist that people need to proactively fill out.

### CODE REVIEW

**Comment by TomNicholas** [comment]
I think this is necessary too - only thing I would add is something along the lines of "this will help you get your question answered faster!"

**Comment by mathause** [comment]
Was this superseeded by #6119?

**Comment by max-sixty** [comment]
Not quite; since this given a specific checklist that people need to complete. Sorry I let this linger. I can finish soon-ish.

**Comment by max-sixty** [comment]
I've refreshed this, since I've been spending time in the issue tracker recently and would like to systematize myself out of the "no MVCE" triagooor.

I also added a quasi-empty binder notebook so people can easily test against a current version of dependencies. I've been using this given my M1 has been prickly for some xarray dependencies. Binder is great.

I'd be up for making it more friendly, if possible. But I do think we should be strict on better quality issues. Some claims:
- Most people want to[^1] invest the time to make good issues, and it's mostly a gap of direction
- An unanswered issue (of which we have many, unfortunately) is worse than no issue at all — people feel that there's no resolution to their concerns
- Bad issues take time away from good issues, and lower maintainers willingness to spend time in the issue tracker
- Friendliness is a virtue. It's difficult to be friendly when managing bad issues, it's very easy when dealing with good bug reports

[^1]: or at least are not adverse to :)

This is the current draft:
image

And the checkboxes:

image

**Comment by mathause** [comment]
Your suggestion looks good - did you close this on purpose?

**Comment by max-sixty** [comment]
Sorry, thanks for letting me know, that was a mistake. I'll restore. 

I've had some issues with my github scripts today...

**Pull request closed without merging**
