### PR TITLE
Continue to use nanosecond-precision Timestamps in precision-sensitive areas

### PR DESCRIPTION
**Pull request by spencerkclark**
This addresses the remaining cftime-related test failures in #7707 by introducing a function that always returns a nanosecond-precision Timestamp object.  Despite no corresponding test failures, for safety I grepped and went ahead and replaced the `pd.Timestamp` constructor with this function in a few other areas.  I also updated our documentation to replace any mentions of the "Timestamp-valid range" with "nanosecond-precision range" since Timestamps are now more flexible, and included a note that we have an issue open for relaxing this nanosecond-precision assumption in xarray eventually.

While in principle I think it would be fine if `CFTimeIndex.to_datetimeindex` returned a `DatetimeIndex` with non-nanosecond-precision values, since we don't use `to_datetimeindex` anywhere outside of tests, in its current state it was returning nonsense values:
```
>>> import pandas as pd
>>> import xarray as xr
>>> times = xr.cftime_range("0001", periods=5)
>>> times.to_datetimeindex()
DatetimeIndex(['1754-08-30 22:43:41.128654848',
               '1754-08-31 22:43:41.128654848',
               '1754-09-01 22:43:41.128654848',
               '1754-09-02 22:43:41.128654848',
               '1754-09-03 22:43:41.128654848'],
              dtype='datetime64[ns]', freq=None)
```
This is due to the assumption in `cftime_to_nptime` that the resulting array will have nanosecond-precision values.  We can (and should) address this eventually, but for the sake of quickly supporting pandas version two I decided to be conservative and punt this off to be part of #7493.  `cftime_to_nptime` is used in places other than `to_datetimeindex`, so modifying it has other impacts downstream.

### CODE REVIEW

**Comment by keewis** [comment]
to properly test this, I guess we'd need to merge #7724 first?

**Comment by jsignell** [comment]
> to properly test this, I guess we'd need to merge #7724 first?

Otherwise the env in the upstream test will never solve right?

**Comment by spencerkclark** [comment]
I'm fine waiting until #7724 is merged to let our main CI cover this.  Indeed the upstream tests are flaky.  Locally I just installed pandas 2 via pip to do testing during development.

**Comment by dcherian** [comment]
RTD failures are real:
```
WARNING: [autosummary] failed to import xarray.CFTimeIndex.is_all_dates.
Possible hints:
* ImportError: 
* AttributeError: type object 'CFTimeIndex' has no attribute 'is_all_dates'
* ModuleNotFoundError: No module named 'xarray.CFTimeIndex'
WARNING: [autosummary] failed to import xarray.CFTimeIndex.is_mixed.
Possible hints:
* ImportError: 
* AttributeError: type object 'CFTimeIndex' has no attribute 'is_mixed'
* ModuleNotFoundError: No module named 'xarray.CFTimeIndex'
WARNING: [autosummary] failed to import xarray.CFTimeIndex.is_monotonic.
Possible hints:
* ImportError: 
* AttributeError: type object 'CFTimeIndex' has no attribute 'is_monotonic'
* ModuleNotFoundError: No module named 'xarray.CFTimeIndex'
WARNING: [autosummary] failed to import xarray.CFTimeIndex.is_type_compatible.
Possible hints:
* AttributeError: type object 'CFTimeIndex' has no attribute 'is_type_compatible'
* ImportError: 
* ModuleNotFoundError: No module named 'xarray.CFTimeIndex'
WARNING: [autosummary] failed to import xarray.CFTimeIndex.set_value.
Possible hints:
* ImportError: 
* AttributeError: type object 'CFTimeIndex' has no attribute 'set_value'
* ModuleNotFoundError: No module named 'xarray.CFTimeIndex'
WARNING: [autosummary] failed to import xarray.CFTimeIndex.to_native_types.
Possible hints:
* ImportError: 
* AttributeError: type object 'CFTimeIndex' has no attribute 'to_native_types'
* ModuleNotFoundError: No module named 'xarray.CFTimeIndex'
* ```

**Comment by spencerkclark** [comment]
Thanks all for the help!  Fingers crossed things should be all green now.  Happy to address any more review comments.

**Comment by dcherian** [comment]
There are a bunch of warnings in the tests that could be silenced:
```
D:\a\xarray\xarray\xarray\tests\test_dataset.py:516: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
```

But we can also just merge quickly to get a release out

**Comment by spencerkclark** [comment]
Thanks for noting that @dcherian -- I think I got to all of them now.

**Comment by dcherian** [comment]
Thanks for patiently working through this Spencer. I'll merge now, and then we can release tomorrow.

**Pull request merged**
