### PR TITLE
Typing of Dataset

### LINKED ISSUE #5945: Start using `|` instead of `Union` or `Optional` when typing
**Is your feature request related to a problem? Please describe.**
To make it easier reading the typing it is now possible to use `|` instead of `Union` or `Optional`.

Here's an example how it looks like in pandas:
https://github.com/pandas-dev/pandas/blob/master/pandas/plotting/_core.py#L116-L134

**Describe the solution you'd like**
Replace for example:
* `Union[str, int]` with `str | int`
* `Optional[str]` with `None | str`

This would likely require adding `from __future__ import annotations` at the top of the file.

References
https://www.python.org/dev/peps/pep-0604/

### PR DESCRIPTION
**Pull request by headtr1ck**
- [x] Closes #5945
- [x] Tests added

Feel free to wait with merging after the 2022.05.0.dev0 release :)

- This PR adds typing to all Dataset methods (only the ones in Dataset directly and DataWithCoords).
- On the way it fixes several typing issues and adds small code changes for more consistent typing (hopefully does not break anything).
- All test_dataset tests are now typed.
- As usual there are still some mypy bugs open that prevent all typing changes to be final (especially https://github.com/python/mypy/issues/12846). I choose to remove the TypeVars in these occasions to prevent false positives on the user side.
- Sorry for updating so many files at once, mostly these are the changes of adding `from __future__ import annotations` and automatic fixes from pyupdate.

If anyone has some typing expertise:
I think that the way align is typed is wrong. The current implementation only works for aligning a sequence of objects of the same type, but not mixed DataArrays and Datasets. In some placed I had to add some "#type: ignore"s...
I should probably open an issue for that.

### CODE REVIEW

**Comment by headtr1ck** [comment]
It seems that the reductions doc outcome differs on my machine.
Is it possible to generate it in CI?

**Comment by dcherian** [comment]
@Illviljan had similar `int32` vs `int64` issues. I guess you're on Windows too?

CI seems like a good idea. I'll fix it manually for now.

Also thanks for this PR. Amazing work!

**Comment by headtr1ck** [comment]
> @Illviljan had similar `int32` vs `int64` issues. I guess you're on Windows too?
Yes this was on windows.

**Comment by max-sixty** [comment]
Great work @headtr1ck !!

**Pull request merged**
