### PR TITLE
use numpys SupportsDtype

### LINKED ISSUE #7479: Use NumPy's SupportsDType
### What is your issue?

Now that we've bumped our minimum NumPy version to 1.21, we can address this comment:

https://github.com/pydata/xarray/blob/b21f62ee37eea3650a58e9ffa3a7c9f4ae83006b/xarray/core/types.py#L57-L62

I decided not to tackle this as part of #7461 but we may be able to do something like this: 

```python
from numpy.typing._dtype_like import _DTypeLikeNested, _ShapeLike, _SupportsDType
```

xref: #6834
cc @headtr1ck

### PR DESCRIPTION
**Pull request by headtr1ck**
- [x] Closes #7479

I don't know how I feel about using private numpy classes that might change anytime.
Maybe within a if TYPE_CHECKING block it is not too bad?

### CODE REVIEW

**Comment by headtr1ck** [comment]
@Illviljan I was away for quite some time, do you have an idea what is wrong with mypy-3.9?

**Comment by Illviljan** [comment]
I don't get the error. Distributed has a py.typed file https://github.com/dask/distributed/blob/main/distributed/py.typed 
And if it was py.typed issue we should have seen it in other PRs and I haven't seen one yet that has this error..

@TomNicholas added py.typed to package data, https://github.com/xarray-contrib/datatree/commit/927749a7702761491461f9bdfa8a0c1fbc244d85
But still, if distributed also needs to do this we should see this error in more PRs. 

```
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.2/49.2 kB 3.6 MB/s eta 0:00:00
Collecting types-docutils
  Downloading types_docutils-0.19.1.3-py3-none-any.whl (16 kB)
Installing collected packages: types-PyYAML, types-pytz, types-docutils, types-setuptools
Successfully installed types-PyYAML-6.0.12.5 types-docutils-0.19.1.3 types-pytz-2022.7.1.0 types-setuptools-67.2.0.1
xarray/tests/test_distributed.py:14: error: Skipping analyzing "distributed": module is installed, but missing library stubs or py.typed marker  [import]
xarray/tests/test_distributed.py:21: error: Skipping analyzing "distributed.client": module is installed, but missing library stubs or py.typed marker  [import]
xarray/tests/test_distributed.py:21: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
xarray/tests/test_distributed.py:22: error: Skipping analyzing "distributed.utils_test": module is installed, but missing library stubs or py.typed marker  [import]
Generated Cobertura report: /home/runner/work/xarray/xarray/mypy_report/cobertura.xml
Installing missing stub packages:
/home/runner/micromamba-root/envs/xarray-tests/bin/python -m pip install types-PyYAML types-pytz types-setuptools


Generated Cobertura report: /home/runner/work/xarray/xarray/mypy_report/cobertura.xml
Found 3 errors in 1 file (checked 140 source files)
```

**Comment by headtr1ck** [comment]
I vaguely remember seeing this error before, but no idea how it got fixed.
Maybe this run uses an older version of distributed?

**Comment by Illviljan** [comment]
```
dask-core                 2023.2.0           pyhd8ed1ab_0    conda-forge
distarray                 2.12.2             pyh050c7b8_4    conda-forge
distlib                   0.3.6              pyhd8ed1ab_0    conda-forge
distributed               2021.4.1         py39hf3d152e_1    conda-forge
```
Yeah looks like an old version. py.typed was around september so it makes sense that part.

**Comment by headtr1ck** [comment]
Is it some caching issue, since this PR has been lying around for some time?

**Comment by dcherian** [comment]
Thanks @headtr1ck 

Do you know if there's a plan to make something like this public on the numpy end?

**Comment by headtr1ck** [comment]
> Do you know if there's a plan to make something like this public on the numpy end?

No idea, the static typing of numpy is still changing a lot and has many bugs (same with xarray, haha).

I'm sure they will make it public is we request it.

**Comment by dcherian** [comment]
Ugh I think I clicked merge too early.

Shall we just keep it on our end till it become public? I defer to your judgement here.

**Comment by headtr1ck** [comment]
I have opened https://github.com/numpy/numpy/issues/23308

It should be an easy change on numpys side if they decide to go for it.
Only problem, we again have to special case this based on bumpy version, haha.

**Comment by headtr1ck** [comment]
It seems that numpy is somewhat against this change, so maybe we are better off to restore the previous state to not have a mess with supporting different numpy versions again.
Lets keep that in mind before the next release but wait if something changes on numpys side.

**Comment by headtr1ck** [comment]
I guess we should revert this change and use our own definition as proposed by the numpy defs.
If I find time I'll make a new PR such that we can be independent off numpys version in this regard.

**Pull request merged**
