### PR TITLE
setuptools-scm and one-liner setup.py

### LINKED ISSUE #3369: Define a process to test the readthedocs CI before merging into master
This is an offshoot of #3358.

The readthedocs CI has a bad habit of failing even after the Azure Pipelines job "Docs" has succeeded.

After major changes that impact the documentation, and before merging everything into master, it would be advisable to explicitly verify that RTD builds correctly.

So far I tried to
1. create my own readthedocs project, https://readthedocs.org/projects/crusaderky-xarray/
2. point it to my fork https://github.com/crusaderky/xarray/
3. enable build for the branch I want to merge

This is currently failing because of an issue with versioneer, which incorrectly sets ``xarray.__version__`` to ``0+untagged.111.g6d60700``.
This in turn causes a failure in a minimum version check in ``pandas.DataFrame.to_xarray()`` on pandas>=0.25.

In the master RTD project https://readthedocs.org/projects/xray/, I can instead read ``xarray: 0.13.0+20.gdd2b803a``.

So far the only workaround I could find was to downgrade pandas to 0.24 in ``ci/requirements/doc.yml``.

### PR DESCRIPTION
**Pull request by crusaderky**
- Closes #3369
- Replace versioneer with setuptools-scm
- Replace setup.py with setup.cfg
- Drop pytest-runner as instructed by deprecation notice on the project webpage

### CODE REVIEW

**Comment by crusaderky** [comment]
I need to retest the RTD CI before merging

**Comment by crusaderky** [comment]
I seem to have no way to test RTD >_<

https://readthedocs.org/projects/crusaderky-xarray/builds/10305870/

**Comment by keewis** [comment]
push your branch to the main repository, I'll activate it

**Comment by crusaderky** [comment]
@keewis done

**Comment by keewis** [comment]
hmm... that timed out (see the link above), which also happened before this PR (see #3697). I'll try rebuilding.

**Comment by keewis** [comment]
and now it passed, see https://readthedocs.org/projects/xray/builds/10306203/

**Comment by crusaderky** [comment]
Awesome, everything looks in order.
This is now ready for review and merge.

**Comment by dcherian** [comment]
Thanks @crusaderky & @keewis

**Comment by keewis** [comment]
don't we need to put `setuptools` (of which `pkg_resources` is a part of) into `install_requires`?

**Comment by max-sixty** [comment]
Awesome! Thanks @crusaderky & @keewis . 

FWIW I don't think we need a `MANIFEST.in` now; setuptools_scm uses whatever is tracked by source control. But no harm either

**Comment by crusaderky** [comment]
@keewis interesting question. setuptools is technically not part of the Python standard library, but it is part of pip and is always included with the cpython binaries, `conda create python=3.6`, and pypy. So... I'm not sure?

**Comment by shoyer** [comment]
This is a lovely clean-up, but unfortunately I think it broke GitHub's "Used by" feature, which no longer appears at the top of this repository: https://twitter.com/shoyer/status/1221676802793295872

It's kind of awkward, but maybe we should add a minimal `requirements.txt` file for the benefit of GitHub?

**Pull request merged**
