### PR TITLE
Expand user dir paths (~) in open_mfdataset.

### LINKED ISSUE #4783: User directories (~) not expanded by open_mfdataset().
**What happened**:

Hi. Perhaps a trivially minor issue, but I have noticed that `open_dataset` and `to_netcdf` expand user directories (`~`), while `open_mfdataset` does so on file lists, but not on patterns or single files.

**What you expected to happen**:

I would expect consistent behaviour across all file reading and writing methods.

**Minimal Complete Verifiable Example**:

```python
>>> import xarray as xr
>>> xr.Dataset().to_netcdf('~/dataset.nc')  # works
>>> xr.open_dataset('~/dataset.nc')         # works
>>> xr.open_mfdataset(['~/dataset.nc'])     # works
>>> xr.open_mfdataset('~/dataset.nc')       # error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/xarray/backends/api.py", line 891, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
```

**Anything else we need to know?**:

This is done by private method `_normalize_paths`, which is called in `open_dataset` and `to_netcdf` but not `open_mfdataset`.

https://github.com/pydata/xarray/blob/1525fb0b23b8e92420ab428dc3d918a658e92dd4/xarray/backends/api.py#L170-L177

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0]
python-bits: 64
OS: Linux
OS-release: 5.4.80-2-MANJARO
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_GB.utf8
LOCALE: en_GB.UTF-8
libhdf5: 1.12.0
libnetcdf: 4.7.4

xarray: 0.16.1
pandas: 1.1.5
numpy: 1.19.4
scipy: 1.5.4
netCDF4: 1.5.4
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.30.0
distributed: None
matplotlib: 3.3.3
cartopy: None
seaborn: None
numbagg: None
pint: None
setuptools: 51.0.0
pip: 20.2.2
conda: None
pytest: 6.1.2
IPython: 7.19.0
sphinx: 3.4.0

</details>

### PR DESCRIPTION
**Pull request by juseg**
- [x] Closes #4783 
- [ ] Tests added
- [x] Passes `pre-commit run --all-files`
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

<sub>
<h3>
  Overriding CI behaviors
</h3>
   By default, the upstream dev CI is disabled on pull request and push events. You can override this behavior per commit by adding a `[test-upstream]` tag to the first line of the commit message. For documentation-only commits, you can skip the CI per commit by adding a `[skip-ci]` tag to the first line of the commit message
</sub>

### CODE REVIEW

**Comment by juseg** [comment]
This is a one-line change (e378dbc0553dc84c953550fa678028c6299a330f). Do we need tests?

**Comment by dcherian** [comment]
There's a similar issue with `to_zarr` if you're up for fixing that too...

**Review by alexamici — APPROVED** [review]
@juseg please note that the `open_dataset` code path is going to switch to the new API v2 shortly, where we get rid of `_normalize_path` altogether and pass the `filename_or_obj` directly to the backends, that then will need to expand users shortcuts by themselves.

In spite of this the current PR is actually good, as the `paths` string is not passed along to the backends but it used for the `glob` call.

LGTM.

**Comment by dcherian** [comment]
Thanks @juseg & @alexamici

**Pull request merged**
