### PR TITLE
Add user survey announcement to docs

### PR DESCRIPTION
**Pull request by jhamman**
Updating the doc announcement banner to include a link to the active user survey: https://forms.gle/pDRtaTx6GtNn91959

This is already live on our landing page: https://xarray.dev

See also #9076

### CODE REVIEW

**Comment by TomNicholas** [comment]
:+1: to this PR

But is this the colors it renders with for everyone else? This kind of hurts my eyes :eyes:

Screenshot 2024-06-12 at 12 10 35 PM

**Comment by kmuehlbauer** [comment]
> But is this the colors it renders with for everyone else? This kind of hurts my eyes 👀

It's looking great in dark mode. But, yeah, in light mode it really is no eye candy at all.

**Comment by jhamman** [comment]
I believe this is a bug in the readthedocs dev build. You can check out another PR build (e.g. https://xray--9099.org.readthedocs.build/en/9099/) and see the same formatting issue.

Might we assume that this will not propagate to the production build?

**Comment by TomNicholas** [comment]
> Might we assume that this will not propagate to the production build?

Just push it and find out 🤷 The formatting is a separate issue from this issue of adding the survey banner anyway.

**Comment by keewis** [comment]
the current banner looks just as bad on `latest`, but not on `stable`. I'd guess we have a changed dependency (probably `sphinx-book-theme` or `pydata-sphinx-theme`).

**Comment by jhamman** [comment]
I happened to be standing next to @choldgraf at the CZI meeting when I reviewed @dcherian's fix. Chris thinks this was broken by a change in the pydata theme css.

**Pull request merged**
