### PR TITLE
Remove old auto combine

### PR DESCRIPTION
**Pull request by TomNicholas**
- [x] Finishes deprecation cycle started in #2616 (was supposed to have been done in 0.15)
 - [x] Passes `isort -rc . && black . && mypy . && flake8`
 - [x] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

I've set `combine='by_coords'` as the default argument to `open_mfdataset`. Technically we could go for either, as the deprecation warning just told users to make it explicit from now on, but going for `by_coords` rather than `nested` means that:
- The `concat_dim` argument is not needed by default,
- The default behaviour of the function is the "magic" one - users have to opt-in to the more explicit behaviour.

### CODE REVIEW

**Comment by TomNicholas** [comment]
It would also be good to include any improvement to the relevant docs (e.g. #3830) in the same release.

**Comment by max-sixty** [comment]
I think `FutureWarning` and `DeprecationWarning` are pretty similar — mostly focused on whether the behavior will change or the API is going away. 
`FutureDeprecationWarning` is generally lower visibility IIRC.

So maybe this should have been `DeprecationWarning` but no need to go through another cycle imo.

**Comment by dcherian** [comment]
There was a case I ran in to where the old `auto_combine` was needed and none of the newer options worked.

Let me see if I can dig it up.

**Comment by TomNicholas** [comment]
> To make the docs CI pass

Thanks @keewis .

> Shouldn't we change the FutureWarning to a DeprecationWarning before removing auto_combine? 

I wasn't even aware that there were two types of warnings I could have used for this. I was taking "deprecating" to mean "removed" and "starting the deprecation cycle" to mean "start warning people it will soon be removed". The warning messages said "will no longer accept" and "will require" in "version 0.15" - that's probably authoritative enough isn't it?

> There was a case I ran in to where the old auto_combine was needed and none of the newer options worked.

I think that was always a possible edge case - I would very much like to see it though, if only so that we can put a "what to do if" section in the docs.

**Comment by keewis** [comment]
> The warning messages said "will no longer accept" and "will require" in "version 0.15" - that's probably authoritative enough isn't it?

I'd think so, yes. Rereading what the warnings are intended for, [`FutureWarning`](https://docs.python.org/3/library/exceptions.html#FutureWarning) is indeed the same as [`DeprecationWarning`](https://docs.python.org/3/library/exceptions.html#DeprecationWarning), the only difference is the intended target audience. I seem to have confused `FutureWarning` with `PendingDeprecationWarning`.

Then my only issue is with the `whats-new.rst` entry. I'd explicitly state that `auto_combine` was removed (but maybe that's what "fully deprecated" means?).

**Comment by keewis** [comment]
thanks, @TomNicholas, looks good to me.

I opened #3928 for the `upstream-dev` failures.

**Comment by TomNicholas** [comment]
Just noticed there's a [section](http://xarray.pydata.org/en/stable/api.html#deprecated-pending-deprecation) of the API reference for `Deprecated/Pending Deprecation`, but `auto_combine` was never added to it...

**Pull request merged**
