### PR TITLE
implement a more threadsafe call to colorbar

### LINKED ISSUE #1889: call to colorbar not thread safe
The following call in `xarray/xarray/plot/plot.py` does not seem to be thread safe:
```
            cbar = plt.colorbar(primitive, **cbar_kwargs)
```
It leads to systematic crashes when distributed, with a cryptic error message (`ValueError: Unknown element o`). I have to call colorbars outside the xarray plot call to prevent crashes.

A call of the following type may fix the problem:
```
            cbar = fig.colorbar(primitive, **cbar_kwargs)
```
But `fig` does not seem to be available directly in plot.py. Maybe:
```
            cbar = ax.get_figure().colorbar(primitive, **cbar_kwargs)
```

cheers

### PR DESCRIPTION
**Pull request by apatlpo**
- [ ] Xref #1889 
 - [ ] Tests added
 - [ ] Passes `isort -rc . && black . && mypy . && flake8`
 - [ ] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

If you think this is relevant, I'll go ahead and start working on the items above, even though I'm not sure new tests are needed.

### CODE REVIEW

**Comment by apatlpo** [comment]
Argh, my bad.
This implementation does not solve #1889.

**Comment by shoyer** [comment]
Even though this doesn't fix the threadsafety issue (sorry about that!) I think it's still a marginal improvement not to be calling the global `pyplot` functions.

Tests pass so I'm inclined to merge as is :)

**Comment by apatlpo** [comment]
Ok, let me know if you need me to do anything else.

**Comment by dcherian** [comment]
You can give yourself credit in whats-new.rst if you want

**Comment by apatlpo** [comment]
I would feel bad claiming credit for such a small contribution ... it's not even solving my pb which I should probably better document on the issue tracker.

**Comment by shoyer** [comment]
Thanks @apatlpo !

**Comment by apatlpo** [comment]
you're welcome, I hope one day I'll be to make a more worthy contribution to this great library !

**Pull request merged**
