### PR TITLE
merge stable

### PR DESCRIPTION
**Pull request by dcherian**
We fixed the docs for 0.15.0 by pinning versions for RTD on the stable branch. This brings that change over to master.

### CODE REVIEW

**Comment by dcherian** [comment]
YIkes, I have somehow managed to merge master to stable. Does anyone know how to undo that?

**Comment by dcherian** [comment]
OK I think I fixed it with a hard reset to HEAD~1. Phew

**Comment by max-sixty** [comment]
Ha! I've done worse. Those moments are the most excitement I've had in a week. Well done for reseting back.

**Comment by dcherian** [comment]
Im still sweating... :D

**Pull request merged**
