### PR TITLE
Add typing to the OPTIONS dict

### PR DESCRIPTION
**Pull request by Illviljan**
This adds typing to the dict values. Using variables as keys is apparently not permitted by mypy so that part has been removed.

Attempts to fix issues found in #5662.

### CODE REVIEW

**Comment by max-sixty** [comment]
This looks cool! You're ahead of me on the new python features @Illviljan !

Any thoughts before we merge?

**Comment by Illviljan** [comment]
I'm a little uncertain about the 3.7 solution and what happens once we start using these typings more (for example is `sum(int, Any)` ok?). 

But we can drop 3.7 in december I think so maybe these typing inconsistencies is fine?

**Comment by max-sixty** [comment]
As long as it passes mypy on 3.7, I think that's fine. If we're not sure, it's worth confirming that it does pass, either locally or adding a `pre-commit` task...

**Comment by Illviljan** [comment]
@max-sixty is there a way turn of the typing, but still having T_Options defined? I think having no typing is better than adding typing in the 3.7 case. 
Maybe I should wrap it inside the if check as well?

**Comment by Illviljan** [comment]
I found `TypedDict` in `typing_extensions` as well. So now I think the mypy should behave the same for all python versions. 
It got quite messy because `typing_extensions` isnt a dependency of xarray, see #5495.

**Comment by max-sixty** [comment]
Yeah, we had similar issues in https://github.com/pydata/xarray/pull/5624

But I think it's fine if it's messy for now given there's a clear path to clean it up when we move to 3.8.

**Comment by Illviljan** [comment]
I think this is ready for review now. 

The only thing missing now is a typing for positive-only ints. I haven't figured out how to do that though.

**Comment by max-sixty** [comment]
This looks really good!

I didn't know about `Literal`, TIL. We could use that in more places too, I guess.

**Comment by max-sixty** [comment]
Thanks @Illviljan !

**Comment by Illviljan** [comment]
Yes! Literal and TypeGuard seems like great ways of narrowing down types without using slow isinstance checks everywhere.

Some nice reading:
https://adamj.eu/tech/2021/05/17/python-type-hints-how-to-narrow-types-with-isinstance-assert-literal/
https://adamj.eu/tech/2021/06/09/python-type-hints-how-to-narrow-types-with-typeguard/

**Pull request merged**
