### PR TITLE
Replace raises_regex with pytest.raises

### PR DESCRIPTION
**Pull request by max-sixty**
- [x] Passes `pre-commit run --all-files`
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

Is there a reason we have our own `raises_regex`? This replaces it with the standard pytest check.

This is another regex special, so it misses multi-line statements. I can dust off the multi-line regex manual if this ends up working.

### CODE REVIEW

**Comment by max-sixty** [comment]
This is weird: https://github.com/pydata/xarray/pull/5188/commits/3f1d3d13326e3d871cd15bb4aad133f17de1933a

Apart from that, does anyone know a good reason to keep our own impl?

**Comment by alexamici** [comment]
@max-sixty I like the cleanup even it it is rather big. I for one find it very confusing when tests use non standard helpers.

BTW, I think you can skip the `r`-prefix everywhere making the change even more appealing. It is only useful when using `\` operands in the the match string which is almost never the case in xarray.

**Comment by max-sixty** [comment]
> BTW, I think you can skip the `r`-prefix everywhere making the change even more appealing. It is only useful when using `\` operands in the the match string which is almost never the case in xarray.

Yes but not 100%! I would do another regex special to check whether it contains a `\`, but the weekend fun is over and this may have to wait until next time :)

**Comment by alexamici** [comment]
> I would do another regex special to check whether it contains a `\`

@max-sixty I was thinking to something more brutal: I would drop the `r`-prefix everywhere and fix by hand the failing tests ;)

**Comment by max-sixty** [comment]
I'll merge this version which has most of them. 

Ideally we would do all of them — otherwise people will keep using the `raises_regex` — we had that issue with the `self.assert` functions a few years ago. But we can finish it up another time.

> fix by hand the failing tests (if any) ;)

😬

**Comment by keewis** [comment]
> Apart from that, does anyone know a good reason to keep our own impl?

I think our own implementation precedes the `match` parameter, so there's no reason for keeping it. I'll try to find the reason why the backends tests fail.

> This is weird: 3f1d3d1

that's because `match` is a keyword-only parameter, `*args` seems to be used only when called with a function:
```python
pytest.raises(Exc, func, match="passed on").match("my pattern")
```

**Comment by max-sixty** [comment]
> that still fails, but the error is `ValueError: seek of closed file` for `f.seek(8)`

Yes! This is the error I was getting

**Comment by keewis** [comment]
I'm not sure why, but `open_dataset(f, engine="scipy")` seems to close the file if a `TypeError` is raised: if I put
```python
print(f, f.closed)
try:
    open_dataset(f, engine="scipy")
except TypeError:
    pass
print(f, f.closed)
```
before `f.seek(0)`, the second print reports `f.closed = True` and `f.seek` fails. Is that a bug in the `scipy` engine?

**Comment by keewis** [comment]
of course, that does not explain why `raises_regex` passes

**Pull request merged**
