### PR TITLE
Fix an overflow bug in decode_cf_datetime

### PR DESCRIPTION
**Pull request by fmaussion**
- [x] Closes https://github.com/pydata/xarray/issues/2002
 - [x] Tests added 
 - [x] Tests passed
 - [x] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

Not sure yet if this is the best way to do this.

### CODE REVIEW

**Comment by fmaussion** [comment]
The problem comes from a weird numpy casting behavior. Consider:

```python
In [1]: import numpy as np

In [2]: (np.int32(2) * np.int64(2)).dtype
Out[2]: dtype('int64')

In [3]: (np.array(np.int32(2)) * np.int64(2)).dtype
Out[3]: dtype('int64')

In [4]: (np.array([np.int32(2)]) * np.int64(2)).dtype
Out[4]: dtype('int32')
```

In the offending line:

```python
flat_num_dates *  _NS_PER_TIME_DELTA[delta]
```
``flat_num_dates`` is an array of dtype ``int32`` and ``_NS_PER_TIME_DELTA[delta]`` is a scalar of dtype ``int64``. Is there a way to make sure this line casts to a secure dtype better than my proposed solution to cast everything to a ``float64`` first?

**Comment by fujiisoup** [comment]
Thanks @fmaussion .

> Is there a way to make sure this line casts to a secure dtype better than my proposed solution to cast everything to a float64 first?

How about `np.array([np.int32(2)]) * np.array([np.int64(2)])`?

I am not sure whether numpy explains this casting behavior, but I guess this is intentional.
This is consistent with
```python
In [11]: (np.array([1.0], dtype=np.float32) * 1.0).dtype
Out[11]: dtype('float32')
```
where we expect the array dtype takes precedence.

**Comment by fujiisoup** [comment]
I am curious why this test is failing in appveyor.
The casting rule of numpy should not depend on the operating system.

**Comment by fmaussion** [comment]
> I am curious why this test is failing in appveyor.
> The casting rule of numpy should not depend on the operating system.

I'm curious too, but I don't have a windows machine to test it. The tests are green with the float64 casting though

**Pull request merged**
