### PR TITLE
Implement GroupBy.__getitem__

### PR DESCRIPTION
**Pull request by dcherian**
- [x] Tests added
 - [x] Passes `black . && mypy . && flake8`
 - [x] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

Just like the pandas method.

### CODE REVIEW

**Comment by max-sixty** [comment]
As first glance, could this just be `__getitem__`?

```python

In [9]: xr.DataArray(np.random.rand(2,3),coords=dict(y=list('abb')), dims=list('xy')).groupby('y').groups
Out[9]: {'a': [0], 'b': [1, 2]}

In [10]: xr.DataArray(np.random.rand(2,3),coords=dict(y=list('abb')), dims=list('xy')).groupby('y')['a']
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-84ace5956c1e> in <module>
----> 1 xr.DataArray(np.random.rand(2,3),coords=dict(y=list('abb')), dims=list('xy')).groupby('y')['a']

TypeError: 'DataArrayGroupBy' object is not subscriptable
```

**Comment by dcherian** [comment]
@max-sixty Changed to `__getitem__` I think that's a good idea.

**Review by max-sixty — APPROVED** [review]
Looks great! Thanks!

**Review by mathause — APPROVED** [review]
LGTM. I often do `dict(groups)[1]` but this is more convenient.

**Comment by mathause** [comment]
Any objection if I merge this? (I can move the whatsnew entry).

**Comment by max-sixty** [comment]
Please @mathause !

**Comment by mathause** [comment]
Ok, let's wait for the tests. I'll merge in a day or two.

**Comment by mathause** [comment]
Thanks @dcherian

**Pull request merged**
