### PR TITLE
De-duplicate some unit test paramatrization

### PR DESCRIPTION
**Pull request by dstansby**
This removes a lot of duplication in parametrizing the unit testing, by extracting a common decorator into a new file. I had to move the tests to a new sub-folder to get this to work, I hope that's okay?

### CODE REVIEW

**Review by keewis — COMMENTED** [review]
with #7799 I believe we can keep things within a single test file: create and append the unit info instance to `unit_libs` within a `try-except` block (so import errors cause only these tests to be skipped), and skip the entire file if `unit_libs` is empty.

In principle, though, this idea does sound good to me, as well.

**Comment by dstansby** [comment]
Is keeping things in a single file a deliberate design choice? Personally from what I can see splitting up into separate files makes sense, given the original file is already so long.

**Comment by max-sixty** [comment]
(I'm going through outstanding PRs)

This does look like a nice simplification. Should we try and resolve conflicts, decide on the single file, and merge?

**Comment by dstansby** [comment]
I don't have time to finish this off now, but someone else is more than welcome to run with it 😄

**Comment by dstansby** [comment]
Closing since I don't have time to work on this any more

**Pull request closed without merging**
