### PR TITLE
Replace distutils.version with packaging.version

### LINKED ISSUE #6092: DeprecationWarning regarding use of distutils Version classes
**What happened**:

While working on some tests that catch and check for warnings in my library I found that xarray with new versions of Python (I think this is the trigger) causes a ton of DeprecationWarnings on import:

```python
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/xarray/core/pycompat.py:22: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion(duck_array_module.__version__)
```

**What you expected to happen**:

No warnings.

**Minimal Complete Verifiable Example**:

```python
import warnings
warnings.simplefilter("always")

import xarray as xr
```

Results in:

```
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/xarray/core/pycompat.py:22: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion(duck_array_module.__version__)
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/xarray/core/npcompat.py:82: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(np.__version__) >= "1.20.0":
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/xarray/core/pdcompat.py:45: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(pd.__version__) < "0.25.0":
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
```

**Anything else we need to know?**:

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

```
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages/_distutils_hack/__init__.py:35: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/asyncio/base_events.py:681: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
[GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 5.15.5-76051505-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 0.20.2
pandas: 1.3.5
numpy: 1.20.3
scipy: 1.7.3
netCDF4: 1.5.8
pydap: None
h5netcdf: 0.12.0
h5py: 3.6.0
Nio: None
zarr: 2.10.3
cftime: 1.5.1.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.10
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2021.12.0
distributed: 2021.12.0
matplotlib: 3.5.1
cartopy: 0.20.1
seaborn: None
numbagg: None
fsspec: 2021.11.1
cupy: None
pint: None
sparse: None
setuptools: 60.0.3
pip: 21.3.1
conda: None
pytest: 6.2.5
IPython: 7.30.1
sphinx: 4.3.2
```

</details>

### PR DESCRIPTION
**Pull request by mathause**
- [x] Closes #6092
- [x] Passes `pre-commit run --all-files`
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

One change is that it is no longer possible to compare to a string, i.e. `version.parse(xr.__version__) < "0.20.0"` errors.

As mentioned in #6092 there are 3 options - if there is a preference I am happy to update this PR.

```python
from distutils.version import LooseVersion
from packaging import version

LooseVersion(xr.__version__)
version.parse(xr.__version__)
version.Version(xr.__version__)

# currently:
if LooseVersion(mod.__version__) < LooseVersion(minversion):
    pass

# options:
if version.parse(mod.__version__) < version.parse(minversion):
    pass

if version.Version(mod.__version__) < version.Version(minversion):
    pass

if Version(mod.__version__) < Version(minversion):
    pass
```

### CODE REVIEW

**Comment by max-sixty** [comment]
Thanks @mathause ! 

The current `version.parse` looks good (but the others are fine if you prefer ofc)

**Comment by neutrinoceros** [comment]
Note that `packaging.version.parse` will soon be effectively the same as calling `packaging.version.Version`, see https://github.com/pypa/packaging/pull/407/files
You might want to instantiate `Version` explicitly to avoid confusion in the future.

**Comment by mathause** [comment]
> Note that `packaging.version.parse` will soon be effectively the same as calling `packaging.version.Version`

Actually, I would prefer `Version(xr.__version__) > Version("0.20.1")` over `version.parse(xr.__version__) > version.parse("0.20.1")` (mostly because I think it looks better...). However, it doesn't seem that this PR will be merged soon, though... Do you know if there any good reason for us to use `parse` over `Version`?

---

And I should still figure out if `DuckArrayModule("pint").duck_array_version` is used/ public.

**Comment by neutrinoceros** [comment]
`parse` was designed to be more resilient and produce `LegacyVersion` instances for packages that didn't use sane version strings. This functionality is going away because packaging devs judged that it causes more harm than good. In practice it seems that the Python landscape is now mature for this change, as sane version number schemes appear to be extremely dominant.
So unless you know that you're parsing version numbers from packages that don't work with the plain `Version` class I don't think there's any reason to use `parse` now.

**Comment by mathause** [comment]
:+1: thanks! I'll update the PR.

**Review by dcherian — APPROVED** [review]
LGTM. Thanks @mathause

**Comment by mathause** [comment]
Thanks for the feedback!

**Comment by ax3l** [comment]
Don't you need to add [packaging](https://github.com/pypa/packaging) to your `pyproject.toml` in the
```toml
[build-system]
requires = [
]
```
section?

**Comment by jhamman** [comment]
@ax3l - The `packaging` dependency should be resolved in https://github.com/pydata/xarray/pull/6207.

**Comment by keewis** [comment]
and we don't need `packaging` to *build* the package itself (e.g. the wheel), which is why we don't list it in `pyproject.toml`

**Pull request merged**
