### PR TITLE
Open mfdataset with long time axis

### PR DESCRIPTION
**Pull request by znicholls**
When `open_mfdataset` is used on files which have a long time axis, sometimes one time axis is cast to `pd.Timestamp` whilst the other is cast to `cftime.datetime`. In such a case, xarray thinks the time co-ordinates are different and won't load and combine the files automatically. This PR identifies this issue. I've also put in a hack solution but there must be a better way to handle this edge case.

- [x] Tests added
- [ ] Passes `pre-commit run --all-files`
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by znicholls** [comment]
@mathause what do you think?

**Comment by mathause** [comment]
I like the idea. I would still raise an error, though.Maybe: "Found a mix of pandas and cftime datetime data types. Re-opening the data with the option ``use_cftime=True`` may fix this issue." That would be less magic and should tell the users what's going wrong. In addition we would not need an additional keyword argument. I expect a `merge_by_coords` operation to be typically fairly early in the analysis pipeline.

**Comment by znicholls** [comment]
> use_cftime=True

I knew there must be a more elegant option, thanks!

**Review by TomNicholas — CHANGES_REQUESTED** [review]
Thanks for this @znicholls!

I also think pointing users to the right kwarg to try is a better solution than magically casting for them.

Only other thing is we generally try not to include binary files for tests if we can, in order to keep the download size of the repo as small as possible. Do you think you could recreate similar data for the tests just with calls to xarray+pandas+cftime(+maybe netCDF)? If the problem is in `combine_by_coords` then we should be testing that rather than `opem_mfdataset` surely?

The way git handles binary files might also mean that to avoid these files still being stored in the repo history you may have to open a new PR, because I'm actually not sure if the way we squash PR commits before merging would remove the binary files or not.

**Comment by mathause** [comment]
Maybe something like this:

```python
attrs = dict(units="days since 1850-01-01", calendar="proleptic_gregorian")
ds1 = xr.Dataset(coords=dict(time=("time", [164678], attrs)))
xr.conventions.decode_cf(ds1)
```

(or you can directly create two time arrays as suggested by @TomNicholas )

**Comment by znicholls** [comment]
Thanks @TomNicholas and @mathause. I've opened a new PR (#5776), turns out all the tests are well setup already, I just needed to be told where to look. Cheers!

**Pull request closed without merging**
