### PR TITLE
Fix optimize for chunked DataArray

### LINKED ISSUE #3698: dask.optimize on xarray objects
I am trying to call `dask.optimize` on a xarray object before the graph gets too big. But get weird errors. Simple examples below. All examples work if I remove the `dask.optimize` step.

cc @mrocklin @shoyer 

### This works with dask arrays:
``` python
a = dask.array.ones((10,5), chunks=(1,3))
a = dask.optimize(a)[0]
a.compute()
```

### It works when a dataArray is constructed using a dask array
``` python
da = xr.DataArray(a)
da = dask.optimize(da)[0]
da.compute()
```

### but fails when creating a DataArray with a numpy array and then chunking it 
:man_shrugging: 
``` python
da = xr.DataArray(a.compute()).chunk({"dim_0": 5})
da = dask.optimize(da)[0]
da.compute()
```

fails with error

``` python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-50-1f16efa19800> in <module>
      1 da = xr.DataArray(a.compute()).chunk({"dim_0": 5})
      2 da = dask.optimize(da)[0]
----> 3 da.compute()

~/python/xarray/xarray/core/dataarray.py in compute(self, **kwargs)
    838         """
    839         new = self.copy(deep=False)
--> 840         return new.load(**kwargs)
    841 
    842     def persist(self, **kwargs) -> "DataArray":

~/python/xarray/xarray/core/dataarray.py in load(self, **kwargs)
    812         dask.array.compute
    813         """
--> 814         ds = self._to_temp_dataset().load(**kwargs)
    815         new = self._from_temp_dataset(ds)
    816         self._variable = new._variable

~/python/xarray/xarray/core/dataset.py in load(self, **kwargs)
    659 
    660             # evaluate all the dask arrays simultaneously
--> 661             evaluated_data = da.compute(*lazy_data.values(), **kwargs)
    662 
    663             for k, data in zip(lazy_data, evaluated_data):

~/miniconda3/envs/dcpy_updated/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    434     keys = [x.__dask_keys__() for x in collections]
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 436     results = schedule(dsk, keys, **kwargs)
    437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 

~/miniconda3/envs/dcpy_updated/lib/python3.7/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     79         get_id=_thread_get_id,
     80         pack_exception=pack_exception,
---> 81         **kwargs
     82     )
     83 

~/miniconda3/envs/dcpy_updated/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    484                         _execute_task(task, data)  # Re-execute locally
    485                     else:
--> 486                         raise_exception(exc, tb)
    487                 res, worker_id = loads(res_info)
    488                 state["cache"][key] = res

~/miniconda3/envs/dcpy_updated/lib/python3.7/site-packages/dask/local.py in reraise(exc, tb)
    314     if exc.__traceback__ is not tb:
    315         raise exc.with_traceback(tb)
--> 316     raise exc
    317 
    318 

~/miniconda3/envs/dcpy_updated/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    220     try:
    221         task, data = loads(task_info)
--> 222         result = _execute_task(task, data)
    223         id = get_id()
    224         result = dumps((result, id))

~/miniconda3/envs/dcpy_updated/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

TypeError: string indices must be integers
```

### And a different error when rechunking a dask-backed DataArray
``` python
da = xr.DataArray(a).chunk({"dim_0": 5})
da = dask.optimize(da)[0]
da.compute()
```

``` python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-55-d978bbb9e38d> in <module>
      1 da = xr.DataArray(a).chunk({"dim_0": 5})
      2 da = dask.optimize(da)[0]
----> 3 da.compute()

~/python/xarray/xarray/core/dataarray.py in compute(self, **kwargs)
    838         """
    839         new = self.copy(deep=False)
--> 840         return new.load(**kwargs)
    841 
    842     def persist(self, **kwargs) -> "DataArray":

~/python/xarray/xarray/core/dataarray.py in load(self, **kwargs)
    812         dask.array.compute
    813         """
--> 814         ds = self._to_temp_dataset().load(**kwargs)
    815         new = self._from_temp_dataset(ds)
    816         self._variable = new._variable

~/python/xarray/xarray/core/dataset.py in load(self, **kwargs)
    659 
    660             # evaluate all the dask arrays simultaneously
--> 661             evaluated_data = da.compute(*lazy_data.values(), **kwargs)
    662 
    663             for k, data in zip(lazy_data, evaluated_data):

~/miniconda3/envs/dcpy_updated/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    434     keys = [x.__dask_keys__() for x in collections]
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 436     results = schedule(dsk, keys, **kwargs)
    437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 

~/miniconda3/envs/dcpy_updated/lib/python3.7/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     79         get_id=_thread_get_id,
     80         pack_exception=pack_exception,
---> 81         **kwargs
     82     )
     83 

~/miniconda3/envs/dcpy_updated/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    484                         _execute_task(task, data)  # Re-execute locally
    485                     else:
--> 486                         raise_exception(exc, tb)
    487                 res, worker_id = loads(res_info)
    488                 state["cache"][key] = res

~/miniconda3/envs/dcpy_updated/lib/python3.7/site-packages/dask/local.py in reraise(exc, tb)
    314     if exc.__traceback__ is not tb:
    315         raise exc.with_traceback(tb)
--> 316     raise exc
    317 
    318 

~/miniconda3/envs/dcpy_updated/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    220     try:
    221         task, data = loads(task_info)
--> 222         result = _execute_task(task, data)
    223         id = get_id()
    224         result = dumps((result, id))

~/miniconda3/envs/dcpy_updated/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

~/miniconda3/envs/dcpy_updated/lib/python3.7/site-packages/dask/array/core.py in concatenate3(arrays)
   4305     if not ndim:
   4306         return arrays
-> 4307     chunks = chunks_from_arrays(arrays)
   4308     shape = tuple(map(sum, chunks))
   4309 

~/miniconda3/envs/dcpy_updated/lib/python3.7/site-packages/dask/array/core.py in chunks_from_arrays(arrays)
   4085 
   4086     while isinstance(arrays, (list, tuple)):
-> 4087         result.append(tuple([shape(deepfirst(a))[dim] for a in arrays]))
   4088         arrays = arrays[0]
   4089         dim += 1

~/miniconda3/envs/dcpy_updated/lib/python3.7/site-packages/dask/array/core.py in <listcomp>(.0)
   4085 
   4086     while isinstance(arrays, (list, tuple)):
-> 4087         result.append(tuple([shape(deepfirst(a))[dim] for a in arrays]))
   4088         arrays = arrays[0]
   4089         dim += 1

IndexError: tuple index out of range
```

### PR DESCRIPTION
**Pull request by TomAugspurger**
Previously we generated in invalidate Dask task graph, becuase the lines
removed here dropped keys that were referenced elsewhere in the task
graph. The original implementation had a
comment indicating that this was to cull:
https://github.com/pydata/xarray/blob/502a988ad5b87b9f3aeec3033bf55c71272e1053/xarray/core/variable.py#L384

Just spot-checking things, I think we're OK here though. Something like
`dask.visualize(arr[[0]], optimize_graph=True)` indicates that we're OK.

 - [x] Closes #3698
 - [x] Tests added
 - [x] Passes `isort . && black . && mypy . && flake8`
 - [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
 - [x] New functions/methods are listed in `api.rst`

### CODE REVIEW

**Comment by max-sixty** [comment]
Thanks @TomAugspurger ! 
Merging so we can get this into 0.16.1

**Comment by keewis** [comment]
with the merge we have a test failure:
```
_______________________ test_persist_Dataset[<lambda>1] ________________________

persist = <function <lambda> at 0x7fe8d1646048>

    @pytest.mark.parametrize(
        "persist", [lambda x: x.persist(), lambda x: dask.persist(x)[0]]
    )
    def test_persist_Dataset(persist):
        ds = Dataset({"foo": ("x", range(5)), "bar": ("x", range(5))}).chunk()
        ds = ds + 1
        n = len(ds.foo.data.dask)
    
        ds2 = persist(ds)
    
>       assert len(ds2.foo.data.dask) == 1
E       AssertionError: assert 2 == 1
E        +  where 2 = len(<dask.highlevelgraph.HighLevelGraph object at 0x7fe8c45f4518>)
E        +    where <dask.highlevelgraph.HighLevelGraph object at 0x7fe8c45f4518> = dask.array<add, shape=(5,), dtype=int64, chunksize=(5,), chunktype=numpy.ndarray>.dask
E        +      where dask.array<add, shape=(5,), dtype=int64, chunksize=(5,), chunktype=numpy.ndarray> = <xarray.DataArray 'foo' (x: 5)>\ndask.array<add, shape=(5,), dtype=int64, chunksize=(5,), chunktype=numpy.ndarray>\nDimensions without coordinates: x.data
E        +        where <xarray.DataArray 'foo' (x: 5)>\ndask.array<add, shape=(5,), dtype=int64, chunksize=(5,), chunktype=numpy.ndarray>\nDimensions without coordinates: x = <xarray.Dataset>\nDimensions:  (x: 5)\nDimensions without coordinates: x\nData variables:\n    foo      (x) int64 dask.array<chunksize=(5,), meta=np.ndarray>\n    bar      (x) int64 dask.array<chunksize=(5,), meta=np.ndarray>.foo

/home/vsts/work/1/s/xarray/tests/test_dask.py:943: AssertionError
```
does anyone know why that happens?

**Comment by max-sixty** [comment]
Hmmm. It did pass before the merge _from_ master:

**Comment by TomAugspurger** [comment]
Huh, I'm able to reproduce locally. Looking into it now.

**Comment by TomAugspurger** [comment]
Might be best to proceed with https://github.com/pydata/xarray/pull/4434 for now. I'll need to give this a bit of thought.

**Comment by max-sixty** [comment]
> Might be best to proceed with #4434 for now. I'll need to give this a bit of thought.

OK, as you wish, I'll merge if that passes. 

But your change did pass before the merge. Could it be a conflict (in functionality, not git) with recent changes on master?

**Comment by TomAugspurger** [comment]
I'm not sure, but I don't think so. It's strange that it didn't fail on the
pull request.

**Comment by keewis** [comment]
it did, the first failing commit is https://github.com/pydata/xarray/pull/4432/commits/381aaf8cc37502907506011f8cb9f4149e229d2d. Most of the failures are due to merging before the tests could complete, but at least a few of them completed (e.g. https://dev.azure.com/xarray/xarray/_build/results?buildId=3842&view=logs&jobId=f2e88b57-11cf-55c8-cc48-7751ab3d0d0f&j=78b48a04-306f-5a15-9ac3-dd2fdb28db5e&t=5160aa4e-6217-5012-6424-4f17180b374b).

**Pull request merged**
