### PR TITLE
use conda.api instead of parallel calls to the conda binary

### PR DESCRIPTION
**Pull request by keewis**
Currently, our `min_deps_check.py` script uses the `conda` binary to analyze the package metadata. This is not very efficient because `conda` will download and parse `repodata.json` on each call. To speed up the script, we're currently running 8 of these calls (+ processing the results) in parallel using a `ThreadPoolExecutor`, but that increases the memory consumption (and my old notebook does not have that much memory).

`conda` provides the [`conda.api.SubdirData.query_all`](https://docs.conda.io/projects/conda/en/latest/api/api.html#conda.api.SubdirData.query_all) function which will cache the parsed `repodata.json` files between calls. Using that, my notebook can complete
```sh
python ci/min_deps_check.py ci/requirements/py36-bare-minimum.yml
python ci/min_deps_check.py ci/requirements/py36-min-all-deps.py
```
in about 30 seconds, even though the packages are analyzed sequentially.

The documentation states that that function maybe be changed without warning between minor versions, so we would have to pin `conda` to a `x.y` version to be able to use this.

Edit: the documentation does have that warning, but it also says:
> There are 3 supported public modules. We support:
>
> -   import conda.cli.python_api
> -   import conda.api
> -   import conda.exports
>
>The first 2 should have very long-term stability. The third is guaranteed to be stable throughout the lifetime of a feature release series--i.e. minor version number.

so I guess we don't have to pin?

cc @crusaderky

<sub>By default, the upstream dev CI is disabled on pull request and push events. You can override this behavior per commit by adding a `[test-upstream]` tag to the first line of the commit message.</sub>

### CODE REVIEW

**Comment by keewis** [comment]
the new code should generate the same report as the old code now, so this should be ready for review.

The tool says we can bump a few libraries, but I guess we should resolve #4179 first.

**Comment by mathause** [comment]
LGTM

**Review by shoyer — APPROVED** [review]
This is great, thanks!

**Review by crusaderky — APPROVED** [review]
This looks great

**Pull request merged**
