### PR TITLE
Remove future statements

### PR DESCRIPTION
**Pull request by max-sixty**
Not sure why these weren't picked up in some of the previous python3-ifying

### CODE REVIEW

**Comment by Zac-HD** [comment]
In all seriousness, pyupgrade will do this and more automatically with the --py3-only option.  I'd add it to CI!

**Comment by max-sixty** [comment]
We did run it through! https://github.com/pydata/xarray/pull/3190

But not with the `--py3-only` it seems... We could do that in this PR

One reason not to enforce it - I can't seem to work out how to apply it to all files in a repo - am I missing something basic? Or does it need another process to loop over files?

**Comment by Zac-HD** [comment]
The author pushes pre-commit pretty hard, but that shouldn't be a problem for Xarray as we're already using it. Then `pre-commit run --all-files` will execute it.

**Comment by max-sixty** [comment]
I think `pre-commit` is great, but that it's too much burden to compel new contributors to use by adding its effects to CI checks. 
I think we've been fairly successful recently at having some less technical folks contribute; keen not to erect even small barriers.

We could add this to `pre-commit` but _not_ to CI; there'd be some unrelated change though.

If anyone is up for a side project - a tool that submits PRs whenever someone commits non-idiomatic code!

Open minded as ever though

**Comment by max-sixty** [comment]
One addendum: if `pre-commit` gained widespread use, and new contributors were installing and learning about it early, I would definitely be up for loading that up with checks

**Comment by Zac-HD** [comment]
[My config](https://github.com/Zac-HD/hypothesmith/blob/master/tox.ini) uses `tox` and `bash` instead of pre-commit.  Doesn't work well for Windows, but it's a tiny Python script to glob for .py files and `subprocess.run` the pyupgrade command.  Balancing powerful CI against new-contributor-friendliness is hard!

```ini
[testenv:check]
deps =
    -r requirements.txt
whitelist_externals = bash
commands =
    autoflake --recursive --in-place --remove-all-unused-imports --remove-duplicate-keys --remove-unused-variables .
    bash -c \"pyupgrade --py36-plus **.py\"
    isort --recursive --apply .
    black .
    flake8
    mypy --config-file=tox.ini . src/
    bandit --recursive --exclude=./.tox/** --skip=B101,B110,B310 --quiet .
```

**Comment by max-sixty** [comment]
Nice! That's quite a list. Between us there's an xkcd or narkoz reference...

**Pull request merged**
