### PR TITLE
Feature/2885 broadcast like

### LINKED ISSUE #2885: Add broadcast_like?
What do you think of adding `da.broadcast_like(a)`?

This would be equivalent to `xr.broadcast(a, da)[1]`

### PR DESCRIPTION
**Pull request by DavidMertz**
- [x] Closes #2885 
 - [x] Tests added
 - [x] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

### CODE REVIEW

**Comment by DavidMertz** [comment]
This was branched off of https://github.com/pydata/xarray/pull/3127 by mistake.  If both are merged, no issue.

**Comment by shoyer** [comment]
Hi @DavidMertz -- @dcherian already started working on this over in https://github.com/pydata/xarray/pull/3086. But there's probably something useful that could be combined between these pull requests, maybe some of the docs or tests?

**Comment by DavidMertz** [comment]
I realized the overlap only after I made the PR. Their implementation of factoring out the shared code is better than my simple wrapper. But my documention and tests are better.

What's the best way to merge the best? I'm happy to do it, but not sure if it should be a new branch and PR, or a revision of one of the existing ones.

**Comment by shoyer** [comment]
I think I'm going to merge the other PR, then you can fork off of master again and add your doc/test improvements?

**Comment by DavidMertz** [comment]
Great. Will do.

**Comment by shoyer** [comment]
OK, I just merged https://github.com/pydata/xarray/pull/3086 in master.

I would suggest either merging `master` into this PR branch, or (probably easier) making a new branch from master with your improved docs/tests.

**Pull request closed without merging**
