### PR TITLE
move da and ds fixtures to conftest.py

### PR DESCRIPTION
**Pull request by mathause**
This PR renames the `da` and `ds` fixtures (to `da_fixture` and `ds_fixture`) and moves them to conftest.py. This allows to remove the flake8 error suppression for the tests and seems more how the fixtures are [intended to be used](https://docs.pytest.org/en/6.2.x/fixture.html#conftest-py-sharing-fixtures-across-multiple-files) (from the pytest side). I think the name changes makes it a bit more obvious what happens but moving them to may make it a bit less obvious (if you don't know where to look).

Removing the flake8 error ignores also unearthed some unused imports:

https://github.com/pydata/xarray/blob/787a96c15161c9025182291b672b3d3c5548a6c7/setup.cfg#L155-L156

(What I actually wanted to do is move the tests for `rolling` to it's own file - but I think it makes sense to do this first.)

### CODE REVIEW

**Review by dcherian — APPROVED** [review]

**Comment by max-sixty** [comment]
I agree with moving them! 

But I haven't seen `..._fixture` in pytest before, and it makes the names longer — could I ask what the benefit of that is? If we wanted `dataarray` & `dataset` then that would be fine...

**Comment by mathause** [comment]
I found the names `da` and `ds` a bit ambiguous. I am happy to adapt to something more common of course - your suggestion would be to name them `dataarray` and `dataset`?

**Comment by max-sixty** [comment]
> your suggestion would be to name them `dataarray` and `dataset`?

That would be great I think!

**Comment by headtr1ck** [comment]
Any chance that this might shadow the "dataarray` and `dataset` modules?
Although I think it is not very common to import these modules directly in the tests.

**Comment by mathause** [comment]
> Any chance that these might shadow the `dataarray` and `dataset` modules? Although I think it is not very common to import these modules directly in the tests.

Good point, haven't thought of this. But I think these are not imported. Staying with `da` and `ds` would also reduce the diff...

**Comment by max-sixty** [comment]
Yes, agree they are not imported — good point but I think this would be OK

**Comment by mathause** [comment]
@max-sixty: so keep `da` or switch to `dataarray` for the fixture?

**Comment by max-sixty** [comment]
Don't put such decisions on a mere mortal!

I would say switch given it sounds like `da` & `ds` caused some confusion. Even if personally I was OK with `da` & `ds`

**Comment by mathause** [comment]
I renamed the fixtures back to `da` & `ds` to make the PR smaller & will merge once the checks are green...

**Pull request merged**
