### PR TITLE
[WIP] [DEMO] Add tests for ZipStore for zarr

### PR DESCRIPTION
**Pull request by hmaarrfk**
- [ ] Related to #3815
 - [ ] Tests added
 - [ ] Passes `isort -rc . && black . && mypy . && flake8`
 - [ ] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

### CODE REVIEW

**Comment by max-sixty** [comment]
My mistake re reproducibility per https://github.com/pydata/xarray/issues/3815#issuecomment-603646754

**Comment by hmaarrfk** [comment]
wouldn't this be a useful to test to have? I think the ability to save things in a zip store is quite useful.

**Comment by max-sixty** [comment]
Yes! But it fails? Otherwise I agree, moar tests...

**Comment by hmaarrfk** [comment]
Alright, it probably makes more sense to reopen this when the issue gets fixed.

**Comment by max-sixty** [comment]
Great! 
Alternatively if you want to surround it with `xfail`, reopen and we can merge....

**Comment by hmaarrfk** [comment]
xfail just gets forgotten, so i'll leave it for now.

**Pull request closed without merging**
