### PR TITLE
update the instructions in the contributing guide

### PR DESCRIPTION
**Pull request by keewis**
Our contributing guide is out-of-date, we usually use merge commits instead of rebasing (which would require force-pushing). This has already lead to confusion, see #4314.

Also, I noticed that in `Delete your merged branch` it recommends to use `git branch -d <feature-branch>` after updating `master`. That doesn't work anymore because we've switched to squash-merges.

 - [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by max-sixty** [comment]
Agree with these changes, thanks @keewis 

Stepping back on the contributing doc — I admit I haven't look at it in a while — I wonder whether we can slim it down a bit, for example by linking to other docs for generic tooling — I imagine we're unlikely to have the best docs on working with GH, for example. Or referencing our PR template rather than the (now out-of-date) PR checklist.

**Comment by keewis** [comment]
ugh. It seems this is the same error as in #4130. This time I can reproduce it locally, though, so now I'm debugging.

**Comment by keewis** [comment]
re contributing docs: would it be best to leave that to the planned docs overhaul?

**Comment by max-sixty** [comment]
> re contributing docs: would it be best to leave that to the planned docs overhaul?

For sure, I didn't mean to weigh down this PR

**Comment by keewis** [comment]
okay, so it seems this happens because RTD only makes shallow copies, as soon as we call `git fetch --unshallow`, the version detection works again.

**Comment by keewis** [comment]
phew, it seems having support set a feature flag to not do shallow clones fixed that particular issue.

**Comment by keewis** [comment]
so I guess this is ready for review and merge?

**Comment by shoyer** [comment]
Thanks @keewis! This is indeed worth updating.

**Comment by keewis** [comment]
Just so we don't forget: do we have a place where we collect ideas for the restructuring of the docs? Or should I just open a tracking issue for this and put it into the `Documentation & User Engagement` board?

**Comment by shoyer** [comment]
> Or should I just open a tracking issue for this and put it into the `Documentation & User Engagement` board?

This sounds good to me!

**Pull request merged**
