### PR TITLE
Speed up localize

### PR DESCRIPTION
**Pull request by Illviljan**
A small performance improvement to `_localize` which is called during interpolation.

### CODE REVIEW

**Comment by Illviljan** [comment]
`get_indexer` is quite heavy. Anyone got any ideas how to remove it?

**Comment by mathause** [comment]
> `get_indexer` is quite heavy. Anyone got any ideas how to remove it?

Unfortunately not, but this would be a small win in any case, no? Should we merge?

**Comment by Illviljan** [comment]
Sure, we can merge. I think I just lost steam on this PR when there was no obvious alternative to get_indexer.

**Comment by mathause** [comment]
Thanks!

**Pull request merged**
