### PR TITLE
Improve alignment typehints

### PR DESCRIPTION
**Pull request by m1so**
- [x] Passes `isort . && black . && mypy . && flake8`
 - [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by max-sixty** [comment]
Hi @m1so — thanks for the PR, and sorry it hasn't been reviewed for a few days.

I've restarted a flaky test.

Is the difference between using the `TypeVar` vs. `DataWithCoords` directly, that this specifies the type supplied in the `objects` argument is the same type in the tuple returned by `align`?

**Comment by m1so** [comment]
No worries, thanks for the response.

Yes, the `TypeVar` suggests that the same type received in `objects` arg will be returned. The main motivation was to help provide better autocompletion in IDEs out of the box, so one doesn't have to appease tools like mypy with a lot of boilerplate
```python
aligned_datasets: Tuple[Dataset, ...] = tuple(xr.align(*datasets))
```

**Comment by max-sixty** [comment]
Great, that makes sense, thanks. 

The name maybe makes it sound like an actual type, but not sure what the conventions are there.

Do you want to add a note in the whatsnew? Then we can merge later.

**Comment by max-sixty** [comment]
Great, that makes sense, thanks. 

The name maybe makes it sound like an actual type, but not sure what the conventions are there.

Do you want to add a note in the whatsnew? Then we can merge later.

**Comment by m1so** [comment]
> The name maybe makes it sound like an actual type, but not sure what the conventions are there.

Wasn't really sure what would be the best name. I'm not aware of any conventions, usually the generic types are denoted with `T`, however this one represents the bound type of data with coordinates (or DataArray/Dataset).

> Do you want to add a note in the whatsnew? Then we can merge later.
Added and rebased

**Comment by max-sixty** [comment]
Perfect! Thank you very much @m1so !

**Pull request merged**
