### PR TITLE
Update related-projects.rst

### PR DESCRIPTION
**Pull request by mmann1123**
adding mention of geowombat for remote sensing applications

- [ ] Closes #xxxx
- [ ] Tests added
- [ ] Passes `pre-commit run --all-files`
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [ ] New functions/methods are listed in `api.rst`

### CODE REVIEW

**Comment by mathause** [comment]
I think that failed due to  #4845. Let's wait until we merge that.

**Comment by mmann1123** [comment]
Sorry, please let me know if i can do anything.

**Comment by mathause** [comment]
No worries, there was a change in another library. It's not directly related to your PR but crashes our docs build so I think it's better to fix that problem first.

**Comment by keewis** [comment]
I pushed the recent changes to your branch so you should not have to do anything else

**Comment by keewis** [comment]
thanks, @mmann1123

**Comment by mmann1123** [comment]
Thanks guys! Can't say how much I appreciate all your work!

**Pull request merged**
