### PR TITLE
update pre-commit hooks

### PR DESCRIPTION
**Pull request by keewis**
I issued a bugfix release for the issue detected in https://github.com/pydata/xarray/pull/4810#discussion_r569830387, so we should use that. `pre-commit autoupdate` also tried to update to `mypy=v0.800`, but this fails because `mypy` does not like the redefinition of `dask_array_type` (and the other `*_type` variables in `xarray.core.pycompat`):
```
xarray/core/pycompat.py:19: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[Any]")
xarray/core/pycompat.py:29: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[Any]")
xarray/core/pycompat.py:37: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[Any]")
```
Does anyone know how to fix that?

- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by mathause** [comment]
I am super confused... These errors should be ignored I think:

https://github.com/pydata/xarray/blob/110c85778a7dd000634618660699ade3148f6d97/setup.cfg#L232-L233

Also I get other errors when running `mypy xarray` (a lot of them:

```python-traceback
xarray/core/pycompat.py:10: error: Skipping analyzing 'dask.array': found module but no type hints or library stubs
```

Somehow it does not recognize the wildcard - don't you get this?

https://github.com/pydata/xarray/blob/110c85778a7dd000634618660699ade3148f6d97/setup.cfg#L182-L183

(this is with mypy 0.800 and numpy 1.19)

---

However, if I update numpy to 1.20 I get a number of errors that (as far as I can tell) have nothing to do with numpy

```python-traceback
xarray/core/common.py:1638: error: Item "None" of "Union[dtype[Any], str, None]" has no attribute "get"
xarray/core/accessor_dt.py:350: error: Argument 3 to "_tslib_field_accessor" of "Properties" has incompatible type "Type[signedinteger[Any]]"; expected "Optional[dtype[Any]]"
```

(for both versions of mypy)

On a related note: I think we should we add a full mypy run again? pre-commit only checks the files that are changed?

**Comment by mathause** [comment]
Sorry, I was wrong about (2) that has to do with numpy.

**Comment by keewis** [comment]
`pre-commit` is run as `pre-commit run --all-files`, which will run the hooks with all files (unless we explicitly told it to skip files matching a pattern).

I do get the errors if I run `python -m mypy xarray` but not if I run `python -m mypy .` or `pre-commit run --all-files`, so I guess `mypy` cannot find the configuration file for `mypy xarray`. With `mypy .`, however, `mypy` will complain about a duplicated `conftest.py`.

**Comment by mathause** [comment]
Thanks, maybe we have to wait for mypy 0.810 then (or however they count). I am still a bit confused why this does not fail for numpy 1.20, though... or does this not install numpy etc?

**Pull request merged**
