### PR TITLE
Test with Python 3.6

### LINKED ISSUE #1182: TST: Add Python 3.6 to test environments

### PR DESCRIPTION
**Pull request by jhamman**
Updated tests to use Python 3.6 for base test and development version tests.

closes #1182

### CODE REVIEW

**Comment by jhamman** [comment]
...and conda doesn't have python 3.6 builds ready yet...

**Comment by jhamman** [comment]
@pydata/xarray - two questions:

- Who is our resident Windows/AppVeyor expert?
- Who do we need to ping in order to get anacona to build `distributed` for Python 3.6?

**Comment by shoyer** [comment]
I don't think we have a window/appveyor expert. 

@mrocklin may know the status of `distributed` builds on Python 3.6.

**Comment by mrocklin** [comment]
Looks like the relevant conda-forge PR is here: https://github.com/conda-forge/distributed-feedstock/pull/18

I haven't taken a close look at things here.  It looks like we need to update the dask/dask feedstock first.  I'll probably do that during the upcoming release process.

**Comment by shoyer** [comment]
@jhamman with my last few commits, things are passing now on Python 3.6. Any objections to merging this?

**Comment by jhamman** [comment]
@shoyer - This looks good. Merging now...

**Pull request merged**
