### PR TITLE
MNT: prepare h5netcdf backend for (coming) change in dimension handling

### LINKED ISSUE #6197: ⚠️ Nightly upstream-dev CI failed ⚠️
[Workflow Run URL](https://github.com/pydata/xarray/actions/runs/1764208897)
<details><summary>Python 3.10 Test Summary Info</summary>

```
FAILED xarray/tests/test_backends.py::TestH5NetCDFData::test_append_write - V...
FAILED xarray/tests/test_backends.py::TestH5NetCDFData::test_append_overwrite_values
FAILED xarray/tests/test_backends.py::TestH5NetCDFData::test_encoding_unlimited_dims
FAILED xarray/tests/test_backends.py::TestH5NetCDFFileObject::test_append_write
FAILED xarray/tests/test_backends.py::TestH5NetCDFFileObject::test_append_overwrite_values
FAILED xarray/tests/test_backends.py::TestH5NetCDFFileObject::test_encoding_unlimited_dims
FAILED xarray/tests/test_backends.py::TestH5NetCDFViaDaskData::test_append_write
FAILED xarray/tests/test_backends.py::TestH5NetCDFViaDaskData::test_append_overwrite_values
FAILED xarray/tests/test_backends.py::TestH5NetCDFViaDaskData::test_encoding_unlimited_dims
FAILED xarray/tests/test_variable.py::TestVariableWithDask::test_multiindex
```

</details>

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- [x] Closes #6197

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@mathause Although I'm pretty sure that this fixes the upstream-dev run, it would be good to verify. Is it possible to run the upstream-dev with this PR?

**Comment by kmuehlbauer** [comment]
I'd also like to add fixes to silence new FutureWarnings emitted by `h5netcdf` (hence the WIP).

**Comment by mathause** [comment]
Great! Thanks for the fix. Yes the string `[test-upstream]` has to be part of the commit message (if you have nothing new to commit you can do `git commit --allow-empty -m "[test-upstream]"`)

**Comment by kmuehlbauer** [comment]
@dionhaefner 

Could you please have a look at the chunksizes FutureWarnings (eg. here https://github.com/pydata/xarray/runs/4965336696?check_suite_focus=true#step:8:344). 

Are the chunksizes via `h5py` and via `h5netcdf` heuristics correct?

**Comment by kmuehlbauer** [comment]
@mathause The fix is applied and works. We have some issues with `chunking` over at `h5netcdf`. This will be fixed after sorting this out.

**Comment by mathause** [comment]
Looks good the remaining upstream failure does not seem to be related.

**Comment by mathause** [comment]
Thanks @kmuehlbauer!

**Comment by mathause** [comment]
Sorry @kmuehlbauer I was too fast with merging. I have to revert this (#6208) and we can do it again once #6207 is fixed.

**Comment by mathause** [comment]
Sorry I was wrong - this was not the cause for the test failure. Let's keep this as is.

**Pull request merged**
