### PR TITLE
fix dtype complex for rasterio backend

### LINKED ISSUE #5491: rasterio backend not supporting complex_int16 type
Dear xarray team,
 problem : `rasterio` xarray's backend doesn't support `complex_int16` dtype.
cmd : 
`xarray.open_rasterio(tiff)`
error : 
```python
----> 4 xarray.open_rasterio(tiff)

/home1/datawork/agrouaze/conda_envs2/envs/xsar_gdal3.3_v2/lib/python3.8/site-packages/xarray/backends/rasterio_.py in open_rasterio(filename, parse_coordinates, chunks, cache, lock)
    371                 attrs[k] = v
    372 
--> 373     data = indexing.LazilyIndexedArray(RasterioArrayWrapper(manager, lock, vrt_params))
    374 
    375     # this lets you write arrays loaded with rasterio

/home1/datawork/agrouaze/conda_envs2/envs/xsar_gdal3.3_v2/lib/python3.8/site-packages/xarray/backends/rasterio_.py in __init__(self, manager, lock, vrt_params)
     40         if not np.all(np.asarray(dtypes) == dtypes[0]):
     41             raise ValueError("All bands should have the same dtype")
---> 42         self._dtype = np.dtype(dtypes[0])
     43 
     44     @property

TypeError: data type 'complex_int16' not understood
```
versions : 
rasterio == 1.2.4
gdal == 3.3.0
numpy == 1.20.4
xarray == 0.18.2
system : Linux Ubuntu 16.04.7
Python 3.8.10

possible patch in `xarray/backends/rasterio_.py` line 42:
```python
     if dtypes[0]!='complex_int16':#patch agrouaze June 2021
            self._dtype = np.dtype(dtypes[0])
     else:
            self._dtype = np.complex
```
Thanks for your help!

### PR DESCRIPTION
**Pull request by agrouaze**
rasterio backend support for the `complex_int16` dtype

- [x] Closes #5491 
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by jhamman** [comment]
@grouny - thanks for this PR! And I see that this is your first time contributing to Xarray -- Welcome!

This fix you propose looks great. Apart from the linter complaining about some whitespace, I think this would benefit from a simple test. Would you mind adding a test to `xarray/tests/test_backends.py`? 

Q for @snowman2 - is rioxarray handling complex datatypes in this way?

**Review by keewis — COMMENTED** [review]
@jhamman, there's a PR here: corteva/rioxarray#353

**Comment by grouny** [comment]
Yes I can think about a test. Could this test be a simple .tiff file opennng or is it too high level?

**Comment by snowman2** [comment]
Also see: https://github.com/corteva/rioxarray/pull/359

**Comment by max-sixty** [comment]
As discussed in the dev meeting, this would be great to merge. The test could be to create a small file, and then read it. Would that work @grouny ?

**Comment by grouny** [comment]
I added a test un test_backends.py :
`pytest -s ./test_backends.py::TestRasterio::test_rasterio_complex_dtype`
But since there is a fix in rasterio I am wondering whether this PR is still needed:
https://github.com/mapbox/rasterio/commit/7114fb7fb5e48146c4f04eb818daaa1fa632d817

**Comment by dcherian** [comment]
We're about to remove the built-in rasterio backend in favour of rioxarray. Sorry for not merging this earlier @agrouaze

**Pull request closed without merging**
