### PR TITLE
fix tests for h5netcdf v0.12

### PR DESCRIPTION
**Pull request by mathause**
h5netcdf no longer warns for invalid netCDF (unless passing `save_kwargs = {"invalid_netcdf": True}`. We need to adapt our tests.

@kmuehlbauer

---

edit: I added h5netcdf to the upstream tests - I can also revert this change if you prefer.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@mathause See https://github.com/h5netcdf/h5netcdf/issues/100. `h5netcdf` changed this to raise `CompatibilityError` with latest version. Sorry for not bringing this to attention earlier.

Are the CI errors connected to changes in `h5netcdf`?

**Comment by kmuehlbauer** [comment]
@mathause I think it would be great to test `h5netcdf` within the upstream tests to get notified early if something breaks.

**Comment by mathause** [comment]
There is an annoying amount of upstream failures. I just merged main - that should help a bit but unfortunately there are still open issues.
- Some of them are fixed in #6096
- For some we are still waiting for a new dask release dask/dask#8482

Let's see what the CI says now.

**Comment by mathause** [comment]
I had a look at the tests & the failures are unrelated to h5netcdf. @kmuehlbauer if you are happy with the changes I would merge soon.

**Comment by kmuehlbauer** [comment]
@mathause I think it looks good. Thanks.

**Comment by mathause** [comment]
thanks for the review!

**Pull request merged**
