### PR TITLE
[WIP] Support nano second time encoding.

### LINKED ISSUE #4183: Unable to decode a date in nanoseconds
**What happened**:

If the unit of a date, is a number of nanoseconds elapsed since a reference date, xarray cannot read this dataset and throws the exception ``KeyError: nanoseconds``.

**What you expected to happen**:

As this unit is valid in CF model, it must be decoded. Today the units that are recognized go from day to microseconds in the module ``coding/time.py``.

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import array as xr

xr.DataArray(
    np.arange(0, 1e10, 1e9).astype("int64"),
    attrs=dict(units="nanoseconds since 1970-01-01")).to_netcdf("/tmp/test.nc")
xr.open_dataset("/tmp/test.nc")
```
**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-957.12.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.7.4

xarray: 0.15.1
pandas: 1.0.4
numpy: 1.17.5
scipy: 1.4.1
netCDF4: 1.5.3
pydap: None
h5netcdf: 0.8.0
h5py: 2.10.0
Nio: None
zarr: 2.4.0
cftime: 1.1.3
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.18.1
distributed: 2.18.0
matplotlib: 3.2.1
cartopy: None
seaborn: None
numbagg: None
setuptools: 47.3.1.post20200616
pip: 20.1.1
conda: 4.8.3
pytest: 5.4.3
IPython: 7.15.0
sphinx: None

</details>

### PR DESCRIPTION
**Pull request by hmaarrfk**
Not too sure i have the bandwidth to complete this seeing as cftime and datetime don't have nanoseconds, but maybe it can help somebody.

 - [x] Closes #4183
 - [x] Tests added
 - [ ] Passes `isort . && black . && mypy . && flake8`
 - [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
 - [ ] New functions/methods are listed in `api.rst`

### CODE REVIEW

**Comment by aldanor** [comment]
Is there anything preventing to merge this?

**Comment by aldanor** [comment]
Oh, that requires `cftime._cftime` support first? :/

**Comment by aldanor** [comment]
But the test already passes (i.e. you can at least do a `.encoding={.... 'nanoseconds'}` and avoid float conversion?

**Comment by hmaarrfk** [comment]
yeah, i'm not too sure. I think the idea is that this breaks compatibility with netcdf times, so the resulting file is thus not standard.

For my application, us timing is enough.

**Comment by aldanor** [comment]
I think netcdf lists "nanoseconds" as a valid unit though?

**Comment by aldanor** [comment]
I'm working on an application where nanosecond-resolution is critical and took me days to find why my timestamps are all scrambled or off-by-1 after I write them with xarray and them read them back... would probably much rather prefer if it threw an exception instead of corrupting your data silently. 

Non-standard netcdf or not, if it was possible to just store them as plain int64s and read them back as is, that would help a ton...

**Comment by hmaarrfk** [comment]
I think you should be able to define your own custom encoder if you want it to be a datetime.

But inevitably, you will have to define your own save and load functions.

Python, by definition of being such a loose language, allows you to do things that the original developers never really imagined.

this can sometimes lead to silent corruption.like the one you've experienced.

**Comment by aldanor** [comment]
Yea, well, in this case it's not about Python... `M8[ns]` datatype is simply an `int64` underneath, why not just store it as that, no bells and whistles required, no corruption possible, no funky conversions?

**Comment by dcherian** [comment]
The merge conflict suggests this was fixed on main by #4684

**Comment by hmaarrfk** [comment]
nice!

**Pull request closed without merging**
