### PR TITLE
Enable pandas type checking

### PR DESCRIPTION
**Pull request by headtr1ck**
Since pandas-stubs is making good progress, I would say it is slowly advantageous to enable type checking for it.
About 200 mypy errors have to be fixed....

- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by headtr1ck** [comment]
It seems that mypy is now resolving the operators more precisely and also it seems that this causes some issues with the current implementation.

It looks like we have to completely rework them... :/
This is gonna take some time to get it right!

**Comment by headtr1ck** [comment]
After some debugging I noticed that DatasetGroupby + Dataset-subclass will return Dataset and not Dataset-subclass.
So our current typing of Self is wrong.

I think refactoring the code to actually return the subclass is blocked by the Coordinates refactor...

**Comment by max-sixty** [comment]
> It seems that mypy is now resolving the operators more precisely and also it seems that this causes some issues with the current implementation.
> 
> It looks like we have to completely rework them... :/

For the pandas items or for all? 🫨 

FWIW IIRC the latest mypy fails on `main` (though that could be a much much smaller & separate change...)

**Comment by max-sixty** [comment]
> After some debugging I noticed that DatasetGroupby + Dataset-subclass will return Dataset and not Dataset-subclass.
> So our current typing of Self is wrong.

I remember hitting similar things in the past. Ideally we'd return the subclass; but to the extent we don't I would heavily deprioritize any big effort to change the typing to state we return `Dataset` — instead I would vote to push it off until we can return the subclass...

**Comment by headtr1ck** [comment]
> For the pandas items or for all? 🫨

I think I have fixed all mypy issues related to pandas.

> FWIW IIRC the latest mypy fails on `main` (though that could be a much much smaller & separate change...)

I though of quickly fixing these issues here as well, turns out not to be so easy...

**Comment by headtr1ck** [comment]
Issue seems to be in `xarray.core.types` with 
```python
    try:
        from dask.array import Array as DaskArray
    except ImportError:
        DaskArray = np.ndarray
```
Somehow that gets evaluated to Any, which in turn makes mypy think that `DataArray + anything = DataArray`, even when this "anything" equals a Dataset/DatasetGroupby...

If I try to recreate this locally, I don't get Any, so no idea what is going on there...

Done for today, lets see how one solves this issue.

**Comment by headtr1ck** [comment]
After hours of trying to figure out what is going on, I am close to giving up :/
If I create a file `xarray.core.types2.py` with the exact same content as `xarray.core.types.py`, the `DaskArray` gets correctly resolved in types2 but not types.... WTH is going on?
Is that a mypy bug???? :/

**Comment by max-sixty** [comment]
That doesn't sound fun...

> If I create a file `xarray.core.types2.py` with the exact same content as `xarray.core.types.py`, the `DaskArray` gets correctly resolved in types2 but not types.... WTH is going on?

Where are the errors from `types.py`? I don't see them in https://github.com/pydata/xarray/actions/runs/9845800832/job/27182145496?pr=9213#step:8:58

**Comment by headtr1ck** [comment]
> Where are the errors from `types.py`? I don't see them in https://github.com/pydata/xarray/actions/runs/9845800832/job/27182145496?pr=9213#step:8:58

As I was saying some comments up, the mypy errors are the ones in _typed_ops. But these are only a symptom not the root of the error...

Mainly: `Variable + Any = Variable`, but should not be the case for e.g. Dataset.
This is because we type the "other" as `Union[ArrayLike, Variable, DaskArray]`, but since `DaskArray = Any` thats what happens...

**Comment by max-sixty** [comment]
Something does seem confusing with `DaskArray`. 

One thing that does seem to fix almost all errors is just excluding `DaskArray`. Arguably even if we can't improve from here this would be a quite worthwhile tradeoff. In particular there is a lot of code here it would be great to merge before we get conflicts etc, to the extent we can push dask typing precision off...

```diff
diff --git a/xarray/core/types.py b/xarray/core/types.py
index 20d94de5..5b231780 100644
--- a/xarray/core/types.py
+++ b/xarray/core/types.py
@@ -178,7 +178,8 @@ def copy(
 T_ExtensionArray = TypeVar("T_ExtensionArray", bound=pd.api.extensions.ExtensionArray)
 
 
-ScalarOrArray = Union["ArrayLike", np.generic, np.ndarray, "DaskArray"]
+# ScalarOrArray = Union[ArrayLike, np.generic, np.ndarray, DaskArray]
+ScalarOrArray = Union[ArrayLike, np.generic, np.ndarray]
 VarCompatible = Union["Variable", "ScalarOrArray"]
 DaCompatible = Union["DataArray", "VarCompatible"]
 DsCompatible = Union["Dataset", "DaCompatible"]
```

---

FWIW I also get weirdness around using `dmypy` with these — after a few changes it reports quite different results than `mypy`. Maybe it's a version thing...

**Comment by headtr1ck** [comment]
@max-sixty thank you! That was the solution, and it does not even matter, because a `DaskArray` is `ArrayLike` anyway!
Wow, that was some wasted hours.
Still I believe that this is some kind of mypy bug, but too difficult to trace!

**Comment by headtr1ck** [comment]
remaining mypy errors are from numpy2, see https://github.com/pydata/xarray/issues/9231

**Comment by dcherian** [comment]
Force-merged since the auto-merge won't work till mypy on main is fixed.

**Pull request merged**
