### PR TITLE
fix Edit on GitHub

### LINKED ISSUE #2821: DOC: Broken links from generated documentation to github
This is the link that is used when i click on the "Edit on Github" button in the documentation. 
https://github.com/pydata/xarray/blob/stable/doc/generated/xarray.DataArray.std.rst 

I wish to access the implementation of Dataset.std() because I am not able to reproduce the results when I calculate the sample standard deviation. Based on the formula below. 

STD = sqrt( sum( x - x.mean() )**2 / (n-1) )

### PR DESCRIPTION
**Pull request by keewis**
This uses `scanpydoc`'s `github_url` jinja filter to fix the github url in our api docs, and to also always point to `master` (see https://github.com/pydata/xarray/pull/4440#issuecomment-695835133).

This currently does not work because we need support to enable the `DONT_OVERWRITE_SPHINX_CONTEXT` flag. We also might want to vendor `github_url` because it is only a small part of `scanpydoc`.

 - [x] Closes #2821
 - [x] Passes `isort . && black . && mypy . && flake8`

### CODE REVIEW

**Comment by dcherian** [comment]
>  vendor github_url because it is only a small part of scanpydoc.

:+1:

**Comment by max-sixty** [comment]
Amazing! Thanks @keewis !

Shall I email RTD support re `DONT_OVERWRITE_SPHINX_CONTEXT` or do you want to?

**Comment by keewis** [comment]
> Shall I email RTD support re `DONT_OVERWRITE_SPHINX_CONTEXT` or do you want to?

sorry for not telling, I already did that directly after creating the PR

**Comment by keewis** [comment]
I looked at the source of `scanpydoc.rtd_github_links`. It seems to be a bit larger than I expected, and is also licensed as GPLv3, so I guess it should be fine to keep it as a docs-only dependency (is vendoring GPLv3-licensed code even possible for non-GPL projects?).

**Comment by keewis** [comment]
okay, so support enabled the flag, but RTD times out while downloading something in `plotting.rst`. Does anyone know what's going on?

**Comment by dcherian** [comment]
These natural earth URLs time out sometimes. 

It's timing out on the browser for me now: https://naciscdn.org/naturalearth/110m/physical/ne_110m_coastline.zip

**Comment by keewis** [comment]
yes, it seems https://naciscdn.org is down.

**Comment by keewis** [comment]
to fix this, should we try to use [cartopy_offlinedata](https://anaconda.org/conda-forge/cartopy_offlinedata)?

**Comment by dcherian** [comment]
Does that help on CI?

**Comment by keewis** [comment]
not sure, I'm [trying that](https://readthedocs.org/projects/xarray-keewis/builds/11963638/) right now

**Comment by keewis** [comment]
`naciscdn.org` is up again so the build passes.

However, since the version is set to `master` the line numbers `github_url` determines might be wrong for other versions (e.g. `stable`). Should we remove those?

**Comment by shoyer** [comment]
Let's keep `scanpydoc` as a docs only dependency, which I think is the easiest option from a GPL compliance perspective (we don't want to make all of xarray GPL)

**Comment by keewis** [comment]
if I remember the meeting correctly, this should be ready for merging?

**Comment by dcherian** [comment]
Thanks @keewis.

**Comment by max-sixty** [comment]
Thanks @keewis — it's great this is solved 🙏

**Pull request merged**
