### PR TITLE
Use micromamba 1.5.10 where conda is needed

### PR DESCRIPTION
**Pull request by kmuehlbauer**
## Updated behaviour

Since micromamba 2.0 installing conda seems to be broken in CI. In #9732 conda was removed from the install where not absolutely needed and the micromamba version was pinned to 2.0.2-0 due to broken 2.0.3-0.

The broken version was yanked and this PR reverts to the default micromamba version (now 2.0.2-0). In CI runs where conda is absolutely needed the micromamba-version is set to 1.5.10-0 (last version of v1-release line).

- When https://github.com/airspeed-velocity/asv/pull/1439 is resolved, we can remove the pin in the benchmark CI runs. 
- By resolving https://github.com/pydata/xarray/pull/9737#issuecomment-2463397879 the pin in the min-deps-check CI run will be removed.

## Former ramblings:

conda.api and libmambapy are not API compatible

In https://github.com/pydata/xarray/blob/main/ci/min_deps_check.py we use `conda.api` to gather package versions from `["conda-forge", "defaults"]` channel (shouldn't we remove defaults, because of the legal stuff?).

The replacement for micromamba v2 is `libmambapy` which unfortunately isn't API compatible. It should have all the capabilities to do the same, but I wasn`t successful ( :man_shrugging: ) in gathering the correct incantations from the docs:

- https://mamba.readthedocs.io/en/latest/usage/specs.html
- https://mamba.readthedocs.io/en/latest/usage/solver.html

If figured out the correct way, this can eventually be replaced.

Tested micromamba/libmamba 2.0.2-0 also for:

- :white_check_mark: upstream
- :x: benchmark, asv doesn't work, need to step back here, too
- :white_check_mark: hypothesis
- :x: pyright, currently disabled

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@keewis I've missed this yesterday, so checked it today.

asv is also not yet ready for micromamba 2 , so I've reverted min-deps-check and benchmark CI runs to use last 1.5.10-0 version of mamba/micromamba. All other CI runs look good.

WOuld be nice, if you could have another look here. Thanks!

**Review by keewis — APPROVED** [review]
looks good, just a couple of comments:
- I don't have knowledge about the benchmarks, so I can't comment on that
- according to the issue you opened we might be able to remove most of the `micromamba` version pins again?
- regarding `libmambapy`, I think it is time to rewrite the min-versions script anyways, so I think pinning for now is fine

> shouldn't we remove defaults, because of the legal stuff?

we're firmly open source, so that shouldn't affect us (I think?). However, we don't really use the `defaults` channel anywhere else, so my guess is that this was to get more accurate `python` release dates? All that would change, though, is that we would get to advance the bump date by a few days – which we usually miss by a couple of weeks anyways, so doesn't really matter either way. And finally, see my note above about rewriting the script.

**Comment by keewis** [comment]
I think we can use `py-rattler`'s version of [`query`](https://conda.github.io/rattler/py-rattler/gateway/#rattler.repo_data.gateway.Gateway.query) instead, which will get rid of the `conda` dependency, is much faster, and we can avoid the undocumented `libmambapy` API.

I'll open a PR for the rewrite of the script once it's close to being ready.

**Comment by kmuehlbauer** [comment]
@keewis I've followed your suggestion to use default settings where applicable, as the problematic version was removed.

Let's see how this works.

**Comment by kmuehlbauer** [comment]
Nice, array-api-strict 2.1.2 (released 5 hours ago) breaks the tests.

**Pull request merged**
