### PR TITLE
`"source"` encoding for datasets opened from `fsspec` objects

### LINKED ISSUE #4830: GH2550 revisited
**Is your feature request related to a problem? Please describe.**
I am retrieving files from AWS: https://registry.opendata.aws/wrf-se-alaska-snap/. An example:
```
import s3fs
import xarray as xr

s3 = s3fs.S3FileSystem(anon=True)
s3path = 's3://wrf-se-ak-ar5/gfdl/hist/daily/1980/WRFDS_1980-01-0[12].nc'
remote_files = s3.glob(s3path)
fileset = [s3.open(file) for file in remote_files]

ds = xr.open_mfdataset(fileset, concat_dim='Time', decode_cf=False)
ds
```
Data files for 1980 are missing time coordinate, so the above code fails. The time could be obtained by parsing file name, however in the current implementation the *source* attribute is available only when the fileset consists of strings or *Path*s. 

**Describe the solution you'd like**
I would suggest to return to the original suggestion in #2550 - pass *filename_or_object* as an argument to *preprocess* function, but with necessary inspection. Here is my attempt (code in *open_mfdataset*):
```
open_kwargs = dict(
        engine=engine, chunks=chunks or {}, lock=lock, autoclose=autoclose, **kwargs
    )

    if preprocess is not None:
        # Get number of free arguments
        from inspect import signature
        parms = signature(preprocess).parameters
        num_preprocess_args = len([p for p in parms.values() if p.default == p.empty])
        if num_preprocess_args not in (1, 2):
            raise ValueError('preprocess accepts only 1 or 2 arguments')

    if parallel:
        import dask

        # wrap the open_dataset, getattr, and preprocess with delayed
        open_ = dask.delayed(open_dataset)
        getattr_ = dask.delayed(getattr)
        if preprocess is not None:
            preprocess = dask.delayed(preprocess)
    else:
        open_ = open_dataset
        getattr_ = getattr

    datasets = [open_(p, **open_kwargs) for p in paths]
    file_objs = [getattr_(ds, "_file_obj") for ds in datasets]
    if preprocess is not None:
        if num_preprocess_args == 1:
            datasets = [preprocess(ds) for ds in datasets]
        else:
            datasets = [preprocess(ds, p) for (ds, p) in zip(datasets, paths)]
```
With this, I can define function *fix* as follows:
```
def fix(ds, source):
    vtime = datetime.strptime(os.path.basename(source.path), 'WRFDS_%Y-%m-%d.nc')
    return ds.assign_coords(Time=[vtime])

ds = xr.open_mfdataset(fileset, preprocess=fix, concat_dim='Time', decode_cf=False)
```
This is backward compatible, *preprocess* can accept any number of arguments:
```
from functools import partial
import xarray as xr

def fix1(ds):
    print('fix1')
    return ds

def fix2(ds, file):
    print('fix2:', file.as_uri())
    return ds

def fix3(ds, file, arg):
    print('fix3:', file.as_uri(), arg)
    return ds

fileset = [Path('/home/george/Downloads/WRFDS_1988-04-23.nc'),
           Path('/home/george/Downloads/WRFDS_1988-04-24.nc')
          ]
ds = xr.open_mfdataset(fileset, preprocess=fix1, concat_dim='Time', parallel=True)
ds = xr.open_mfdataset(fileset, preprocess=fix2, concat_dim='Time')
ds = xr.open_mfdataset(fileset, preprocess=partial(fix3, arg='additional argument'),
                       concat_dim='Time')
```
```
fix1
fix1
fix2: file:///home/george/Downloads/WRFDS_1988-04-23.nc
fix2: file:///home/george/Downloads/WRFDS_1988-04-24.nc
fix3: file:///home/george/Downloads/WRFDS_1988-04-23.nc additional argument
fix3: file:///home/george/Downloads/WRFDS_1988-04-24.nc additional argument
```
**Describe alternatives you've considered**
The simple solution would be to make xarray s3fs aware. IMHO this is not particularly elegant. Either a check for an attribute, or an import within a *try/except* block would be needed.

### LINKED ISSUE #9142: mfdataset - ds.encoding["source"] to retrieve filename not valid key
### What happened?

Looking at the doc https://docs.xarray.dev/en/stable/generated/xarray.open_mfdataset.html 

> preprocess ([callable()](https://docs.python.org/3/library/functions.html#callable), optional) – If provided, call this function on each dataset prior to concatenation. You can find the file-name from which each dataset was loaded in ds.encoding["source"].

I expected to be able to use ds.encoding["source"] in my preprocess function to retrieve the filename. However I get

### What did you expect to happen?

I expected the doc to be correct? unless I missed something trivial.

### Minimal Complete Verifiable Example

```Python
def preprocess_xarray_no_class(ds):
    filename = ds.encoding["source"]
    ds = ds.assign(
        filename=("time"), [filename])
    )  # add new filename variable with time dimension
    return ds

ds = xr.open_mfdataset(
    fileset,
    preprocess=preprocess_xarray_no_class,
    engine='h5netcdf',
    concat_characters=True,
    mask_and_scale=True,
    decode_cf=True,
    decode_times=True,
    use_cftime=True,
    parallel=True,
    decode_coords=True,
    compat="equals",

)
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [X] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Relevant log output

```Python
...
      1 def preprocess_xarray_no_class(ds):
----> 2     filename = ds.encoding["source"]
      3     ds = ds.assign(
      4         filename=("time",), [filename])
      5     )  # add new filename variable with time dimension

KeyError: 'source'
```

### Anything else we need to know?

_No response_

### Environment

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
python-bits: 64
OS: Linux
OS-release: 6.5.0-1023-oem
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: C.UTF-8
LANG: en_IE.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.14.2
libnetcdf: 4.9.3-development

xarray: 2024.6.0
pandas: 2.2.2
numpy: 1.26.4
scipy: 1.13.1
netCDF4: 1.7.1
pydap: None
h5netcdf: 1.3.0
h5py: 3.11.0
zarr: 2.18.2
cftime: 1.6.4
nc_time_axis: 1.4.1
iris: None
bottleneck: 1.3.8
dask: 2024.6.0
distributed: 2024.6.0
matplotlib: 3.9.0
cartopy: None
seaborn: 0.13.2
numbagg: 0.8.1
fsspec: 2024.6.0
cupy: None
pint: None
sparse: None
flox: 0.9.7
numpy_groupies: 0.11.1
setuptools: 70.0.0
pip: 24.0
conda: None
pytest: 8.2.2
mypy: 1.10.0
IPython: 7.34.0
sphinx: None

</details>

### PR DESCRIPTION
**Pull request by keewis**
When opening files from path-like objects (`str`, `pathlib.Path`), the backend machinery (`_dataset_from_backend_dataset`) sets the `"source"` encoding. This is useful if we need the original path for additional processing, like writing to a similarly named file, or to extract additional metadata. This would be useful as well when using `fsspec` to open remote files.

In this PR, I'm extracting the `path` attribute that most `fsspec` objects have to set that value. I've considered using `isinstance` checks instead of the `getattr`-with-default, but the list of potential classes is too big to be practical (at least 4 classes just within `fsspec` itself).

If this sounds like a good idea, I'll update the documentation of the `"source"` encoding to mention this feature.

- [x] Tests added
- [x] Closes #9142, Closes #4830
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by max-sixty** [comment]
Without knowing much (I generally `ds.reset_encoding()`) it does sound like a good idea!

**Comment by Illviljan** [comment]
Shouldn't `_normalize_path` or `_find_absolute_paths` be able to handle this?

**Comment by keewis** [comment]
the main use case is indeed to extract additional data, which you'd do immediately after `open_dataset` (after which you could drop the encoding).

> Shouldn't `_normalize_path` or `_find_absolute_paths` be able to handle this?

As far as I can tell, they only convert path-likes to string (which these objects are not, they are file-like, not path-like). Are you suggesting we should change that?

**Comment by keewis** [comment]
my impression of that discussion was that we wanted to either return the encoding in a separate object, or somehow remove the encoding after the first operation (i.e. not carry it around). Which would be fine with me, since I would still have access to it.

**Comment by dcherian** [comment]
Would a dataset with this in encoding be round tripped without error? Would be good to test that

**Comment by dcherian** [comment]
Ah thanks. My mistake m I thought we were sticking in the fsspec object not just the path

**Comment by keewis** [comment]
as far as I can tell, we could write anything in that encoding (`fsspec` objects, strings, or other things), and it would simply be ignored.

**Pull request merged**
