### PR TITLE
Allow pathlib.Path to be passed to all engines

### PR DESCRIPTION
**Pull request by alexamici**
- Related to #4309 and in particular: https://github.com/pydata/xarray/issues/4309#issuecomment-747055666
 - [x] Passes `isort . && black . && mypy . && flake8`
 - No user visible change

Once `ZarrStore.open_group` and `NetCDF4DataStore.open` accepts `pathlib.Path` objects we can remove `_normalize_path` from `apiv2.open_dataset`. All other backends accept them.

Note that `zarr` itself doesn't support them, yet. See: https://github.com/zarr-developers/zarr-python/issues/601

### CODE REVIEW

**Comment by max-sixty** [comment]
LGTM @alexamici !

Could we add a small test / param onto an existing test? Or do you want to handle that as part of the larger PRs?

**Comment by alexamici** [comment]
@max-sixty there's no direct test for the backend Store classes, only indirect tests through `open_dataset`. For example all other beckends do support `pathlib.Path` but none is tested.

Once we remove `_normalize_path` (PR is coming, and we may need a bit of discussion before approval) we will be able to test all backends.

I propose to merge this PR as it is.

**Review by aurghs — APPROVED** [review]

**Comment by max-sixty** [comment]
Great! Thanks!

**Comment by clbarnes** [comment]
Zarr's convenience methods accept Path objects as of 2.9.0: https://zarr.readthedocs.io/en/stable/release.html#enhancements

**Pull request merged**
