### PR TITLE
Allow for consistenty ordered coords

### PR DESCRIPTION
**Pull request by max-sixty**
- [ ] Tests added
 - [ ] Passes `isort . && black . && mypy . && flake8`
 - [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
 - [ ] New functions/methods are listed in `api.rst`

I took an initial stab at allowing for consistently ordered coords, which came up recently, by using a list rather than a set. It's fairly involved, and the currently proposed code fails quite a few tests.

Another option would be to use `OrderedSet`. Or to leave it as a `set`.

### CODE REVIEW

**Comment by dcherian** [comment]
> Another option would be to use OrderedSet.

Would this be a smaller change overall (aside from typing)?

**Comment by max-sixty** [comment]
> Would this be a smaller change overall (aside from typing)?

I think slightly smaller, yes.

**Comment by max-sixty** [comment]
As discussed in dev meeting:
- one case to look at is that of pulling a variable out of a dataset
- consider using an `OrderedSet`, which will perform better in worst case

**Comment by dcherian** [comment]
> one case to look at is that of pulling a variable out of a dataset

@max-sixty see https://github.com/pydata/xarray/pull/4744

**Review by keewis — COMMENTED** [review]
I forgot to submit these suggestions before the meeting, so they might be out-of-date (but possibly still helpful).

**Comment by max-sixty** [comment]
Going to close this in favor of using an `OrderedSet`. I should have realized that would be a better design in the first place!

**Pull request closed without merging**
