### PR TITLE
DOC: add see also for to_zarr

### LINKED ISSUE #5159: DOC: link to_zarr docs to io section on zarr
the to_zarr docs http://xarray.pydata.org/en/latest/generated/xarray.Dataset.to_zarr.html could add a "See Also" and point to http://xarray.pydata.org/en/latest/user-guide/io.html?highlight=zarr#zarr

### PR DESCRIPTION
**Pull request by raybellwaves**
- [x] Closes #5159 
- [ ] Tests added
- [ ] Passes `pre-commit run --all-files`
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [ ] New functions/methods are listed in `api.rst`

### CODE REVIEW

**Comment by max-sixty** [comment]
Great! Thanks as ever @raybellwaves

**Comment by keewis** [comment]
sorry for not answering sooner. The issue with the link is that we have multiple versions on RTD, so with a explicit link we're linking from a docstring in `latest` to `stable`. To fix that I think we should change that to
```
:doc:`io.zarr`
```
or something similar (I didn't check whether that label was defined) in a follow-up PR, with the disadvantage that this is not really useful when viewing with `pydoc` / `help` / IPython's `?` operator.

**Comment by zmoon** [comment]
Currently renders like this, which I don't think is intended.

image

numpydoc *See Also* section is really intended for references to code; it is taking `http` as the identifier (and linking to Python std lib's http package).

**Comment by max-sixty** [comment]
Thanks @keewis & @zmoon , mea culpa.

@raybellwaves would you like to swap for @keewis 's suggestion? I'm happy to otherwise.

**Pull request merged**
