### PR TITLE
Remove old PR template

### PR DESCRIPTION
**Pull request by max-sixty**

### CODE REVIEW

**Comment by mathause** [comment]
I kind of liked it - are we replacing it with anything? Is there a new template?

**Comment by max-sixty** [comment]
We have the new one, no? So this doesn't do anything. Or am I woefully mistaken?

**Comment by keewis** [comment]
As far as I understand it we only have new issue templates, which means that opening a new PR results in a empty text box at the moment. Should we revert this, or do we want to write a new one instead?

**Comment by max-sixty** [comment]
I'm sorry, I moved too fast. I'll revert now.

**Pull request merged**
