### PR TITLE
Increase support window of all dependencies

### LINKED ISSUE #4295: We shouldn't require a recent version of setuptools to install xarray
@canol reports on our mailing that our setuptools 41.2 (released 21 August 2019) install requirement is making it hard to install recent versions of xarray at his company:
https://groups.google.com/g/xarray/c/HS_xcZDEEtA/m/GGmW-3eMCAAJ

> Hello, this is just a feedback about an issue we experienced which caused our internal tools stack to stay with xarray 0.15 version instead of a newer versions.
>
> We are a company using xarray in our internal frameworks and at the beginning we didn't have any restrictions on xarray version in our requirements file, so that new installations of our framework were using the latest version of xarray. But a few months ago we started to hear complaints from users who were having problems with installing our framework and the installation was failing because of xarray's requirement to use at least setuptools 41.2 which is released on 21th of August last year. So it hasn't been a year since it got released which might be considered relatively new.
>
> During the installation of our framework, pip was failing to update setuptools by saying that some other process is already using setuptools files so it cannot update setuptools. The people who are using our framework are not software developers so they didn't know how to solve this problem and it became so overwhelming for us maintainers that we set the xarray requirement to version >=0.15 <0.16. We also share our internal framework with customers of our company so we didn't want to bother the customers with any potential problems.
>
> You can see some other people having having similar problem when trying to update setuptools here (although not related to xarray): https://stackoverflow.com/questions/49338652/pip-install-u-setuptools-fail-windows-10
> 
> It is not a big deal but I just wanted to give this as a feedback. I don't know how much xarray depends on setuptools' 41.2 version.

I was surprised to see this in our `setup.cfg` file, added by @crusaderky in #3628. The version requirement is not documented in our docs.

Given that setuptools may be challenging to upgrade, would it be possible to relax this version requirement?

### PR DESCRIPTION
**Pull request by crusaderky**
Closes #4295

Increase width of the sliding window for minimum supported version:
- setuptools from 6 months sliding window to hardcoded >= 38.4, and to 42 months sliding window starting from July 2021
- dask and distributed from 6 months sliding window to hardcoded >= 2.9, and to 12 months sliding window starting from January 2021
- all other libraries from 6 months to 12 months sliding window

### CODE REVIEW

**Comment by max-sixty** [comment]
Thanks @crusaderky , LGTM

To confirm, this is still "the oldest version _released_ within the time period", rather than "the version that existed at the start of the time period"

(which as discussed in other threads is a bit odd, but that's what numpy does so...)

**Comment by crusaderky** [comment]
> To confirm, this is still "the oldest version released within the time period", rather than "the version that existed at the start of the time period"

Yes, this hasn't changed.

**Comment by max-sixty** [comment]
I'm guessing the docs failure is unrelated — I can't see why this would be affected and there doesn't seem to be any error in the logs. Does that sound right?

**Comment by crusaderky** [comment]
@max-sixty definitely unrelated

**Comment by keewis** [comment]
the failing docs CI is indeed unrelated and will be fixed by #4286

**Comment by keewis** [comment]
support set a feature flag, so now RTD appends to our environment file instead of executing multiple install commands. That means version pinning of `sphinx` works and the docs CI should hopefully pass.

**Comment by shoyer** [comment]
> support set a feature flag, so now RTD appends to our environment file instead of executing multiple install commands. That means version pinning of `sphinx` works and the docs CI should hopefully pass.

Awesome, thanks for digging in here! Multiple install commands in RTD has been persistently very painful / error-prone.

**Pull request merged**
