### PR TITLE
Run mypy in pre-commit only in CI?

### PR DESCRIPTION
**Pull request by max-sixty**
On top of https://github.com/pydata/xarray/pull/5467, given I'm not sure this is correct.

With `additional_dependencies`, we may not need the additional CI run.

But OTOH there's nothing confirming that the `additional_dependencies` has the correct dependencies and there's no material cost to the additional step.

### CODE REVIEW

**Comment by max-sixty** [comment]
@keewis @andersy005 — could I ask (and forgive me if I'm mistaken / misremembering you as working on this) — any idea why the latest CI on this PR was cancelled? Is it something to do with pushing another commit to https://github.com/pydata/xarray/pull/5467?

**Comment by andersy005** [comment]
@max-sixty, I skimmed through Github Action logs, but I couldn't figure out where the "cancel" command came from. I am going to speculate that it was some glitch in GitHub action. 

>  Is it something to do with pushing another commit to #5467?

Pushing another commit to the same branch should cancel previous runs and start new runs (for the new commit). So, the fact that all runs were cancelled makes me think that it was a glitch somewhere :)

**Comment by andersy005** [comment]
> Pushing another commit to the same branch should cancel previous runs and start new runs (for the new commit). So, the fact that all runs were cancelled makes me think that it was a glitch somewhere :)

I take this back... I just realized that #5467 is a different PR :). The previous runs cancellation is currently triggered for commits in the same branch/PR

**Comment by mathause** [comment]
This catches a numpy-based typing error in the pre-commit hook. So I think we can try this.

**Comment by max-sixty** [comment]
> I take this back... I just realized that #5467 is a different PR :). The previous runs cancellation is currently triggered for commits in the same branch/PR

Ah, sorry for the confusion in that case!

**Comment by max-sixty** [comment]
OK let's try this, merging!

**Pull request merged**
