### PR TITLE
add pyproject.toml

### LINKED ISSUE #4274: Local installation from sources - failing due to version not being parsable
I did the following things:
1. Download latest release tar from github [here](https://github.com/pydata/xarray/releases/tag/v0.16.0)
2. Extracted tar file
3. Ran
```bash
python3 setup.py install --prefix=<>
```
4. Got this error:
```bash
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    setup(use_scm_version=True)
  File "/opt/gnu/9.3.0/python/3.8.3/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/gnu/9.3.0/python/3.8.3/lib/python3.8/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/opt/gnu/9.3.0/python/3.8.3/lib/python3.8/site-packages/setuptools/dist.py", line 445, in __init__
    _Distribution.__init__(self, {
  File "/opt/gnu/9.3.0/python/3.8.3/lib/python3.8/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/opt/gnu/9.3.0/python/3.8.3/lib/python3.8/site-packages/setuptools/dist.py", line 734, in finalize_options
    ep.load()(self, ep.name, value)
  File "/opt/gnu/9.3.0/python/3.8.3/lib/python3.8/site-packages/setuptools_scm/integration.py", line 17, in version_keyword
    dist.metadata.version = _get_version(config)
  File "/opt/gnu/9.3.0/python/3.8.3/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 148, in _get_version
    parsed_version = _do_parse(config)
  File "/opt/gnu/9.3.0/python/3.8.3/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 110, in _do_parse
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for '/home/nicpa/installation/bash-build/.compile/py-3.8/xarray-0.16.0'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```
I think this is because the tar's created by tagging does not contain the version information *anywhere*.
The `setuptools_scm` reads versions according to [this](https://github.com/pypa/setuptools_scm/#builtin-mechanisms-for-obtaining-version-numbers)

As far as I can see, one should create a `PKG-INFO` with this content:
```bash
Version: <version>
```
I then tried this and then it worked. It would be ideal if the release pages have a fully functional installation procedure. This is mainly useful for non-pip installations etc.

### PR DESCRIPTION
**Pull request by keewis**
Along with [`pyproject.toml`](https://snarky.ca/what-the-heck-is-pyproject-toml/), this adds support for [git archives](https://github.com/pydata/xarray/releases) using `setuptools_scm_git_archive`.

This shouldn't be a breaking change since `python setup.py sdist bdist_wheel` still works, but it makes tools that know about it (like `pip`) behave differently.

Edit: do we need a entry to `whats-new.rst`?

- [x] closes #4274
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by max-sixty — APPROVED** [review]

**Comment by max-sixty** [comment]
Looks good, thanks! 

(your call on whatsnew)

**Review by andersy005 — APPROVED** [review]

**Comment by keewis** [comment]
I decided to declare this a breaking change and to remove the `setup_requires` key. This is not too much of a breaking change, though, manually creating the environment and running `python setup.py sdist bdist_wheel` still works.

If there's no objection to this I think this is ready for merging.

**Comment by mathause** [comment]
Should we get that in before the release? (I don't know the format so I can't really review)

**Comment by max-sixty** [comment]
Agreed @mathause . I'll merge now and do the release in the next day or so (I originally planned for this weekend), so if anyone has concerns please say so before then!

**Pull request merged**
