### PR TITLE
Disable workflows on forks

### PR DESCRIPTION
**Pull request by andersy005**
Currently, the CI runs both on a user's fork and `pydata/xarray`. This leads to duplicate runs and the user is flooded with GitHub notifications in case of failures... This PR addresses this issue by making sure the workflows are triggered on `pydata/xarray` only. 

Screen Shot 2021-05-06 at 8 55 24 AM

### CODE REVIEW

**Review by shoyer — APPROVED** [review]
LGTM, assuming this worked properly in this PR itself :)

**Review by keewis — APPROVED** [review]
looks good to me. I thought we did that already (then again, there recently was someone getting an e-mail about failed CI), but I personally disabled all CI runs on the xarray fork (so instead of skipping the CI it is actually never run)

**Comment by andersy005** [comment]
> LGTM, assuming this worked properly in this PR itself :)

I think it's working properly. I'm not seeing new CI runs for this PR in my fork 

> looks good to me. I thought we did that already

As far as I can tell, we did it for the upstream-dev CI only

**Comment by andersy005** [comment]
Thank you both for the feedback! Merging this shortly...

**Pull request merged**
