### PR TITLE
Raise TypeError if plotting empty data

### LINKED ISSUE #7156: Plotting empty DataArray oddly raises ImportError
### What happened?

When calling the `xarray.DataArray.plot()` method on empty DataArrays raises an `ImportError` about a required, but missing, `nc-time-axis` package. This is at least confusing.

### What did you expect to happen?

Either a more appropriate exception (to the effect of "don't try to plot nothing plz"). Or just get an empty plot returned.

### Minimal Complete Verifiable Example

```Python
>>> import xarray as xr
>>> xr.DataArray([])
<xarray.DataArray (dim_0: 0)>
array([], dtype=float64)
Dimensions without coordinates: dim_0
>>> xr.DataArray([]).plot()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "foo/env/lib/python3.9/site-packages/xarray/plot/plot.py", line 866, in __call__
    return plot(self._da, **kwargs)
  File "foo/env/lib/python3.9/site-packages/xarray/plot/plot.py", line 332, in plot
    return plotfunc(darray, **kwargs)
  File "foo/env/lib/python3.9/site-packages/xarray/plot/plot.py", line 438, in line
    _ensure_plottable(xplt_val, yplt_val)
  File "foo/env/lib/python3.9/site-packages/xarray/plot/utils.py", line 648, in _ensure_plottable
    raise ImportError(
ImportError: Plotting of arrays of cftime.datetime objects or arrays indexed by cftime.datetime objects requires the optional `nc-time-axis` (v1.2.0 or later) package.
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

_No response_

### Anything else we need to know?

_No response_

### Environment

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.9.10 (main, Mar 15 2022, 15:56:56) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1160.49.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.0
libnetcdf: 4.7.4

xarray: 0.21.1
pandas: 1.4.0
numpy: 1.21.5
scipy: 1.8.1
netCDF4: 1.5.8
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.5.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.5.1
cartopy: None
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
setuptools: 49.2.1
pip: 22.2.2
conda: None
pytest: 7.1.2
IPython: 8.0.1
sphinx: None
</details>

### PR DESCRIPTION
**Pull request by headtr1ck**
- [x] Closes #7156
- [x] Tests added
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [x] ~New functions/methods are listed in `api.rst`~

### CODE REVIEW

**Review by mathause — APPROVED** [review]
Nice!

**Comment by headtr1ck** [comment]
In the line plot we now have:
```python
    if ndims == 0 or darray.size == 0:
        # TypeError to be consistent with pandas
        raise TypeError("No numeric data to plot.")
    if ndims > 2:
        raise ValueError(
            "Line plots are for 1- or 2-dimensional DataArrays. "
            "Passed DataArray has {ndims} "
            "dimensions".format(ndims=ndims)
        )
```
which looks just wrong, haha.

**Comment by Illviljan** [comment]
> Should we change the error for `ndims > 2` to a TypeError as well? That would be a breaking change (I don't think it would affect many people though...)

I think we should remove it eventually. In #7174 ndims > 2 is allowed as we just stack the extra dimensions.

**Comment by headtr1ck** [comment]
> I think we should remove it eventually. In #7174 ndims > 2 is allowed as we just stack the extra dimensions.

Ok, then lets leave it for now and remove it with #7174

**Pull request merged**
