### PR TITLE
Enforce ruff/flake8-type-checking rules (TCH)

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Review by max-sixty — COMMENTED** [review]
What's the advantage of this?

**Comment by DimitriPapadopoulos** [comment]
These imports will only be imported during type checking, not at run time.

**Comment by max-sixty** [comment]
Yes, though these are very cheap imports.

I'm also cognizant of #9581...

**Comment by DimitriPapadopoulos** [comment]
I was not aware of runtime type checking tools. Perhaps we need to keep the current status quo until we make sure [TCH](https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch) rules do the right thing take into account runtime typecheckers.

Not sure they currently do the right thing, at least by default. From [TCH001](https://docs.astral.sh/ruff/rules/typing-only-first-party-import/):
> Unused imports add a performance overhead at runtime, and risk creating import cycles. If an import is only used in typing-only contexts, it can instead be imported conditionally under an if `TYPE_CHECKING:` block to minimize runtime overhead.
> 
> If [`lint.flake8-type-checking.quote-annotations`](https://docs.astral.sh/ruff/settings/#lint_flake8-type-checking_quote-annotations) is set to `true`, annotations will be wrapped in quotes if doing so would enable the corresponding import to be moved into an if `TYPE_CHECKING:` block.
> 
> If a class requires that type annotations be available at runtime (as is the case for Pydantic, SQLAlchemy, and other libraries), consider using the [`lint.flake8-type-checking.runtime-evaluated-base-classes`](https://docs.astral.sh/ruff/settings/#lint_flake8-type-checking_runtime-evaluated-base-classes) and [`lint.flake8-type-checking.runtime-evaluated-decorators`](https://docs.astral.sh/ruff/settings/#lint_flake8-type-checking_runtime-evaluated-decorators) settings to mark them as such.

**Comment by max-sixty** [comment]
OK, I reckon given the uncertainty & low cost of these imports, let's push this off until the ecosystem has had a chance to coalesce on an option...

**Pull request closed without merging**
