### PR TITLE
Restored dim order in DataArray.rolling().reduce() 

### LINKED ISSUE #1125: DataArrayRolling.reduce changes dimensions order
Seems like a bug.
Code to reproduce:
```
import numpy as np
import xarray as xr
arr = xr.DataArray(np.random.rand(3, 3, 100))
rolled = arr.rolling(dim_2=3)
print(rolled.mean().dims)
print(rolled.reduce(np.mean).dims)
```
Output:
```
('dim_0', 'dim_1', 'dim_2')
('dim_2', 'dim_0', 'dim_1')
```

P.S. Package version:
```
$ pip show xarray
---
Metadata-Version: 2.0
Name: xarray
Version: 0.8.2
Summary: N-D labeled arrays and datasets in Python
Home-page: https://github.com/pydata/xarray
Author: xarray Developers
Author-email: xarray@googlegroups.com
Installer: pip
License: Apache
Location: /usr/lib/python3.5/site-packages
Requires: numpy, pandas
Classifiers:
  Development Status :: 4 - Beta
  License :: OSI Approved :: Apache Software License
  Operating System :: OS Independent
  Intended Audience :: Science/Research
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Topic :: Scientific/Engineering
```

### PR DESCRIPTION
**Pull request by fujiisoup**
- [x] closes #1125 
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew 

Added 1 line to fix #1125.

I hope this is enough.
If another care is necessary, please let me know.

### CODE REVIEW

**Comment by shoyer** [comment]
Looks good to me! Can you please add a bug fix note to the what's new doc?

**Comment by fujiisoup** [comment]
Thanks for reviewing.
I added a few lines to whats-new docs.

**Comment by jhamman** [comment]
@fujiisoup - this looks great. Can you pull in the latest master branch? The Appveyor test should pass after that and we can merge this.

**Comment by fujiisoup** [comment]
Hi @jhamman .
Thanks for the review.
Done and test passes.

**Comment by jhamman** [comment]
Thanks!

**Pull request merged**
