### PR TITLE
Add pyright type checker

### PR DESCRIPTION
**Pull request by Illviljan**
It can be helpful to get a second opinion from another typer checker than mypy. 

The CI activates when the `run-pyright` label is added.

### CODE REVIEW

**Comment by headtr1ck** [comment]
2144 errors, haha.
Most of them are in the tests though.

**Comment by Illviljan** [comment]
pyright indeed checks different things, it's been quite useful to run both. Sometimes they hint the issue in a better way than the other.

**Comment by max-sixty** [comment]
FWIW, I do worry a bit that getting mypy to pass can be difficult enough at times, and if we're in a situation where changing something such that mypy passes and then pyright fails, or vice-versa, could be quite painful. 

But maybe that doesn't happen, and they rarely are opposing. I would be +0.7 on trying this, but with direction that it's OK to ignore things quite liberally if it slows down progress.

For those who find mypy slow, I often run with `dmypy` — e.g. `watchexec -rc -e py -- dmypy run`

**Comment by Illviljan** [comment]
I was thinking it will stay an optional check, at least until pyright passes without errors. Considering there are 2000+ errors I think it'll stay optional for the foreseeable future. 

We'll probably have strict mypy passing before that happens! :D

**Comment by max-sixty** [comment]
> I was thinking it will stay an optional check, at least until pyright passes without errors. Considering there are 2000+ errors I think it'll stay optional for the foreseeable future.

Ah great, perfect!

**Pull request merged**
