### PR TITLE
Examples for quantile

### PR DESCRIPTION
**Pull request by keewis**
Following up to #3527, this adds examples for `DataArray.quantile`, `Dataset.quantile` and `GroupBy.quantile` (which is inherited by both `DatasetGroupBy` and `DataArrayGroupBy`).

 - [x] Passes `black . && mypy . && flake8`

### CODE REVIEW

**Comment by keewis** [comment]
there seems to be something wrong with one of the rasterio tests. Due to a new version of rasterio, maybe?

**Comment by max-sixty** [comment]
These are great! Thanks as ever @keewis !

**Comment by max-sixty** [comment]
Do you want to add to `whatsnew` in Documentation? I hit the green button so would need to be another PR.

**Comment by keewis** [comment]
see #3581.

**Pull request merged**
