### PR TITLE
Add sphinx-gallery to the docs

### PR DESCRIPTION
**Pull request by fmaussion**
- [x] Closes https://github.com/pydata/xarray/issues/1061
 - [ ] Tests added / passed
 - [ ] Passes ``git diff upstream/master | flake8 --diff``
 - [x] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

This uses [sphinx-gallery](http://sphinx-gallery.readthedocs.io) to illustrate some examples of the xarray workflow. See it rendered [here](http://xarray.pydata.org/en/fix-docs/auto_gallery/index.html)

It's nicer for the gallery if there is a plot to draw in the end but it doesn't *have* to be a plot. Once the gallery gets more examples it's possible to sort them by topic (see the sphinx gallery documentation for an overview of the possibilities).

I could think of several other things we could add (including moving or copying @jhamman and @rabernat 's examples to the gallery), but I thought it's better to merge quickly in order to encourage the community to contribute with more examples before the next release.

### CODE REVIEW

**Comment by shoyer** [comment]
This looks great -- but maybe move the "Gallery" section under "Examples"?

**Comment by fmaussion** [comment]
>  maybe move the "Gallery" section under "Examples"?

good idea: done.

**Comment by rabernat** [comment]
Agreed, great idea to use sphinx-gallery. I agree that it's best to get the basic functionality working first. Then we can migrate the other examples to sphinx-gallery once we have a working template.

**Comment by shoyer** [comment]
Thinking about this a little bit more -- maybe we would rather use something like nbsphinx that lets us directly embed ipython notebooks in the docs and/or write notes in the form of notebooks?

sphinx-gallery seems very well suited to an examples that produce a single plot but not much else. Maybe we should put this gallery on the "Plotting" page instead?

Anyways, I'm happy to trust your judgment here. I'm happy to merge now and iterate later.

(Also, I'm not a huge fan of the prominent "Download all" links, they seem mostly like clutter to me -- but that's a side note.)

**Comment by fmaussion** [comment]
I agree with you @shoyer , but it can still provides a little bit more than mere plotting examples. 

How about naming the gallery "Recipes" and keep it in the examples section for now?

**Comment by shoyer** [comment]
> How about naming the gallery "Recipes" and keep it in the examples section for now?

Sounds good to me.

**Pull request merged**
