### PR TITLE
Add unique method

### LINKED ISSUE #2795: Add "unique()" method, mimicking pandas
Would it be good to add a unique() method that mimics pandas?

```
import pandas as pd
import xarray as xr
pd.Series([0, 1, 1, 2]).unique()
xr.DataArray([0, 1, 1, 2]).unique()  # not implemented
```

AttributeError: 'DataArray' object has no attribute 'unique'

### PR DESCRIPTION
**Pull request by ahuang11**
- [x] Closes #2795
- [x] Tests added
- [x] Passes `pre-commit run --all-files`
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [x] New functions/methods are listed in `api.rst`

### CODE REVIEW

**Comment by max-sixty** [comment]
What are people's thoughts?

We don't have precedent for methods that return a numpy array. But it's unclear what xarray object this would return.

**Comment by rhkleijn** [comment]
> We don't have precedent for methods that return a numpy array. But it's unclear what xarray object this would return.

There is a precedent in xarray:

```
In [2]: xr.DataArray([1,2,3,4,5]).searchsorted([-10, 10, 2, 3])
Out[2]: array([0, 5, 1, 2])
```

**Comment by shoyer** [comment]
> > We don't have precedent for methods that return a numpy array. But it's unclear what xarray object this would return.
> 
> There is a precedent in xarray (it might be the only one):
> 
> ```
> In [2]: xr.DataArray([1,2,3,4,5]).searchsorted([-10, 10, 2, 3])
> Out[2]: array([0, 5, 1, 2])
> ```

I think `searchsorted` was probably a mistake from the very early days of Xarray.

I would lean against adding `unique`. These functions are very short to write (and thus easy to reproduce in user code), so it's not clear that the cost/benefit is worth it.

**Comment by ahuang11** [comment]
What if we added coordinates/dims to it and it returns a stacked dimension if multiple dims?
```
def unique(da):
    da_stack = da.stack({'tmp_dim': da.dims})
    _, index = np.unique(da_stack.values, return_index=True)
    return da_stack.isel({'tmp_dim': index})

da = xr.DataArray([[[0, 1, 1], [2, 3, 4], [4, 5, 6]], [[7, 8, 9], [10, 11, 12], [13, 14, 15]]],
                  coords={'lat': [0, 1, 2], 'lon': [4, 5, 6], 'time': [7, 8]}, dims=['time', 'lat', 'lon'])
unique(da)  # would be da.unique()
```
image

Then users can use `da.unique().unstack()` if they like.
image

**Comment by shoyer** [comment]
Let's sort out `drop_duplicates` (https://github.com/pydata/xarray/pull/5089) first. I imagine `unique()` could be a special case of the exact same logic.

**Pull request closed without merging**
