### PR TITLE
Remove broken test for Panel with to_pandas()

### PR DESCRIPTION
**Pull request by shoyer**
We don't support creating a Panel with to_pandas() with *any* version of
pandas at present, so this test was previous broken if pandas < 0.25 was
installed.

### CODE REVIEW

**Comment by dcherian** [comment]
`LooseVersion` needs to be removed from `test_dataset.py` but readded to `test_dataarray.py`

**Comment by shoyer** [comment]
It seems that our doc build is timing out...

**Comment by dcherian** [comment]
There is an error unrelated to this PR
```
Sphinx parallel build error:
RuntimeError: Non Expected warning in `/home/vsts/work/1/s/doc/plotting.rst` line 732
```

**Comment by shoyer** [comment]
It looks like it had trouble downloading data from Natural Earth:
```
/usr/share/miniconda/envs/xarray-tests/lib/python3.8/site-packages/cartopy/io/__init__.py:260: DownloadWarning: Downloading: https://naciscdn.org/naturalearth/110m/physical/ne_110m_coastline.zip
```

I'll try re-running.

**Pull request merged**
