### PR TITLE
Xfail failing test

### PR DESCRIPTION
**Pull request by max-sixty**
As per https://github.com/pydata/xarray/issues/6209#issuecomment-1025116203

### CODE REVIEW

**Comment by keewis** [comment]
makes sense, feel free to merge as soon as the CI is green. That way, we avoid having the CI fail in other PRs (this is not just a upstream-dev issue anymore)

**Comment by mathause** [comment]
Can I suggest you xfail in 

https://github.com/pydata/xarray/blob/5470d933452d88deb17cc9294a164c4a03f55dec/xarray/tests/test_variable.py#L2105

(sorry, could have done this myself...)

**Comment by max-sixty** [comment]
> Can I suggest you xfail in

No prob, you do lots!

**Comment by max-sixty** [comment]
We have another couple of failures though. I'll xfail them but please could someone who knows the dask interface better check them out and assess if we should raise them on the dask repo?

**Comment by mathause** [comment]
I haven't seen them fail before - were they just flaky?

**Comment by max-sixty** [comment]
> I haven't seen them fail before - were they just flaky?

More than a one-off — I got them multiple times. Though they look like tests that are liable to be flaky...

**Comment by max-sixty** [comment]
RTD is being slow, but I'll merge regardless so we can return to green

**Comment by crusaderky** [comment]
> More than a one-off — I got them multiple times. Though they look like tests that are liable to be flaky...

They are both tests that fail on the cleanup of ``@gen_cluster``, and specifically on ``check_process_leak``.
However, in both cases, the test itself doesn't spawn any processes. What I think is happening is that something unrelated, at some point *before* the failing tests, spawned a subprocess that has become unresponsive to SIGTERM.
I'm updating ``check_process_leak`` to be more aggressive in the cleanup before the test.

**Pull request merged**
