### PR TITLE
One-off isort run

### PR DESCRIPTION
**Pull request by crusaderky**
A one-off, manually vetted and tweaked isort run

### CODE REVIEW

**Comment by crusaderky** [comment]
Ready for review and merge

**Comment by max-sixty** [comment]
I was thinking about doing this (and had done it a couple of times in the past). My only concern with doing it now is whether it's likely to exacerbate any merge conflicts from the black changes. I've found that merge conflicts scale super-linearly with changes, at least in frustration if not lines - if so potentially we could wait for the outstanding PRs to update and then rerun?

**Comment by crusaderky** [comment]
Fine for me - is a week enough to allow everybody to adapt?

**Comment by crusaderky** [comment]
Updated, re-run everything, and removed the blanket F401 (unused import) suppression.
Ready for final review and merge.

**Pull request merged**
