### PR TITLE
run CI on `python=3.12`

### LINKED ISSUE #8580: add py3.12 CI and update pyproject.toml
### What is your issue?

We haven't done this yet!
https://github.com/pydata/xarray/blob/d87ba61c957fc3af77251ca6db0f6bccca1acb82/pyproject.toml#L11-L15

### PR DESCRIPTION
**Pull request by keewis**
- [x] Closes #8580

### CODE REVIEW

**Comment by keewis** [comment]
@Illviljan, it appears on `python=3.12` the trick with `_arrayfunction` does not work for `pint` anymore:
```python
from xarray.namedarray._typing import _arrayfunction
import pint

ureg = pint.UnitRegistry()
q = ureg.Quantity([0, 1, 2], "m")
isinstance(q, _arrayfunction)  # True on `python < 3.12`, False on `python=3.12`
```

I assume this is part of the performance improvements in [this section](https://docs.python.org/3.12/whatsnew/3.12.html#typing)? Do you have any idea what we have to do to fix this (here or in `pint`)?

**Comment by keewis** [comment]
as it turns out, all of the above is wrong: `Quantity.dtype` is only available through the `__getattr__` fallback, explicitly defining it as a property makes the check work again. I'll put in a PR to fix this in `pint`, but in the meantime we need to figure out how to deal with this, as it causes a number of our tests to fail.

**Comment by Illviljan** [comment]
Was the dtype fix in pint enough to solve all the errors, @keewis?

I didn't go through all the errors but a few seems to be due to triggering a reduction like `.mean`, which ends up in `.reduce` which then ends up in `from_array`:
https://github.com/pydata/xarray/blob/d20ba0d387d206a21d878eaf25c8b3392f2453d5/xarray/namedarray/core.py#L800

Because `NamedArray.data` _should_ always be the same duckarray type (numpy, dask, etc) regardless of the operation, I'd argue the safety checks done in `from_array` is redundant and should be replaced with `self._new` instead.

That's my high level point of view at least...

I've been looking into `.reduce` before and the problem if I remember correctly is that you somehow can get `ArrayLike` values out of the reductions. I have some draft code how to clean `.reduce` up in #8344, but that one still had `from_array` unfortunately.

**Comment by keewis** [comment]
yes, that was enough to fix every issue (at least on my machine, not entirely sure about windows / macos). To unblock this we decided in the meeting today to remove `pint` from the 3.12 environment until there's at least one released version that does not cause the tests to fail.

> Because NamedArray.data should always be the same duckarray type (numpy, dask, etc) regardless of the operation, I'd argue the safety checks done in from_array is redundant and should be replaced with self._new instead.

We need to be careful about removing runtime checks, as this can easily become unsafe – though if we can ensure for normal usage that we don't work on data that has never been checked I would agree, checking more than once is not necessary. As an example for when this can go wrong, `xr.namedarray.core.NamedArray("x", range(10))` currently raises an `AttributeError` because `range` objects don't have the `shape` attribute (I've been meaning to open an issue for this, but didn't get around to it until now).

**Comment by dcherian** [comment]
> Because NamedArray.data should always be the same duckarray type (numpy, dask, etc) regardless of the operation

Unfortunately not true for our lazy indexing wrappers.

**Review by TomNicholas — APPROVED** [review]

**Comment by Illviljan** [comment]
> We need to be careful about removing runtime checks, as this can easily become unsafe – though if we can ensure for normal usage that we don't work on data that has never been checked I would agree, checking more than once is not necessary. As an example for when this can go wrong, `xr.namedarray.core.NamedArray("x", range(10))` currently raises an `AttributeError` because `range` objects don't have the `shape` attribute (I've been meaning to open an issue for this, but didn't get around to it until now).

My point of view here is technically NamedArray hasn't 'removed' any runtime checks as it's not public yet. Now NamedArray has a performant initialization with the promise that the user inputs a valid array function or array api. If the user is uncertain about the data, then use the slower `from_array` / `asarray` functions. `Cubed` uses this approach which I think was the correct decision. This was discussed a bit in #8294.

`Variable` and `DataArray` both suffers performance from the overuse of `as_compatible_data` in the init, which is hard for the user to avoid.

> > Because NamedArray.data should always be the same duckarray type (numpy, dask, etc) regardless of the operation
> 
> Unfortunately not true for our lazy indexing wrappers.
> 
> EDIT: I guess those live in `_data`

The lazy wrappers needs more love to be considered array_functions/array_api is what I'm reading! 
But the necessary tweaks to keep them working can still be on the Variable level, which I think it mostly is right now.

**Comment by keewis** [comment]
> My point of view here is technically NamedArray hasn't 'removed' any runtime checks as it's not public yet.

As long as that was a intentional decision with runtime usage in mind I'm fine with the current state.

**Pull request merged**
