### PR TITLE
Filter out doctest warning

### LINKED ISSUE #8537: Doctests failing
### What is your issue?

The doctest is currently failing with
> E   UserWarning: h5py is running against HDF5 1.14.3 when it was built against 1.14.2, this may cause problems

### PR DESCRIPTION
**Pull request by max-sixty**
Trying to fix #8537. Not sure it'll work and can't test locally so seeing if it passes CI

### CODE REVIEW

**Comment by max-sixty** [comment]
No luck. Possibly we could add a filter in an `autouse` fixture for the doctests? Or just skip that test?

**Comment by keewis** [comment]
I think the issue is that the warning is emitted on test collection time (when executing one of the `conftest.py` files), so the `filterwarnings` does not apply there. It also does not appear to be possible to apply a mark to all `doctest` tests.

So I guess the only option we have is using the CLI:
```sh
pytest --doctest-modules xarray --ignore xarray/tests -Werror -W "ignore:h5py is running against HDF5 1.14.3:UserWarning"
```

**Comment by kmuehlbauer** [comment]
Seems to be pinning problem over at conda-forge: https://github.com/conda-forge/h5py-feedstock/issues/122 (see latest comments there).

**Comment by keewis** [comment]
> Seems to be pinning problem over at conda-forge: [conda-forge/h5py-feedstock#122](https://github.com/conda-forge/h5py-feedstock/issues/122) (see latest comments there).

As expected. For now, I've added a ignore to the CLI (as mentioned above, we're using `-Werror`, so the warning from `conftest.py` cannot be ignored using `pytest`'s `filterwarnings` setting), but we'll have to come up with a strategy for future cases.

**Comment by headtr1ck** [comment]
Did you try adding it to `xarray/tests/__init__.py`? There are already a few ignores.

**Comment by max-sixty** [comment]
> For now, I've added a ignore to the CLI, but we'll have to come up with a strategy for future cases.

Thanks! Closing



> Did you try adding it to `xarray/tests/__init__.py`? There are already a few ignores.

Good point — maybe we can do it at import time. (though not that different from adding to CLI I guess, since the only time it errors is with our CLI arguments that convert warnings to errors — which I think is great overall)

**Comment by keewis** [comment]
> Did you try adding it to `xarray/tests/__init__.py`? There are already a few ignores.

no, I totally missed that. I agree with @max-sixty though that having the ignore in the same place as where we enable raising warnings is a good property, especially since it then will not be ignored in the tests (although right now that's not so useful since we have hundreds if not thousands of warnings).

>> For now, I've added a ignore to the CLI
>
> Thanks! Closing

what I meant was that I modified this PR, so we'd still have to merge it.

**Comment by max-sixty** [comment]
> having the ignore in the same place as where we enable raising warnings is a good property, especially since it then will not be ignored in the tests (although right now that's not so useful since we have hundreds if not thousands of warnings). So we might want to migrate those warnings that should only be ignored in `doctest`?

I would say it depends on "do we want to oversee the warnings"?
- for warnings that are temporary and we know we can always ignore (`'urllib3.contrib.pyopenssl' module is deprecated`, as an example), putting it in the `__init__` means we don't have to litter the tests with their ignores. That's often the case with warnings from dependencies, and almost always the case with dependencies of dependencies, where we don't have control.
- and then for more specific warnings — those in xarray, and those in some close dependencies, it makes sense to have them next to the tests, where we want to oversee them

...probably both of those are better than the CLI. Though I'm not sure the `__init__` covers the doctests, does `xarray.tests.__init__` get run before doctest collections?

**Comment by keewis** [comment]
> does `xarray.tests.__init__` get run before doctest collections?

Yes, because we import it in `xarray/tests/conftest.py`

**Comment by max-sixty** [comment]
> Either way, we definitely need to point out why we ignore a certain warning (in general a link to the issue / PR with a short explanation should be enough), and maybe also list criteria that allow removing them?

Agree!

> I'd argue that we should ignore warnings that are emitted by imports in `xarray.tests`, and anything else should be ignored in the tests (unless way too many tests would emit these, in which case it might make sense to also do so in `xarray.tests`).

I agree with the direction. Though I would put the bar for "way too many tests would emit these" quite low for things we can't control, or that don't show up at runtime (e.g. `PendingDeprecationWarning`)

In particular, if it means that we silence more of the warnings, that's great — our test suite is hardly too restrictive about showing warnings which we can't do anything about atm...

**Pull request merged**
