### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by keewis**
As requested in https://github.com/pydata/xarray/issues/5232#issuecomment-831956692, this bumps the dependencies. There's a warning for `netcdf4`: it uses the `1.major.minor` scheme, so we pinned it to `1.5.3` due to #4491. To remove that warning (and get automatic notifications for `netcdf4` again) we'll have to update the `min_deps_check` script.

- [x] Passes `pre-commit run --all-files`
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by dcherian** [comment]
Thanks @keewis !

Could delete 
https://github.com/pydata/xarray/blob/f455e00f0228c30423123c089227d7a8fd4a94b5/xarray/core/dask_array_compat.py#L61-L97

There's also a `@requires_cftime_1_1_0` decorator in the tests that could be cleaned up if you want.

**Comment by keewis** [comment]
done

**Review by dcherian — APPROVED** [review]
Thanks @keewis

**Review by alexamici — APPROVED** [review]
LGTM as well, shall we merge it right away?

**Comment by alexamici** [comment]
@dcherian with dask>=2.15 you can update #4740 that looks mergiable as well, right?

**Comment by dcherian** [comment]
> with dask>=2.15 

It doesn't work on 2.15, I checked; but we can merge anyway

**Pull request merged**
