### PR TITLE
1D line plot with data on both axes + errorbar plotting added

### LINKED ISSUE #575: 1D line plot with data on the x axis
Consider the following Dataset, representing a function f = cos(z)

``` python
z = np.arange(10)
ds = xray.Dataset( {'f': ('z', np.cos(z))}, coords={'z': z})
```

If I call

``` python
ds.f.plot()
```

xray naturally puts "z" on the x-axis.

However, since z represents the vertical dimension, it would be more natural do put it on the y-axis, i.e. 

``` python
plt.plot(ds.f, ds.z)
```

This is conventional in atmospheric science and oceanography for buoy data or balloon data.

Is there an easy way to do this with xray's plotting functions? I scanned the code and didn't see an obvious solution, but maybe I missed it.

### PR DESCRIPTION
**Pull request by kuchaale**
- [ ] Closes #575 
 - [ ] Tests added / passed
 - [ ] Passes ``git diff upstream/master **/*py | flake8 --diff``
 - [ ] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

### CODE REVIEW

**Comment by shoyer** [comment]
I think you're on the right track here, but rather than adding these to the exist `_PlotMethods` object, I think we would need a new dedicated PlotMethods class for use on Dataset instead of DataArray objects. This could probably involve duplicating some of the existing code to setup the `.plot` accessor.

**Comment by kuchaale** [comment]
[#1285](https://github.com/mwaskom/seaborn/pull/1285)

**Comment by kuchaale** [comment]
https://github.com/mwaskom/seaborn/pull/#1285

**Comment by kuchaale** [comment]
mwaskom/seaborn/#1285

**Comment by kuchaale** [comment]
mwaskom/seaborn#1285

**Pull request closed without merging**
