### PR TITLE
Switch py2.7 CI build to use conda-forge

### PR DESCRIPTION
**Pull request by shoyer**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@shoyer I am interested in help you investigate what is going on here as that will help us to keep the conda-forge stable. Can you please add `conda config --set show_channel_urls true` in the `.travis.yml` so we know where the packages are coming from? We just added scipy and I am afraid that might be the issue here.

**Comment by shoyer** [comment]
@ocefpaf looks like the previous build failed due to a lack of the "coveralls" package... just switched that back to pip, we'll see how that it goes.

**Comment by shoyer** [comment]
@ocefpaf Looks like it's the official *Continuum* build of SciPy that just started failing here (entirely coincidentally). I only switched to conda forge for our build with all optional dependencies `py27-cdat+pynio`. So I'm going to merge this for now and fix the minimal build later.

**Comment by jakirkham** [comment]
Please let me know if there is something actionable for me here. Looks like that is not the case. If that changes, please let me know.

**Comment by jakirkham** [comment]
Also, FYI we have `python-coveralls` currently. Though we don't have `coveralls` yet.

**Comment by ocefpaf** [comment]
> @ocefpaf Looks like it's the official Continuum build of SciPy that just started failing here (entirely coincidentally). I only switched to conda forge for our build with all optional dependencies py27-cdat+pynio. So I'm going to merge this for now and fix the minimal build later.

Cool. I will take a look at adding coveralls once I get back in office. (Heading to PyCon. Will you be there @shoyer?)

**Comment by shoyer** [comment]
I just tried switching our other Python 2.7 build to use conda-forge and am still seeing the same issues with scipy:
https://github.com/pydata/xarray/pull/863

I'll try adding show_channels_urls to that build and we'll see what it reports.

@ocefpaf I'm not making it to PyCon (or scipy!) this year, but I hope you enjoy it. Portland is a great city!

**Pull request merged**
