### PR TITLE
Add Pyproject pre-commit hooks

### PR DESCRIPTION
**Pull request by VeckoTheGecko**
- [x] Closes None (see https://github.com/pydata/xarray/pull/9781#discussion_r1845444677)

Changes:
- add taplo (toml formatting) hook
- add `validate-pyproject` hook

Heyo! Looks like Taplo (https://github.com/tamasfe/taplo) would be a good option (same project as VScode extension [Even Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) with 2.3M downloads) . They don't have an official hook (https://github.com/tamasfe/taplo/issues/535) but there's an unofficial one at https://github.com/ComPWA/taplo-pre-commit. I don't think they'll get an official one soon as they would need to set up a mirror repo (and best to transfer both repos to an org for that).

### CODE REVIEW

**Comment by VeckoTheGecko** [comment]
a72decf was because taplo defaults to `align_comments=true` (which is nice for the `tool.ruff.lint.extend-select` block, but means that once off inline comments aren't as nice).

See [formatter options](https://taplo.tamasfe.dev/configuration/formatter-options.html) for more.

Keeping with the default due to the smaller diff

**Comment by max-sixty** [comment]
I'm up for merging ... _unless_ we decide to go with prettier, which covers all of these. 

I've had a good experience with prettier, because it's a single file manages the formatting for all these formats where we only have a few files. A long track record over at PRQL.

But no particularly strong preference...

**Comment by VeckoTheGecko** [comment]
We already have prettier in precommit, and prettier doesn't support TOML (https://prettier.io/docs/en/). Unless you mean via a prettier plugin like https://www.npmjs.com/package/prettier-plugin-toml, but that is just a wrapper for taplo

**Comment by keewis** [comment]
:+1: for `taplo`, as prettier plugins are not upgraded by `pre-commit autoupdate` (I think?). I'd probably add `validate-pyproject` together with it, though.

**Comment by max-sixty** [comment]
Ah, thanks, definitely +1 to this, then

**Comment by VeckoTheGecko** [comment]
> I'd probably add `validate-pyproject` together with it, though.

Done

**Review by headtr1ck — APPROVED** [review]

**Comment by max-sixty** [comment]
Thanks @VeckoTheGecko !

**Pull request merged**
