### PR TITLE
remove all inplace parameters from the public API

### LINKED ISSUE #3586: Update documentation to reflect removal of inplace option
#### MCVE Code Sample

```python
# Your code here
ds_gamma.reset_coords('month', drop=True, inplace=True)

~/miniconda3/envs/spi_multi/lib/python3.8/site-packages/xarray/core/utils.py in _check_inplace(inplace)
     38 def _check_inplace(inplace: Optional[bool]) -> None:
     39     if inplace is not None:
---> 40         raise TypeError(
     41             "The `inplace` argument has been removed from xarray. "
     42             "You can achieve an identical effect with python's standard assignment."

TypeError: The `inplace` argument has been removed from xarray. You can achieve an identical effect with python's standard assignment.
```

#### Expected Output
Coordinates reset in-place, or documentation that does not list `inplace` as a valid argument.

#### Problem Description

The documentation for [`Dataset.reset_coords`](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.reset_coords.html) and [`Dataset.reset_coords`](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.reset_coords.html) lists an inplace argument that is no longer supported. My assumption is that this should be removed from the documentation but I'm not sure how this documentation is generated -- it may come from the docstring and/or function signature and the argument is still present in the function signature so it shows up in the documentation as a result?

This appears to have been addressed before in issue #858 but maybe the inplace argument slipped back into the documentation somehow? I see that there is a [function](https://github.com/pydata/xarray/blob/master/xarray/core/utils.py#L38) to check for an inplace argument and raise an error if present -- why is this being used rather than removing the inplace argument altogether? Is this mechanism in place to facilitate backward compatibility, etc.?

#### Output of ``xr.show_versions()``
<details>
# Paste the output here xr.show_versions() here
INSTALLED VERSIONS
------------------
commit: None
python: 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:38) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.15.0-70-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.7.1

xarray: 0.14.1
pandas: 0.25.3
numpy: 1.17.3
scipy: 1.3.2
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.0.4.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.8.1
distributed: 2.8.1
matplotlib: 3.1.2
cartopy: None
seaborn: None
numbagg: None
setuptools: 42.0.1.post20191125
pip: 19.3.1
conda: None
pytest: None
IPython: 7.10.0
sphinx: None
</details>

### PR DESCRIPTION
**Pull request by keewis**
As in #4561 this has been around for about 3 major versions. Not sure if it's too soon to remove it altogether, but I guess if we decide it is we can just wait with the merge until it is not.

 - [x] Closes #3586
 - [x] Passes `isort . && black . && mypy . && flake8`

### CODE REVIEW

**Comment by max-sixty** [comment]
Excellent! Do we want to wait for 0.17 though?

**Comment by keewis** [comment]
should we merge this now that `0.16.2` has been released?

**Comment by max-sixty** [comment]
Yes I think that makes sense — the next can be 0.17.0. There's some value to not leaving these unmerged given future conflicts.

**Comment by dcherian** [comment]
Works for me

**Comment by max-sixty** [comment]
Should we add the breaking change to whatsnew?

**Comment by keewis** [comment]
I'm not sure we should call this a breaking change, the `inplace` parameter was removed some time ago. With this, we just changed the error message.

**Pull request merged**
