### PR TITLE
move scalar-handling logic into `possibly_convert_objects`

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
This seems an undisputed change up to now if we count @spencerkclark in who suggested that change in #9618. Getting this in soon.

**Review by spencerkclark — APPROVED** [review]
Thanks @kmuehlbauer, yes, I'm on board with this update.  Sorry for being a bit absent from the discussion over the last few weeks.  I should be able to catch up on reviewing the bigger stuff over the holidays.  I appreciate you splitting things off into smaller PRs!

**Comment by kmuehlbauer** [comment]
Thanks @spencerkclark and no worries!

**Comment by kmuehlbauer** [comment]
Mypy errors are unrelated, getting this in now.

**Pull request merged**
