### PR TITLE
allow other and drop arguments in where (gh#6466)

### LINKED ISSUE #6466: drop and other shouldn't be mutually exclusive in DataWithCoords.where
### Is your feature request related to a problem?

[`xr.Dataset.where` and `xr.DataArray.where`](https://github.com/pydata/xarray/blob/main/xarray/core/common.py#L1200) currently do not allow providing both *`other`* and *`drop=True`*, stating that they are mutually exclusive. Conceptually, this doesn't strike me as true. Drop does not drop *all* points where *`cond`* is False, only those where an entire coordinate label evaluates to False. This is most important when trying to avoid type promotion, such as in the below example, where an integer FillValue might be preferred over `dtypes.NA`.

```python
In [2]: da = xr.DataArray(np.arange(16).reshape(4, 4), dims=['x', 'y'])

In [3]: da
Out[3]:
<xarray.DataArray (x: 4, y: 4)>
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
Dimensions without coordinates: x, y
```
If *`other`* is not provided, the array is promoted to `float64` to accommodate the default,`dtypes.NA`:
```python
In [4]: da.where(da > 6, drop=True)
Out[4]:
<xarray.DataArray (x: 3, y: 4)>
array([[nan, nan, nan,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])
Dimensions without coordinates: x, y
```
However, the combination of *`other`* and *`drop=True`* is not allowed:
```python
In [5]: da.where(da > 6, -1, drop=True)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [5], in <module>
----> 1 da.where(da > 6, -1, drop=True)

File ~/miniconda3/envs/rhodium-env/lib/python3.10/site-packages/xarray/core/common.py:1268, in DataWithCoords.where(self, cond, other, drop)
   1266 if drop:
   1267     if other is not dtypes.NA:
-> 1268         raise ValueError("cannot set `other` if drop=True")
   1270     if not isinstance(cond, (Dataset, DataArray)):
   1271         raise TypeError(
   1272             f"cond argument is {cond!r} but must be a {Dataset!r} or {DataArray!r}"
   1273         )

ValueError: cannot set `other` if drop=True
```

## Current implementation

The current behavior is enforced within the block handling the `drop` argument (currently https://github.com/pydata/xarray/blob/main/xarray/core/common.py#L1266-L1268):

```python
        if drop:
            if other is not dtypes.NA:
                raise ValueError("cannot set `other` if drop=True")
```

## Proposed fix

I just removed the above if statement on a fork, and the example now works!

```python
>>> import xarray as xr, numpy as np
>>> da = xr.DataArray(np.arange(16).reshape(4, 4), dims=['x', 'y'])
>>> da
<xarray.DataArray (x: 4, y: 4)>
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
Dimensions without coordinates: x, y
>>> da.where(da > 6, drop=True)
<xarray.DataArray (x: 3, y: 4)>
array([[nan, nan, nan,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])
Dimensions without coordinates: x, y
>>> da.where(da > 6, -1, drop=True)
<xarray.DataArray (x: 3, y: 4)>
array([[-1, -1, -1,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
Dimensions without coordinates: x, y
```
Making this change fails a single test in https://github.com/pydata/xarray/blob/main/xarray/tests/test_dataset.py#L4548-L4549, which explicitly checks for this behavior:

```python
        with pytest.raises(ValueError, match=r"cannot set"):
            ds.where(ds > 1, other=0, drop=True)
```
This could easily be reworked to check for valid handling of both arguments.

### Describe alternatives you've considered

_No response_

### Additional context

I haven't yet investigated what would happen with chunked, sparse, or other complex arrays, or if it's compatible with trees and other things on the roadmap. It's possible this breaks things I'm not imagining. Currently, `where(cond, other)` and `where(cond, drop=True)` are well-tested, flexible operations, and I don't see why allowing their union would break anything, but I'll wait to hear from the experts on that front!

I'm definitely open to creating a pull request (and have the simple implementation I've outlined here ready to go).

### PR DESCRIPTION
**Pull request by delgadom**
- [x] Closes #6466
- [x] Tests added
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst` - not sure if this is warranted or if it should go in new features or bug fixes. happy to change/remove.

### CODE REVIEW

**Comment by max-sixty** [comment]
Thanks @delgadom ! 

I think this is a good idea! Any thoughts?

Note @delgadom 's thoughtful comment in the issue:
> I haven't yet investigated what would happen with chunked, sparse, or other complex arrays, or if it's compatible with trees and other things on the roadmap. It's possible this breaks things I'm not imagining. Currently, `where(cond, other)` and `where(cond, drop=True)` are well-tested, flexible operations, and I don't see why allowing their union would break anything, but I'll wait to hear from the experts on that front!

**Comment by delgadom** [comment]
thanks @max-sixty! I was mostly trying to be overly-cautious because the ValueError was so clearly raised intentionally, and I can't figure out why it was necessary. But maybe it was just left over from a time when providing both arguments really would have caused a problem, and it's no longer the case.

**Comment by delgadom** [comment]
hmm. readthedocs failed because of concurrency limits (my bad) but seems to have failed to automatically retry. can someone give it a nudge?

**Comment by max-sixty** [comment]
> hmm. readthedocs failed because of concurrency limits (my bad) but seems to have failed to automatically retry. can someone give it a nudge?

Hmmm, I haven't seen this before, maybe it's a change, maybe it's a fluke. I hit the button, let's see if it resolves.

**Comment by max-sixty** [comment]
I'm merging this and fixing the `whatsnew` on L39 in a different PR.

Not a great CI run the past few days!

**Comment by max-sixty** [comment]
Thank you @delgadom !!

**Pull request merged**
