### PR TITLE
Optimize some copying

### LINKED ISSUE #7181: xarray 2022.10.0 much slower then 2022.6.0
### What is your issue?

[xbout](https://github.com/boutproject/xBOUT)'s test suite finishes with 2022.6.0 in less than an our, with 2022.10.0 it gets aborted after 6 hours.

I haven't managed to debug what is the issue.

Git bisect will not work, as 2022.9.0 is broken due to #7111

### PR DESCRIPTION
**Pull request by headtr1ck**
- [x] Potentially closes #7181
- [x] Tests added
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

I have passed along some more memo dicts, which could prevent some double deep-copying of the same data (don't know how exactly, but who knows :P)
Also, I have found some copy calls that did not pass along the deep argument (I am not sure if that breaks things, lets find out).
And finally I have found some places where shallow copies are enough.

All together it should improve the performance a lot when copying things around.

### CODE REVIEW

**Comment by dcherian** [comment]
Thanks @headtr1ck do we have a benchmark for this, if not can we add one please?

**Comment by headtr1ck** [comment]
> Thanks @headtr1ck do we have a benchmark for this, if not can we add one please?

Since the benchmark didn't change we either don't have one or my change doesn't matter much, haha.

I think the most important change is the shallow copy for `Variable.to_index_variable`, but I will have to check how to test this in a useful way, probably better testing some functions that use it indirectly.

**Comment by dschwoerer** [comment]
The change does matter - but deep copies are still much more expensive than they used to be (as to be expected, I guess)

**Comment by headtr1ck** [comment]
> The change does matter - but deep copies are still much more expensive than they used to be (as to be expected, I guess)

Do you by any chance know which parts have improved, so we can add them as a benchmark here?

**Comment by headtr1ck** [comment]
I added a benchmark for `swap_dims` which uses `Variable.to_index_variable` when swapping into an existing coord, but I can not see any significant improvement... Any ideas what else to test?

**Comment by benbovy** [comment]
The change in `Variable.to_index_variable` seems sensible (not sure when one wants a deep copy of an `IndexVariable` or an Xarray / Pandas index).

`to_index_variable` may be called in some core functions of Xarray internals (e.g., in `as_variable()`) so it might be tricky to benchmark its effect Xarray-wise. Perhaps it would be good to track it down in the original issue #7181?

**Comment by headtr1ck** [comment]
Are we merging this anyway, or should we try harder to find a benchmark that shows some improvement?

**Comment by dcherian** [comment]
I don't think we need a benchmark to merge. Sorry that wasn't clear, it mostly for information purposes.

> The change in Variable.to_index_variable seems sensible (not sure when one wants a deep copy of an IndexVariable or an Xarray / Pandas index).

Great! let's merge

**Pull request merged**
