### PR TITLE
Modify code in "Grouped arithmetic"

### PR DESCRIPTION
**Pull request by hoseinmadadi**
`results.append(group - alt.sel(x=label))` must be changed to:
`results.append(group - alt.sel(letters=label))`

### CODE REVIEW

**Comment by max-sixty** [comment]
Thanks @hoseinmadadi , good spot.

Want to add to `whatsnew` and give yourself credit?

**Comment by hoseinmadadi** [comment]
@max-sixty, yes thanks, It will be my honor :)

**Comment by max-sixty** [comment]
Great, ping when added and tests pass, thanks!

**Comment by max-sixty** [comment]
@hoseinmadadi do you want to add a line to the whatsnew file?

**Comment by shoyer** [comment]
Let's just merge. I would also encourage contributors to give themselves credit, but in this case that's almost more of a burden than the fix itself :)

@hoseinmadadi thanks for the fix here! if you want to add a credit to yourself in whatsnew in a later PR, feel free!

**Pull request merged**
