### PR TITLE
Expose use_cftime option in open_zarr #2886

### LINKED ISSUE #2886: Expose use_cftime option in open_zarr
`use_cftime` was recently added as an option to `decode_cf` and `open_dataset` to give users a little more control over how times are decoded (#2759).  It would be good if it was also available for `open_zarr`.  This perhaps doesn't have quite the importance, because `open_zarr` only works for single data stores, so there is no risk of decoding times to different types (e.g. as there was for `open_mfdataset`, #1263); however, it would still be nice to be able to silence serialization warnings that result from decoding times to cftime objects in some instances, e.g. #2754.

### PR DESCRIPTION
**Pull request by Geektrovert**
- [x] Closes #2886 
 - [x] Tests added
 - [x] Passes `black . && mypy . && flake8`

### CODE REVIEW

**Comment by andersy005** [comment]
@Geektrovert, thank you for working on this! I added rebase your fork to upstream master and added some tests locally. Do you mind giving me permissions so that I can push to your folk so as to bring this PR to completion?

**Comment by Geektrovert** [comment]
@andersy005 sure! I will add you as a collaborator to my fork. Thank you for working on this!

**Review by dcherian — APPROVED** [review]
LGTM. This just needs a `whats-new` entry

**Comment by andersy005** [comment]
> LGTM. This just needs a `whats-new` entry

Done! I don't know why the readthedocs build failed though

**Comment by keewis** [comment]
this seems to be a general issue with RTD (there are quite a few open issues about this already) and has to be fixed by them.

**Comment by dcherian** [comment]
Thanks @Geektrovert & @andersy005. This is a great improvement.

@Geektrovert I see this is your first PR. Thanks! and welcome to xarray.

**Pull request merged**
