### PR TITLE
Add type checking when concat

### LINKED ISSUE #5051: Error message when trying to concatenate DataSet and DataArray
I come from the conversation [5047](https://github.com/pydata/xarray/discussions/5047). There is a misleading error when trying to concatenate a DataArray and a DataSet:

**What you expected to happen**:
Have an error that give you a hint about the wrong type

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import xarray as xr

dataset = xr.Dataset(
    {"measurements": (("simulation", "characteristic", "value"), np.random.random((10,3,6)))},
    coords={"characteristic": ['a', 'b', 'c']})

logged = np.log(dataset["measurements"].sel(characteristic=["b", "c"]))
logged = logged.assign_coords(characteristic=["log_b", "log_c"])

xr.concat([dataset, logged], dim="characteristic")
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-8df5bd650bd4> in <module>
     10 logged = logged.assign_coords(characteristic=["log_b", "log_c"])
     11 
---> 12 xr.concat([dataset, logged], dim="characteristic")

C:\ProgramData\Anaconda3\lib\site-packages\xarray\core\concat.py in concat(objs, dim, data_vars, coords, compat, positions, fill_value, join, combine_attrs)
    237             "objects, got %s" % type(first_obj)
    238         )
--> 239     return f(
    240         objs, dim, data_vars, coords, compat, positions, fill_value, join, combine_attrs
    241     )

C:\ProgramData\Anaconda3\lib\site-packages\xarray\core\concat.py in _dataset_concat(datasets, dim, data_vars, coords, compat, positions, fill_value, join, combine_attrs)
    433     )
    434 
--> 435     dim_coords, dims_sizes, coord_names, data_names = _parse_datasets(datasets)
    436     dim_names = set(dim_coords)
    437     unlabeled_dims = dim_names - coord_names

C:\ProgramData\Anaconda3\lib\site-packages\xarray\core\concat.py in _parse_datasets(datasets)
    394 
    395     for ds in datasets:
--> 396         dims_sizes.update(ds.dims)
    397         all_coord_names.update(ds.coords)
    398         data_vars.update(ds.data_vars)

ValueError: dictionary update sequence element #0 has length 10; 2 is required
```

**Anything else we need to know?**:
For the previous code to be working, it is needed to write `dataset[["measurements"]]`

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: None
LOCALE: fr_FR.cp1252
libhdf5: 1.10.4
libnetcdf: None

xarray: 0.17.0
pandas: 1.2.3
numpy: 1.19.2
scipy: 1.6.1
netCDF4: None
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2021.02.0
distributed: 2021.03.0
matplotlib: 3.3.4
cartopy: None
seaborn: 0.11.1
numbagg: None
pint: None
setuptools: 52.0.0.post20210125
pip: 21.0.1
conda: 4.9.2
pytest: 6.2.2
IPython: 7.21.0
sphinx: 3.5.1

</details>

### PR DESCRIPTION
**Pull request by thomashirtz**
Pull related to the issue [5051](https://github.com/pydata/xarray/issues/5051)
(I was not so sure about the Error message, please check if it is acceptable)

- [ ] Closes #5051
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by max-sixty** [comment]
Hi @thomashirtz ! Thanks for the PR.

The code looks reasonable, though it's generating test failures. To prioritize giving quick feedback over complete feedback — possibly `datasets` is sometimes a generator. We could add `datasets = list(datasets)` above the current code. If that doesn't fix it, feel free to take an error and try debugging what's going on, or someone can help.

We should add a test for this too.

**Comment by thomashirtz** [comment]
Ok! I'll do that in the next few days :)
I'm trying to get more familiar with the whole procedure

**Comment by thomashirtz** [comment]
Will it not cripple performance due to the non-lazy evaluation of the list ?

I also started the test for the concat function, I discovered that if the first element determine between `_dataarray_concat` and `_dataset_concat`. I am not sure if I need to do several commits (type checking dataset, type checking data array) and several test.

Here is the draft for the tests:
```
def test_concat_check_input_type():
    ds = Dataset({"foo": 1}, {"bar": 2})
    da = Dataset({"foo": 3}, {"bar": 4}).to_array(dim='foo')

    # concatenate a list of non-homogeneous types must raise TypeError
    with pytest.raises(TypeError, match="Some elements in the input list datasets are not 'DataSet'"):
        concat([ds, da], dim="foo")

    # concatenate a list of non-homogeneous types must raise TypeError
    with pytest.raises(TypeError, match="Some elements in the input list datasets are not 'DataArray'"):
        concat([da, ds], dim="foo")
```

Code I plan to add also for the typing check in `_dataarray_concat`:
```
    from .dataarray import DataArray
    arrays = list(arrays)
    if not all(isinstance(array, DataArray) for array in list(arrays)):
        raise TypeError("Some elements in the input list datasets are not 'DataArray'")
```
(I need to add `from .dataarray import DataArray` to be able to use the type)

**Comment by max-sixty** [comment]
> Will it not cripple performance due to the non-lazy evaluation of the list ?

I don't think so, but I'm not sure — keeping the full list in memory isn't expensive at all IIUC. And either way, it'll confirm the reason for the test failures for now.


> I also started the test for the concat function, I discovered that if the first element determine between `_dataarray_concat` and `_dataset_concat`. I am not sure if I need to do several commits (type checking dataset, type checking data array) and several test.
> 
> Here is the draft for the tests:
> 

Those look good! Feel free to add them directly and we can discuss them there, and see the test results. Thanks!

**Comment by keewis** [comment]
> keeping the full list in memory isn't expensive at all IIUC

I agree, this should not be an issue at all: we're iterating over `datasets` multiple times so we definitely need it to be a sequence (currently it's some kind of iterator object, e.g. the one returned by `dict.keys`).

**Pull request closed without merging**
