### PR TITLE
Remove reference to tensors in description of N-dimensional arrays

### PR DESCRIPTION
**Pull request by tjcrone**
Don't mean to be pedantic, but although tensors are often represented by N-dimensional arrays, not all N-dimensional arrays are tensors. Tensors conform to a set of tests on coordinate system rotations that, in general, N-dimensional arrays will not pass. I suggest that we remove the reference to tensors in this description. Thank you for Xarray!

### CODE REVIEW

**Comment by max-sixty** [comment]
Yeah, I somewhat agree. But to level up on pedantry: the statement claims that multi-d arrays are sometimes called tensors; not their definition.

@shoyer was the author and certainly knows what tensors are, so I'll close this unless he wants to merge.

Thank you for the PR though @tjcrone , and we'd enjoy a contribution from you in the future!

**Comment by shoyer** [comment]
I think @rabernat may actually be the original author of this language, which I helped edit.

We definitely know what mathematical tensors are, but the term has been (ab)used by popular machine learning frameworks to mean "multi-dimensional array" so I think it's worth keeping around the reference.

**Comment by tjcrone** [comment]
I don't think Xarray is helped much by this fairly cringeworthy misuse of this term. But I'm fine with this close because it's just your documentation. Oh well.

**Comment by tjcrone** [comment]
Also to add, @max-sixty, I agree completely on your level-up, and that was something I considered when I made this almost insignificant change. I am sure that some people call N-dimensional arrays tensors. But I think that the Xarray project would benefit from using terms like this accurately in the documentation. We shouldn't be amplifying this sort of confusion IMO.

**Comment by tjcrone** [comment]
Over the last couple of years I have been an enthusiastic ambassador for open-source projects, arguing at every turn that this model is inclusive, thoughtful, considerate, and that community-driven development leads to better software and better documentation. Lots of burgeoning Earth and ocean scientists who are just learning Python/Numpy/Xarray are also learning about tensors, which are central to much of our science. Xarray should embrace an accurate description of N-dimensional arrays and tensors, in large part to help those who are just learning the science and the software understand these sometimes difficult concepts. But also just to be accurate. Accurate descriptions of these ideas in the Xarray documentation adds to the credibility of the Xarray project, and can help dispel misunderstandings that others may introduce. Tensors are not easy to understand. But they are important and cool. Let's describe them accurately in the Xarray documentation for the sake of all those learning about tensors and N-dimensional arrays.

**Comment by shoyer** [comment]
My intent was to indicate the N-dimensional arrays subsumes the notion of "tensors" from projects like TensorFlow/PyTorch. I agree it doesn't need to be as emphasized as it is, though.

Maybe something like:

> 
Multi-dimensional (a.k.a. N-dimensional, ND) arrays are an essential part of computational science. They are encountered in a wide range of fields, including physics, astronomy, geoscience, bioinformatics, engineering, finance, and deep learning (where they are sometimes called "tensors"). 

I guess we could go further and say "mistakenly called" but in general I don't like to tell people that they're using the wrong word. It feels overly judgmental to me.

**Comment by rabernat** [comment]
Tim, I sincerely appreciate your desire to improve the documentation here. It's a tricky issue. We need to strike a balance between the traditional, mathematically precise definition of tensors and the unfortunate yet now irreversible adoption of this term by a certain [popular machine learning library](https://www.tensorflow.org/guide/tensor). In their words:

> TensorFlow, as the name indicates, is a framework to define and run computations involving tensors. A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes.

If you are really unhappy about how the term tensor is being used in contemporary data science, I sincerely encourage you to open a PR to get tensorflow to change their name and rewrite their documentation. Until that PR is merged, we all have to live with it.

The goal in saying "sometimes called tensors" here is to signal to TensorFlow users that xarray is a tool that is relevant to them. One of our long-term goals is for xarray to achieve wider usage within the machine learning community.

A compromise, rather than simply removing the reference to tensors, would be to add some sort of language to the documentation detailing these subtleties and explaining the contradictions. I would be :+1: on that.

**Comment by max-sixty** [comment]
> A compromise, rather than simply removing the reference to tensors, would be to add some sort of language to the documentation detailing these subtleties and explaining the contradictions. I would be 👍 on that.

👍

**Comment by tjcrone** [comment]
Sorry. I didn't mean to get overly dramatic here on this. @rabernat I appreciate your argument that this language is a signal to TensorFlow users and others in the ML community that Xarray is a tool relevant to them. That's a bit of politics that perhaps I did not fully understand. There is almost certainly a compromise here that acknowledges this use of the term in these fields but also recognizes the correct mathematical use of the term. I really did think this was a minor change but I was wrong. If I come up with the time to find this compromise I will be sure to make another PR. Thank you Xarray.

**Pull request closed without merging**
