### PR TITLE
document update as inplace

### LINKED ISSUE #2951: Document that Dataset.update defaults to being inplace.
It is not documented that the inplace argument to Dataset.update defaults to True, in a departure from every other place where the inplace argument exists (I see this was briefly mentioned in #1756).

Currently the documentation reads:

> Dataset.update(other, inplace=None)
> ...
> inplace:bool, optional
> If True, merge the other dataset into this dataset in-place. Otherwise, return a new dataset object.

I had to dig into the source code to understand why `new_ds = ds.update(changes)` was causing changes to ds. It needs to be documented that update is one of the few mutable functions on a dataset.

### PR DESCRIPTION
**Pull request by keewis**
As pointed out in #2951 I don't think we are able to deprecate the return value. If we are fine with introducing the breaking change in 0.17, I can also remove the return value here.

- [x] closes #2951 (?)
- [ ] Tests added
- [x] Passes `pre-commit run --all-files`
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by dcherian** [comment]
I think we should warn for a while before removing the return value.

**Comment by keewis** [comment]
how would we do that? As far as I can tell the only options are: always warn (but that would also warn if the return value is not used) or wrap in a custom object and warn in `__getattr__` (but that would break `isinstance` checks).

**Comment by dcherian** [comment]
:embarassed: I didn't think of that. Maybe we make the breaking change in v1.0?

**Comment by keewis** [comment]
> could add a "pending deprecation" message in the docstring?

I added the deprecation to both the docstring and `whats-new.rst`. This won't reach as many people as warning would, but I guess this is as much as we are able to do. Should we add a estimated release for the removal (`0.19`)?

**Comment by max-sixty** [comment]
LGTM!

Your call on ETA — `0.19` sounds very reasonable. Also OK to see how we go.

**Comment by max-sixty** [comment]
I was on the fence about doing the release this evening anyway — I may as well wait until we're decided and this is merged — I'll complete in the next couple of days.

**Comment by mathause** [comment]
Could we modify the original `Dataset` class with a special attribute? (Not sure if that'd actually work.)

```python
class Dataset(...)

    _from_update = False

    def update(self, other: "CoercibleMapping") -> "Dataset":

        merge_result = dataset_update_method(self, other)
        out = self._replace(inplace=True, **merge_result._asdict())
        out = out.copy()
        out._from_update = True
        return out

    def __getattr__(self, name: str) -> Any:
        if self._from_update:
            warnings.warn("")
            self._from_update = False
        super().__getattr__(name)

```

**Comment by keewis** [comment]
that could work, but we would need to use `__getattribute__` instead (`__getattr__` is only called if `AttributeError` would be raised otherwise). Not sure if the increased visibility is worth the additional complexity, though.

**Comment by keewis** [comment]
if we decide the overhead introduced by @mathause's suggestion is worth it, I can try adding that. Does not have to be in this PR (or included in the release), though.

**Comment by keewis** [comment]
let's include this in the release, even though we still have to decide whether we should use the `__getattributes__` method

**Pull request merged**
