### PR TITLE
install `numbagg` from `conda-forge`

### PR DESCRIPTION
**Pull request by keewis**
It seems there is a `numbagg` package on `conda-forge` now.

Not sure what to do about the `min-all-deps` CI, but given that the most recent version of `numbagg` happened more than 12 months ago (more than 18 months, even) maybe we can just bump it to the version on `conda-forge`?

### CODE REVIEW

**Comment by keewis** [comment]
that looks like it works, besides the fact that `conda` reports [`numbagg=0.2.1`](https://github.com/pydata/xarray/actions/runs/3838778465/jobs/6535670189#step:7:248) but
```python
print(f"numbagg={numbagg.__version__}")
```
prints [`numbagg=0.2.0`](https://github.com/pydata/xarray/actions/runs/3838778465/jobs/6535670189#step:7:397) (cc @ocefpaf)

**Comment by ocefpaf** [comment]
> that looks like it works, besides the fact that `conda` reports [`numbagg=0.2.1`](https://github.com/pydata/xarray/actions/runs/3838778465/jobs/6535670189#step:7:248) but

It is not a conda problem but a bug upstream. The `v0.2.1` tag has`v0.2.0` hardcoded in it.

See https://github.com/numbagg/numbagg/blob/v0.2.1/setup.py#L24

**Comment by keewis** [comment]
ah, that makes sense, thanks. I must have missed that line when checking the package metadata. This has even been fixed since then, but not released. @max-sixty, would it be possible to issue a new release?

**Comment by max-sixty** [comment]
> This has even been fixed since then, but not released. @max-sixty, would it be possible to issue a new release?

This should now be releasing! https://github.com/numbagg/numbagg/releases/tag/v0.2.2

**Comment by keewis** [comment]
do we need to worry about this:
```pytb
Traceback (most recent call last):
  File "/home/runner/micromamba-root/envs/xarray-tests/lib/python3.10/doctest.py", line 1350, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest xarray.core.rolling_exp.RollingExp.sum[1]>", line 1, in <module>
  File "/home/runner/work/xarray/xarray/xarray/core/rolling_exp.py", line 162, in sum
    return self.obj.reduce(
  File "/home/runner/work/xarray/xarray/xarray/core/dataarray.py", line 3667, in reduce
    var = self.variable.reduce(func, dim, axis, keep_attrs, keepdims, **kwargs)
  File "/home/runner/work/xarray/xarray/xarray/core/variable.py", line 1955, in reduce
    data = func(self.data, axis=axis, **kwargs)
  File "/home/runner/work/xarray/xarray/xarray/core/rolling_exp.py", line 41, in move_exp_nansum
    raise ValueError("`rolling_exp(...).sum() requires numbagg>=0.2.1.")
ValueError: `rolling_exp(...).sum() requires numbagg>=0.2.1.
```
not being caught by CI?

**Pull request merged**
