### PR TITLE
Use pycodestyle for lint checks.

### PR DESCRIPTION
**Pull request by shoyer**
flake8 includes a few more useful checks, but it's annoying to only see it's
output in Travis-CI results.

This keeps Travis-CI and pep8speaks in sync.

### CODE REVIEW

**Comment by dcherian** [comment]
Looks like these need to be fixed:

```
xarray/tests/test_backends.py:2466:38: E741 ambiguous variable name 'l'
xarray/tests/test_backends.py:2466:58: E741 ambiguous variable name 'l'
xarray/tests/test_dataarray.py:445:9: E741 ambiguous variable name 'I'
xarray/tests/test_indexing.py:27:9: E741 ambiguous variable name 'I'
xarray/tests/test_indexing.py:137:9: E741 ambiguous variable name 'I'
xarray/tests/test_indexing.py:157:9: E741 ambiguous variable name 'I'
xarray/tests/test_indexing.py:214:9: E741 ambiguous variable name 'I'
xarray/tests/test_indexing.py:526:5: E741 ambiguous variable name 'I'
xarray/core/common.py:809:80: E501 line too long (80 > 79 characters)
xarray/core/dataset.py:1080:80: E501 line too long (81 > 79 characters)
xarray/core/dataset.py:2174:80: E501 line too long (80 > 79 characters)
xarray/core/dataset.py:2259:80: E501 line too long (80 > 79 characters)
xarray/core/pycompat.py:135:80: E501 line too long (81 > 79 characters)
xarray/core/pycompat.py:146:80: E501 line too long (81 > 79 characters)
```

**Comment by shoyer** [comment]
@pep8speaks fix all

**Comment by shoyer** [comment]
I found a related issue on the pep8speaks tracker, opened by our own @fmaussion: https://github.com/OrkoHunter/pep8speaks/issues/96

**Comment by shoyer** [comment]
Lint is passing on Travis-CI now, so I'm going to merge this.

**Comment by fmaussion** [comment]
@shoyer pep8speaks now support `#noqa` : https://github.com/OrkoHunter/pep8speaks/issues/96#issuecomment-472310933

I wonder if it's still relevant for us since your change though.

**Pull request merged**
