### PR TITLE
adding 'open_groups_as_dict' fucntion to open any zarr file containing nested groups

### LINKED ISSUE #9430: open_groups function to open any zarr file containing nested groups
### What is your issue?

Following #9137 closed by #9243, we suggest a similar approach for Zarr nested groups

### PR DESCRIPTION
**Pull request by aladinor**
- [X] Closes #9430
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Review by aladinor — COMMENTED** [review]
@TomNicholas this is what I was talking about today. Any suggestion about how to handle this?

**Comment by TomNicholas** [comment]
Wait hang on, is this now a duplicate of the PR @eni-awowale just opened in https://github.com/pydata/xarray/pull/9469?

**Comment by eni-awowale** [comment]
Lol @TomNicholas I think everything but the tests I added is the same 💀

**Comment by TomNicholas** [comment]
Agh sorry for the duplicated work here @aladinor - that's my bad!

@eni-awowale has got a lot further with testing in her PR so we'll probably end up merging that and closing this, once any differences have been looked at.

**Comment by aladinor** [comment]
Closing this as is solved by #9469

**Pull request closed without merging**
