### PR TITLE
Docstring and documentation improvement for the Dataset class

### LINKED ISSUE #8970: Example code in the documentation for `Dataset` is not clear
### What is your issue?

The example code in the documentation for the `Dataset` class (e.g., [here](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.html)) is probably clear to those who study Earth and Atmospheric Sciences, but it makes no sense to me. Here is the code:

```python
np.random.seed(0)
temperature = 15 + 8 * np.random.randn(2, 2, 3)
precipitation = 10 * np.random.rand(2, 2, 3)
lon = [[-99.83, -99.32], [-99.79, -99.23]]
lat = [[42.25, 42.21], [42.63, 42.59]]
time = pd.date_range("2014-09-06", periods=3)
reference_time = pd.Timestamp("2014-09-05")

ds = xr.Dataset(
    data_vars=dict(
        temperature=(["x", "y", "time"], temperature),
        precipitation=(["x", "y", "time"], precipitation),
    ),
    coords=dict(
        lon=(["x", "y"], lon),
        lat=(["x", "y"], lat),
        time=time,
        reference_time=reference_time,
    ),
    attrs=dict(description="Weather related data."),
)
```

To be clear, I understand each individual line of code, but I don't understand why there is both a latitude/longitude and an x/y in this example or how they are supposed to be related to each other (and there do not appear to be any additional details about this dataset's intended structure). Probably due to this lack of clarity I'm having a hard time wrapping my head around what the x/y coordinates and the lat/lon coordinates are supposed to demonstrate about xarray here, or how the x/y and lat/lon values are represented in the data structure. Are the x and y coordinates in a map projection of some kind? I have worked successfully with `Dataset`s in the past, but as someone who doesn't work with geospatial data, I find myself more confused about `Dataset`s after reading this example than before.

I suspect that all that is needed is a clear description of what these data are supposed to represent, how they are intended to be used, and how x/y and lat/lon are related. If someone can explain this to me, I'd be happy to submit a PR for the docs.

### PR DESCRIPTION
**Pull request by noahbenson**
The example in the doc-string of the `Dataset` class prior to this commit uses an example array whose size is `2 x 2 x 3` with the first two dimensions labeled `"x"` and `"y"` and the final dimension labeled `"time"`. This was confusing due to the fact that `"x"` and `"y"` are just arbitrary names for these axes and that no reason is given for the data to be organized in a `2x2x3` array instead of a `2x2` matrix. This commit clarifies the example.

Additionally, this PR contains updates to the documentation, specifically the `user-guide/data-structures.rst` file; the updates bring the documentation examples into alignment with the doc-string change. Unfortunately, I wasn't able to build the documentation, so this will need to be checked. (I followed the instructions [here](https://docs.xarray.dev/en/stable/contributing.html#contributing-to-the-documentation), but despite `cfgrib` working fine, I got an error about how it wasn't a valid engine.)

See issue #8970 for more information.

- [X] Closes #8970

### CODE REVIEW

**Comment by max-sixty** [comment]
Thanks!

We do get an error in the doc build — `TypeError: Variable 'temperature': Using a DataArray object to construct a variable is ambiguous, please extract the data using the .data property.`. Check out https://readthedocs.org/projects/xray/builds/24178355/ for more. I also struggle to build the docs...

For the doctests, you may be on a slightly older version of xarray which doesn't print sizes, so worth updating. If you want to update the output automatically I have a project https://github.com/max-sixty/pytest-accept which does this automatically!

**Comment by noahbenson** [comment]
Thanks. That error does not make sense to me—I have not materially changed it from what currently exists in the docs [here](https://docs.xarray.dev/en/stable/user-guide/data-structures.html#dictionary-like-methods) where the line is `ds["temperature"] = (("x", "y", "time"), temp)`. In fact, I think the error should have been that `temp` is not a declared symbol? (I changed the `temp` in the example to `temperature` but did not change it in this line.) That said, I don't use this tool for documentation, so I'm probably missing something.

Anyway, assuming that the `temp` versus `temperature` is fundamentally the problem, my last push should have fixed those issues... 🤞

**Comment by max-sixty** [comment]
Great — if anyone has any thoughts, feel free to comment; otherwise let's merge.

Thanks @noahbenson , nice improvement to a core part of the docs...

**Comment by max-sixty** [comment]
Any other thoughts? There's some discussion in #8970. I think it's reasonable to merge tomorrow without other suggestions.

Give this a 👎 for disagreement (which is welcome ofc)

**Pull request merged**
