### PR TITLE
Fix a typo

### LINKED ISSUE #1363: Typo in reshaping.rst
There are some typos in reshaping.rst, that is newly added in #1347.

### PR DESCRIPTION
**Pull request by fujiisoup**
- [x] closes #1363

Fixes typos in reshaping.rst.
Is there a good way to check docs before merge?

### CODE REVIEW

**Comment by shoyer** [comment]
> Is there a good way to check docs before merge?

Not yet, unfortunately. But they're working on it:
https://github.com/rtfd/readthedocs.org/milestone/18

**Comment by shoyer** [comment]
thanks!

**Comment by fujiisoup** [comment]
> Not yet, unfortunately. But they're working on it:
> https://github.com/rtfd/readthedocs.org/milestone/18

Thanks for the information.
The best solution for me might be to be more careful.

**Comment by shoyer** [comment]
I'll often run a local docs build to make sure (e.g., `make html` after moving to the `docs/` direcotry). But I still make mistakes with RST syntax -- it's not very intuitive. So no big deal on this at all :).

**Pull request merged**
