### PR TITLE
fix miscellaneous `numpy=2.0` errors

### LINKED ISSUE #8133: AttributeError: `np.unicode_` was removed in the NumPy 2.0 release. Use `np.str_` instead
### What happened?

We've been getting this AttributeError on PyGMT's dev CI which tests nightly packages of numpy/xarray/etc. See https://github.com/GenericMappingTools/pygmt/actions/runs/6043991082/job/16401918043#step:16:40

### What did you expect to happen?

Running `import xarray as xr` should work with numpy 2.0.

### Minimal Complete Verifiable Example

```Python
mamba create --name xr_with_np2 python=3.11
mamba activate xr_with_np2
python -m pip install --pre --extra-index https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy pandas xarray

python -c "import xarray as xr"
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/mambaforge/envs/xr_with_np2/lib/python3.11/site-packages/xarray/__init__.py", line 1, in <module>
    from xarray import testing, tutorial
  File "/home/user/mambaforge/envs/xr_with_np2/lib/python3.11/site-packages/xarray/testing.py", line 10, in <module>
    from xarray.core import duck_array_ops, formatting, utils
  File "/home/user/mambaforge/envs/xr_with_np2/lib/python3.11/site-packages/xarray/core/duck_array_ops.py", line 36, in <module>
    from xarray.core import dask_array_ops, dtypes, nputils
  File "/home/user/mambaforge/envs/xr_with_np2/lib/python3.11/site-packages/xarray/core/dask_array_ops.py", line 3, in <module>
    from xarray.core import dtypes, nputils
  File "/home/user/mambaforge/envs/xr_with_np2/lib/python3.11/site-packages/xarray/core/dtypes.py", line 43, in <module>
    (np.bytes_, np.unicode_),  # numpy promotes to unicode
                ^^^^^^^^^^^
  File "/home/user/mambaforge/envs/xr_with_np2/lib/python3.11/site-packages/numpy/__init__.py", line 372, in __getattr__
    raise AttributeError(
AttributeError: `np.unicode_` was removed in the NumPy 2.0 release. Use `np.str_` instead.
```

### Anything else we need to know?

See https://numpy.org/devdocs/release/2.0.0-notes.html#numpy-2-0-python-api-removals. Relevant code at xarray is here https://github.com/pydata/xarray/blob/1043a9e13574e859ec08d19425341b2e359d2802/xarray/core/dtypes.py#L36-L44

### Environment

<details>

```
# packages in environment at /home/weiji/mambaforge/envs/xr_with_np2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.43.0               h2797004_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
numpy                     2.0.0.dev0               pypi_0    pypi
openssl                   3.1.2                hd590300_0    conda-forge
packaging                 23.1                     pypi_0    pypi
pandas                    2.2.0.dev0+141.g413d92d471          pypi_0    pypi
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
python                    3.11.5          hab00c5b_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
setuptools                68.1.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2023.3                   pypi_0    pypi
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xarray                    2023.8.1.dev7+g1043a9e1          pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge
```

</details>

### PR DESCRIPTION
**Pull request by keewis**
- [x] towards #8091
- [x] closes #8133 

Edit: looking at the relevant `numpy` issues, it appears `numpy` will stay a bit unstable for the next few weeks / months. Not sure how quickly we should try to adapt to those changes.

### CODE REVIEW

**Comment by keewis** [comment]
not sure what to do with the `float_` removal, but otherwise this should be ready for merging. That way, at least the `import` check in the upstream-dev CI succeeds.

**Comment by kmuehlbauer** [comment]
> Isn't `np.float_` and `float` equivalent

Not for numpy 2.0, where is has been removed: https://numpy.org/devdocs/release/2.0.0-notes.html#numpy-2-0-python-api-removals.

Maybe just replacing `np.float_` with `np.float64` as suggested in the error message will fix it?

**Comment by mathause** [comment]
Right, thanks. I found no deprecation warning or error in our upstream-dev CI, though. Maybe that's still to come? Anyway, given the description that seems to be the right approach.

**Review by headtr1ck — APPROVED** [review]
Thanks for this PR.
Maybe we should add some type ignores to silence Mypy. Still not sure what the best approach is in such cases.

**Comment by dcherian** [comment]
Yeah we'll need to do something about the. mypy errors:
```
xarray/core/dataset.py:30: error: Cannot find implementation or library stub for module named "numpy.exceptions"  [import]
xarray/core/dataset.py:30: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
xarray/tests/test_dataset.py:20: error: Cannot find implementation or library stub for module named "numpy.exceptions"  [import]
xarray/tests/test_dataarray.py:18: error: Cannot find implementation or library stub for module named "numpy.exceptions"  [import]
```

**Comment by keewis** [comment]
> Maybe just replacing `np.float_` with `np.float64` as suggested in the error message will fix it?

We can't, as we cannot know the default floating-point size in advance: as far as I remember, 32bit OSs (windows in particular) still has `float32` as the default `float`. Instead, just using the python `float` as dtype might work?

> Yeah we'll need to do something about the mypy errors:

I'd be tempted to just add `numpy.exceptions.*` to the list of ignored modules in `pyproject.toml`, but `numpy` does have a `.pyi` file for that, so not sure how to deal with the transition.

**Comment by keewis** [comment]
this should be ready for merging now. Note that there are lots of failing upstream-dev mypy errors and `dask` seems to have some internal inconsistency in its `rolling` implementation, but these can be fixed / discussed in separate issues / PRs.

**Comment by mathause** [comment]
numpy suggests replacing `np.float_` with `np.float64`: https://numpy.org/devdocs/release/2.0.0-notes.html

**Comment by max-sixty** [comment]
FYI looking through the mypy upstream errors, they're almost all matplotlib (with a couple of numpy ones)

**Comment by headtr1ck** [comment]
> FYI looking through the mypy upstream errors, they're almost all matplotlib (with a couple of numpy ones)

See https://github.com/pydata/xarray/pull/8030

**Pull request merged**
