### PR TITLE
Fix tests on big-endian systems

### PR DESCRIPTION
**Pull request by ginggs**
- [ ] Tests added
 - [ ] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

### CODE REVIEW

**Comment by max-sixty** [comment]
Thanks @ginggs 

Is your PR here still relevant? https://github.com/pydata/xarray/pull/2334. I'm sorry no one reviewed that. 
This isn't my area of expertise; @pydata/xarray is there another member of the team who would be able to help?

**Comment by ginggs** [comment]
@max-sixty 

Yes, #2334 is still relevant, I recently rebased and added another XFAIL for a new test.

**Comment by shoyer** [comment]
I don't suppose any of platforms Azure pipelines offers for tests are big-endian? https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#software

I'm guessing not, which is a bit of a shame, but that shouldn't stop us from merging this.

**Comment by shoyer** [comment]
Thanks @ginggs !

**Comment by max-sixty** [comment]
@ginggs if you're up for adding a whatsnew (and give yourself credit), please do!

**Comment by ginggs** [comment]
@max-sixty done in #3135

**Pull request merged**
