### PR TITLE
Switch AppVeyor CI to use conda env / requirements.yml

### LINKED ISSUE #1127: Switch Appveyor CI configuration to use conda env / requirements.yml
This would make it more consistent with our configuration for Travis-CI:
https://github.com/pydata/xarray/tree/master/ci

### PR DESCRIPTION
**Pull request by spencerkclark**
- [x] closes #1127 
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

@shoyer here I'm reusing existing requirements files.  Is this along the lines of what you were looking for in #1127?

I think this should solve the AppVeyor test failures in #1252, as it should install version 1.2.7 of netCDF4, rather than version 1.2.4.

### CODE REVIEW

**Comment by spencerkclark** [comment]
@shoyer it's entirely possible I'm in over my head here, as I'm not a Windows user, so I can't test this setup locally.  It looks as though using the existing requirements files (which install more than what was specified in the original ```appveyor.yml``` configuration file) was probably not a good idea.

If it's a matter of simply creating new requirements files for the Windows environments to mirror what was installed in the original ```appveyor.yml``` file, i.e. pip, pytest, numpy, pandas, scipy, netCDF4, matplotlib, and dask, (this time using the conda-forge channel) then I can probably handle that, but anything more is guesswork on my end, so I'd be fine closing this PR.  I was hoping for a straightforward fix.

**Comment by shoyer** [comment]
> If it's a matter of simply creating new requirements files for the Windows environments to mirror what was installed in the original appveyor.yml file, i.e. pip, pytest, numpy, pandas, scipy, netCDF4, matplotlib, and dask, (this time using the conda-forge channel) then I can probably handle that

Yes, this is what I would recommend. It's just a little easier to maintain if we keep the requirements separate from the install script.

**Comment by spencerkclark** [comment]
Cool, I think I have things working now.  Please let me know if you'd like me to make any changes.

**Comment by shoyer** [comment]
Looks great, thanks!

**Pull request merged**
