### PR TITLE
Add some more mypy checks

### PR DESCRIPTION
**Pull request by max-sixty**
This disallows redundant casts

FWIW I thought we had gone through many of the tests and forced them to have typed defs, maybe with the intention of turning on some elements of strict mode. But then I don't think we have any strictness checks at the moment, and I see many functions in the tests which don't have typing. Am I mis-rembering?? Or maybe we started but didn't get far enough (it is a big project...)

### CODE REVIEW

**Comment by max-sixty** [comment]
This fails on numpy 1.24.1, because the ignore isn't needed.

Is it viable to merge this once CI upgrades to 1.25? Or is this approach going to mean we're quite dependent on the exact version of dependencies, which is difficult to rely on in python / conda?

**Comment by headtr1ck** [comment]
We had this problem several times already in the past weeks.
For now we have simply added `type: ignore[xxx,unused-ignore]` which feels a bit like cheating but no idea on how to solve this while supporting different dependency versions.

**Comment by max-sixty** [comment]
> For now we have simply added `type: ignore[xxx,unused-ignore]` which feels a bit like cheating but no idea on how to solve this while supporting different dependency versions.

Super! Done

---

BTW @headtr1ck any recollection re my comment above? Is it possible I remember that you might have done a lot of the work to move tests to use typing, possible with the intention of turning on some checks so we forced typing in tests? Or is my memory making things up?

**Comment by headtr1ck** [comment]
> BTW @headtr1ck any recollection re my comment above? Is it possible I remember that you might have done a lot of the work to move tests to use typing, possible with the intention of turning on some checks so we forced typing in tests? Or is my memory making things up?

You are not making this up I remember it as well, but after searching for 20 min I give up...

I vaguely remember that turning on strict mode was raising so many errors that it was impossible to solve the issues in a single PR. And enforcing `def test_xxx(...) -> None:` in all new tests was also turning out to be difficult, so we stick with enforcing this via reviews.

I guess we could try again with strict mode?
> Found 12211 errors in 130 files (checked 142 source files)

Maybe I'm motivated enough in the next days to start a few PRs that enable type checking manually in the tests.

**Comment by max-sixty** [comment]
> You are not making this up I remember it as well, but after searching for 20 min I give up...

Unless we're both misremembering?? :)

---

Something we can do is turn parts of strict mode on incrementally with the config file. While I think `--strict` is on-or-off (or at least used to be), its various components can be turned on by module — https://justincaustin.com/blog/mypy-tips-and-tricks/.

So we could ratchet up the coverage by starting with files which already have it, and expanding from there. And then if we pause we don't lose the progress.

I do think this would be quite valuable — I remember realizing that some of our type defn were incorrect and our tests weren't testing them! So mandating `-> None` would fix that...

**Comment by headtr1ck** [comment]
> Something we can do is turn parts of strict mode on incrementally with the config file. While I think `--strict` is on-or-off (or at least used to be), its various components can be turned on by module — https://justincaustin.com/blog/mypy-tips-and-tricks/.

The main problem with this is that large parts of the really low level functions are still untyped, so strict mode will complain a lot about calling untyped methods.

**Review by headtr1ck — APPROVED** [review]

**Comment by max-sixty** [comment]
Yes, I looked at a couple of modules and you're right...

I create #8198 with a single module to start...

**Pull request merged**
