### PR TITLE
[skip-ci] Fix groupby binary ops benchmarks

### PR DESCRIPTION
**Pull request by dcherian**

### CODE REVIEW

**Review by Illviljan — APPROVED** [review]

**Comment by Illviljan** [comment]
Ahh, there are a few errors in the benchmarks. Are those fixed with your other PRs?
```
Error: [ 88.75%] ··· ...by.ResampleDask.peakmem_groupby_binary_op_2d             failed
Error: [ 88.75%] ···· Traceback (most recent call last):
                 File "/home/runner/micromamba-root/envs/xarray-tests/lib/python3.10/site-packages/asv/benchmark.py", line 1293, in main_run_server
                   main_run(run_args)
                 File "/home/runner/micromamba-root/envs/xarray-tests/lib/python3.10/site-packages/asv/benchmark.py", line 1167, in main_run
                   result = benchmark.do_run()
                 File "/home/runner/micromamba-root/envs/xarray-tests/lib/python3.10/site-packages/asv/benchmark.py", line 573, in do_run
                   return self.run(*self._current_params)
                 File "/home/runner/micromamba-root/envs/xarray-tests/lib/python3.10/site-packages/asv/benchmark.py", line 842, in run
                   self.func(*param)
                 File "/home/runner/work/xarray/xarray/asv_bench/benchmarks/groupby.py", line 136, in peakmem_groupby_binary_op_2d
                   self.ds2d.resample(time="48H") - self.ds2d_mean
                 File "/home/runner/work/xarray/xarray/asv_bench/.asv/env/e3a5540da3d30da735a9fb168f264be6/lib/python3.10/site-packages/xarray/core/_typed_ops.py", line 589, in __sub__
                   return self._binary_op(other, operator.sub)
                 File "/home/runner/work/xarray/xarray/asv_bench/.asv/env/e3a5540da3d30da735a9fb168f264be6/lib/python3.10/site-packages/xarray/core/groupby.py", line 601, in _binary_op
                   raise ValueError(
               ValueError: incompatible dimensions for a grouped binary operation: the group variable '__resample_dim__' is not a dimension on the other argument
               asv: benchmark failed (exit status 1)
```

**Comment by dcherian** [comment]
No this is a real failure with no test coverage :(. I guess not many people do resampling binary ops?

**Comment by dcherian** [comment]
Hmmm not sure why the resample binary ops benchmarks still fail.

**Comment by Illviljan** [comment]
```
 Error: [ 89.17%] ··· groupby.ResampleDask.time_binary_op_1d                      failed
Error: [ 89.17%] ···· Traceback (most recent call last):
                 File "/home/runner/micromamba-root/envs/xarray-tests/lib/python3.10/site-packages/asv/benchmark.py", line 1293, in main_run_server
                   main_run(run_args)
                 File "/home/runner/micromamba-root/envs/xarray-tests/lib/python3.10/site-packages/asv/benchmark.py", line 1167, in main_run
                   result = benchmark.do_run()
                 File "/home/runner/micromamba-root/envs/xarray-tests/lib/python3.10/site-packages/asv/benchmark.py", line 573, in do_run
                   return self.run(*self._current_params)
                 File "/home/runner/micromamba-root/envs/xarray-tests/lib/python3.10/site-packages/asv/benchmark.py", line 669, in run
                   samples, number = self.benchmark_timing(timer, min_repeat, max_repeat,
                 File "/home/runner/micromamba-root/envs/xarray-tests/lib/python3.10/site-packages/asv/benchmark.py", line 705, in benchmark_timing
                   timing = timer.timeit(number)
                 File "/home/runner/work/xarray/xarray/asv_bench/.asv/env/e3a5540da3d30da735a9fb168f264be6/lib/python3.10/timeit.py", line 178, in timeit
                   timing = self.inner(it, self.timer)
                 File "<timeit-src>", line 6, in inner
                 File "/home/runner/work/xarray/xarray/asv_bench/benchmarks/groupby.py", line 127, in time_binary_op_1d
                   raise NotImplementedError
               NotImplementedError
               asv: benchmark failed (exit status 1)
```

Comparing to 
https://github.com/pydata/xarray/blob/5043223ca7942c6eb582798aafa843d2efc0895b/asv_bench/benchmarks/__init__.py#L72-L74

It has to be initialized? Try adding a short description with why it's not implemented/link to issue.

**Pull request merged**
