### PR TITLE
vélin

### PR DESCRIPTION
**Pull request by keewis**
as suggested by @dcherian in https://github.com/pydata/xarray/pull/4867#issuecomment-774489458, ~this adds [`velin`](https://github.com/Carreau/velin) to the `pre-commit` hooks~ as suggested below, we'll leave that hook deactivated for now.

I think this would help enforcing the style of the docstrings a bit more. However, while most of the changes it proposes are great, the tool itself does not seem to be mature, so I'll mark this PR as a draft.

- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by max-sixty** [comment]
I think the changes look great! Thanks for finding it!

I would probably start by applying it first and then as we gain more experience, later add it to pre-commit hooks; so we can learn whether it has any sharp edges. Because this affects all contributors — even those making a small docs PR for the first time — if it has any confusing behavior, it could be fairly frustrating for them. 

We did this for `isort` IIRC and then later added it to pre-commit (though given its success, I wonder if that experience updates us to add tools slower or faster...)

**Comment by keewis** [comment]
I found a way to remove the extra newlines, so the missing `,` aside this actually does look really good.

**Comment by dcherian** [comment]
Looks great! should we merge just before the next release to avoid conflicts with open PRs?

**Comment by keewis** [comment]
I don't think we have to worry about that: the number of lines this PR changes is pretty small, only touches the documentation and even if someone gets a merge conflict that would be a few lines at most.

**Comment by dcherian** [comment]
Great. merging!

**Comment by max-sixty** [comment]
Nice! Thanks!

**Pull request merged**
