### PR TITLE
chore: Remove unnecessary comprehension

### PR DESCRIPTION
**Pull request by pnijhara**
- [x] Passes `isort -rc . && black . && mypy . && flake8`
 - [x] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

### CODE REVIEW

**Comment by max-sixty** [comment]
Thanks @pnijhara — want to add to whatsnew + give yourself credit? No problem if not given the breadth of the change.

**Comment by pnijhara** [comment]
@max-sixty, sorry! I am not getting you.

**Comment by max-sixty** [comment]
If you like, you can add a line here: https://github.com/pydata/xarray/blob/master/doc/whats-new.rst, under "Internal Changes" to say you made a change. You don't have to, though.

**Comment by pnijhara** [comment]
Will surely write.

**Comment by max-sixty** [comment]
Thanks. Merging as the test failure is unrelated.

**Pull request merged**
