### PR TITLE
Add yet an other CI for numpy 2.1

### PR DESCRIPTION
**Pull request by hmaarrfk**
In response to help with: https://github.com/pydata/xarray/pull/9403#issuecomment-2368005828

- [ ] Closes #xxxx
- [ ] Tests added
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [ ] New functions/methods are listed in `api.rst`

### CODE REVIEW

**Comment by dcherian** [comment]
Thanks! 

Perhaps we should go the other way and have numba, sparse, numbagg only in one env?

**Comment by hmaarrfk** [comment]
hmmm as you wish, but my attempt got sparse 0.3.1.

So i guess i should remove sparse from my test environement too.

**Comment by hmaarrfk** [comment]
PS. i also opened: https://github.com/conda-forge/sparse-feedstock/issues/25

**Comment by max-sixty** [comment]
I'll merge so we can have this running.

But should we adjust this to always have the latest numpy? The policy would be to eschew any package (like numba) which is incompatible with the latest numpy.

**Comment by hmaarrfk** [comment]
> But should we adjust this to always have the latest numpy?

this seems complicated to me. you can try, but it isn't too much churn to check this from time to time.

I think we are just going through some long needed cleanup pains of numpy. happy that this is happening!

**Comment by max-sixty** [comment]
> this seems complicated to me. you can try, but it isn't too much churn to check this from time to time.

I don't know conda well at all, but if we just exclude a list of packages which pin numpy, won't that suffice? It's conditional on a package not newly pinning numpy but should otherwise work?

**Comment by hmaarrfk** [comment]
>  but if we just exclude a list of packages which pin numpy,

Many bugs seem to come from various interactions. So the more you exclude, the less you test....

xarray builds on alot of the scientfici stack, so you can't be too "modern". 

I think if you just remember to set the lower bound of numpy every one in a while, you'll get a semi-modern environment.

**Comment by hmaarrfk** [comment]
Selfishly, i would just recommend setting your lower bound to whatever the output of 


```
nep29 PACKAGE_NAME
```
gives you.

https://pypi.org/project/nep29/

**Comment by max-sixty** [comment]
> Many bugs seem to come from various interactions. So the more you exclude, the less you test....

Sure sure, but IIUC there are a few specific packages which pin numpy (e.g. `numba`) — so if we exclude those then we will get latest numpy. No?

That was my understanding of the gap here — in our existing CI we basically either have a) minimum deps or b) everything, but we were lacking a "latest numpy" because of that pinning; outside of `upstream-dev`.

(Ofc _possible_ for a package to suddenly start pinning numpy — but seems less maintenance than manually upgrading numpy, which the currently merged code requires...)

**Pull request merged**
