### PR TITLE
Clearer terminology for coordinate variables

### PR DESCRIPTION
**Pull request by fmaussion**
- [x] closes https://github.com/pydata/xarray/issues/1295

### CODE REVIEW

**Comment by fmaussion** [comment]
cc @rabernat @shoyer

**Comment by rabernat** [comment]
After additional discussion in #1295, I guess this should be revised.

**Comment by fmaussion** [comment]
Yes. Let me know if you have a preference for the second coordinate type in https://github.com/pydata/xarray/issues/1295

**Comment by fmaussion** [comment]
OK, this is ready for review.

**Pull request merged**
