### PR TITLE
unpin pip 20.2 again

### PR DESCRIPTION
**Pull request by mathause**
Another enormous PR from my side ;) unpin pip again. numpy probably fixed the issue re the name of the nightly build. But I also need to doublecheck if scipy is ok.

### CODE REVIEW

**Comment by keewis** [comment]
thanks for keeping an eye on this, @mathause. Unfortunately, `scipy` didn't fix their package, yet, which means that we have to wait with the merge until they do.

**Comment by max-sixty** [comment]
> Another enormous PR from my side ;)

Highest value per line changed! 😀

**Comment by keewis** [comment]
it seems `scipy` fixed this, but their wheel building repository fails the py38 build jobs so there's no py38 manylinux wheels. We could upgrade the upstream-dev CI to py39, but unfortunately there's no stable release of `numba` with py39 support.

**Comment by keewis** [comment]
we upgraded upstream-dev to py39 so we should be able install scipy with the new dependency resolver again, but they currently have trouble with their wheel building repository so the wheels we install are from early March. No reason not to merge this PR, though.

**Comment by keewis** [comment]
it seems `scipy` has fixed their packages. If CI passes we should be able to finally merge this.

**Comment by keewis** [comment]
the upstream-dev failures are the ones reported by #5077, so this is ready.

**Comment by max-sixty** [comment]
Nice! Thanks @keewis !

**Pull request merged**
