### PR TITLE
Fix doctest warnings, enable errors in CI

### PR DESCRIPTION
**Pull request by max-sixty**
- [x] From https://github.com/pydata/xarray/issues/7164
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

I'm not confident about the CI change; either we can merge with the "this is a trial message" and see how it goes, or split that into a separate PR and discuss.

### CODE REVIEW

**Comment by max-sixty** [comment]
Currently this raises a deprecation warning: https://github.com/pydata/xarray/blob/50301acd266cbfeb5a59c31f3ddabf2673e127cf/xarray/backends/rasterio_.py#L193

Possibly we add something to the doctest to ignore warnings? It'll be out of place in the docs though...

**Comment by Illviljan** [comment]
`open_rasterio` has been deprecated for like a year, #5808. Is it time to remove it?

**Comment by max-sixty** [comment]
> `open_rasterio` has been deprecated for like a year, #5808. Is it time to remove it?
> 
> You can also just remove the example from the docstring, this is on minimal support anyway.

Done

**Review by headtr1ck — APPROVED** [review]
Nice

**Comment by max-sixty** [comment]
OK, let's give this a whirl!

**Pull request merged**
