### PR TITLE
Partial fix for #2841 to improve formatting.

### PR DESCRIPTION
**Pull request by dnowacki-usgs**
Updates formatting to use .format() instead of % operator. Changed all instances of % to .format() and added test for using tuple as key, which errored using % operator.

### CODE REVIEW

**Comment by shoyer** [comment]
Thanks @dnowacki-usgs !

One minor note -- it's valid (since Python 2.7) to write string formatting with explicit positional indexes, e.g., you could just write `'{} {}'.format('one', 'two')` rather than `'{0} {1}'.format('one', 'two')`.

I think it's usually a little cleaner to omit the numeric indices, unless you're reusing arguments multiple times or printing the names out of order. (But even in these cases it's usually nicer to use keyword names.)

**Comment by max-sixty** [comment]
Also come Py3.6, f strings 🙏

**Comment by dnowacki-usgs** [comment]
Thanks @shoyer. I think numeric indexes are clearer, though maybe not cleaner. Removed them and fixed the dask CI test I didn't catch the first time through. Hopefully everything passes now. 🤞

**Comment by shoyer** [comment]
Looks great! You can ignore the failing doc build in the tests, that is unrelated.

If you like, feel free to give yourself a credit in `whats-new.rst` for fixing this. Otherwise I'll merge this in a day or two.

**Comment by dnowacki-usgs** [comment]
Good to go as far as I'm concerned. I'm not even sure how I'd phrase these changes in whats-new, so let's go with it as-is.

**Comment by max-sixty** [comment]
OK, thanks @dnowacki-usgs !

**Pull request merged**
