### PR TITLE
DOC: remove example using Dataset.T

### PR DESCRIPTION
**Pull request by shoyer**
as reported on the mailing list

### CODE REVIEW

**Comment by dcherian** [comment]
Oops, missed that. Thanks.

**Comment by dcherian** [comment]
do we need a `ds.transpose()` example to show that args are unnecessary?

**Comment by shoyer** [comment]
We documented `ds.transpose()` on the computation page, too, so I don't think it's really necessary here.

**Comment by shoyer** [comment]
actually -- maybe that's a good idea after all.

**Pull request merged**
