### PR TITLE
adapt to NEP 51

### PR DESCRIPTION
**Pull request by keewis**
With NEP 51 (and the changes to `numpy` `main`), scalar types no longer pretend to be standard python types in their string representation. This fixes most of the errors in the tests but there are still a few remaining in the doctests (in particular, doctests for private plotting utils).

- [x] towards #8091

### CODE REVIEW

**Comment by dcherian** [comment]
Should we keep the numpy representation since that's more accurate?

We could use `pytest-accept` to update the tests

**Comment by keewis** [comment]
> Should we keep the numpy representation since that's more accurate?

I wouldn't think so, but I might be wrong: we already have the dtype information right beside it so it wouldn't add much, and they are usually taken out of arrays and are only formatted that way because we iterate over the array's values.

That said, there are definitely a few instances where we actually do return `numpy` scalars in the doctests that should be updated (although that means we'd have to wait until we adopt `numpy>1.25` (`numpy=2.0`?), and accept that you *have* to use at least that version to run the doctests until we can discontinue support for `numpy<2.0`)

**Comment by headtr1ck** [comment]
> That said, there are definitely a few instances where we actually do return `numpy` scalars in the doctests that should be updated (although that means we'd have to wait until we adopt `numpy>1.25` (`numpy=2.0`?), and accept that you *have* to use at least that version to run the doctests until we can discontinue support for `numpy<2.0`)

You could also parse them to python floats/ints before displaying them. This would work with all numpy versions.

**Comment by keewis** [comment]
> You could also parse them to python floats/ints before displaying them.

Cast, you mean?

**Comment by headtr1ck** [comment]
Simply `value = float(da.item())`. This will display the same for all np versions.

**Comment by keewis** [comment]
> Simply `value = float(da.item())`

The `float` wouldn't even be necessary, `arr.item()` (and `arr.tolist()`) always return python types.

However, for some we're not the ones who issue those (an example: `fg.axs[0, 0].get_xlim()` in `xarray.plot.facetgrid.FacetGrid._set_lims` returns a tuple of two `numpy.float`s, but `get_xlim` is from `matplotlib`).

According to numpy/numpy#24470, the recommendation is to test a single `numpy` version, so I'd vote to worry about those once `numpy=2.0` has been released.

**Pull request merged**
