### PR TITLE
PKG: Explicitly add setuptools dependency

### PR DESCRIPTION
**Pull request by hoechenberger**
Compare https://github.com/conda-forge/xarray-feedstock/pull/53

Not sure whether this should be mentioned in `whats-new.rst`?

 - [ ] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

### CODE REVIEW

**Comment by dcherian** [comment]
gentle ping @crusaderky

**Comment by crusaderky** [comment]
setuptools is not a runtime dependency since https://github.com/pydata/xarray/pull/3720
Also, I'm confused - both conda and cpython always come with setuptools preinstalled. How did you manage to get an environment without it?

**Comment by hoechenberger** [comment]
> Also, I'm confused - both conda and cpython always come with setuptools preinstalled. How did you manage to get an environment without it?

It won't get installed on the `conda-forge` CI, see https://github.com/conda-forge/xarray-feedstock/pull/53#issuecomment-580174543

**Comment by crusaderky** [comment]
@dcherian I've heavily changed this, please give it a second read and merge if you're happy with it

**Pull request merged**
