### PR TITLE
Check types in travis

### PR DESCRIPTION
**Pull request by max-sixty**
As part of https://github.com/pydata/xarray/pull/2929#issuecomment-502302695, I looked at enabling travis to check types. 

What do people think? As a more cautious option I could add to `allowed_failures` for the moment

### CODE REVIEW

**Comment by shoyer** [comment]
My original reason for not enabling this was to impose the burden of hunting down type errors on Travis-CI. But maybe we can figure out how to run `mypy` with pep8speaks?

**Comment by max-sixty** [comment]
pep8speaks doesn't run mypy yet, unfortunately.

Shall I add to `allow_failures` and we can see whether it's failing too often for normal PRs?

**Comment by shoyer** [comment]
Sure, sounds great to add this as an allowed failure for now

**Comment by max-sixty** [comment]
Great, moved to `allow_failures` - could someone give this a final check (or feel free to merge directly)

**Comment by shoyer** [comment]
thanks!

**Pull request merged**
