### PR TITLE
release notes for 2024.06.0

### PR DESCRIPTION
**Pull request by keewis**
PRs to wait on:
- [x] #9101
- [x] #9085?

I'll remove the empty sections before just before merging, so any PRs that are merged before that can still be included without merge conflicts.

### CODE REVIEW

**Comment by keewis** [comment]
I'll cut the release tomorrow morning (and merge this just before that). If there's anything to merge before that, feel free to do so, and I'll do a final pass over the release notes just before that.

**Comment by max-sixty** [comment]
Nice, thanks!

**Comment by keewis** [comment]
the upstream-dev CI currently fails for similar reasons as the tests fixed in #9081. Since this is caused by changes in the (unreleased) `pandas=3.0`, I think we can just go ahead with the merge.

**Comment by keewis** [comment]
@dcherian, it looks like the hypothesis CI triggers on `[skip-ci]` (i.e. the inverse of what we usually do). Is that intentional?

**Comment by dcherian** [comment]
No!

**Comment by keewis** [comment]
I'm going to wait a bit more to give time to resolve #9085 (otherwise we might just add the names for the remaining ones?), and will release tomorrow. Any opinions, @dcherian?

**Comment by dcherian** [comment]
+1 to just adding names and closing it out.

Somehow I seem to have messed up the hypothesis action again. but that's not a blocker!
#9107 would be good to get in. RTD is slow today.

**Comment by keewis** [comment]
I'll go ahead and do that, then

**Pull request merged**
