### PR TITLE
Explicitly keep track of indexes with merging

### PR DESCRIPTION
**Pull request by shoyer**
Part of the explicit indexes refactor (https://github.com/pydata/xarray/issues/1603)

No user facing changes.

 - [x] Passes `black . && mypy . && flake8`

### CODE REVIEW

**Comment by shoyer** [comment]
Test failure should be fixed by https://github.com/pydata/xarray/pull/3235

**Comment by shoyer** [comment]
@pydata/xarray if anyone has time, it would be great to get a review here.

(I think this is pretty low risk, so I will probably self merge this in a week or so if there aren't any reviews)

**Comment by max-sixty** [comment]
I had a read through—looks good, better design (and lots of nice idioms!). 
But I confess that I don't know the code well enough to make a more helpful judgement, and while I'd normally approach from the tests, no changes to those.

**Comment by shoyer** [comment]
@max-sixty thanks for taking a look!

I agree, this was hard to review without test changes.

**Pull request merged**
