### PR TITLE
Restore crashing CI tests on pseudonetcdf-3.1

### PR DESCRIPTION
**Pull request by crusaderky**
Related to #3409 

The crashes caused by pseudonetcdf-3.1 are blocking all PRs.
Sorry I don't know anything about pseudonetcdf. This PR takes the issue out of the critical path so that whoever knows about the library can deal with it in due time.

### CODE REVIEW

**Comment by jhamman** [comment]
@barronh - can you take a look at the failing pseudonetcdf tests?

**Comment by barronh** [comment]
As a temporary fix, you can change xarray to require 3.0.2, which did not have this issue. I'll look into it.

**Comment by barronh** [comment]
I see you already did move back to 3.0.2. Can you point me to a log where the problem exists to get me started?

**Comment by crusaderky** [comment]
@barronh  https://dev.azure.com/xarray/xarray/_build/results?buildId=1128&view=logs&jobId=f2e88b57-11cf-55c8-cc48-7751ab3d0d0f

**Comment by barronh** [comment]
Thank you. I need to update the xarray tests.

**Pull request merged**
