### PR TITLE
Alternate method using inline css to hide regular html output in an untrusted notebook

### PR DESCRIPTION
**Pull request by mlhenderson**
When using xarray in a jupyterlab notebook environment with lab extensions loading external css libraries (e.g., bootstrap), the hidden html5 attribute applied to the 'xr-wrap' div element is actually respected and cannot be escaped using a display change in the xarray included css.

The html hidden attribute was weakly enforced in some browsers, but bootstrap added this rule to ensure it took effect as early as v4.0:
https://github.com/twbs/bootstrap/blob/v4.0.0/scss/_reboot.scss#L480-L482

This means that not only does the normal html content inside the xr-wrap div not display in a trusted notebook environment that has this type of css rule applied from an external library, the fallback text display mechanism in the pre element does not kick in because the css block is present and sets that content to 'display: none' and so then you just get blank output in the cell when trying to display a Dataset, which is not ideal.

This PR addresses the above problem and maintains a fallback display mechanism when in an untrusted notebook.  In a trusted environment, the css will be loaded and the inline css for 'xr-wrap' of 'display:none' will be overridden by the embedded css style block of 'display: block !important', displaying the expected html.  In an untrusted environment, the css block will be removed (not hiding the pre element) but the inline style will remain (hiding the 'xr-wrap' div element), leaving the pre text to load instead.

- [x] Passes `pre-commit run --all-files`
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by mlhenderson** [comment]
I looked at the other issues, and this should resolve the sphinx-book issue in https://github.com/executablebooks/sphinx-book-theme/issues/238#issuecomment-714784321 without needing a special exception for that codebase.

For https://github.com/pydata/xarray/pull/4053:
Github rendered notebooks will still not look great because it will strip the inline css of the xr-wrap div (and all css).  All of the actual styling (placement, color, etc) for that html block is in the css style block that gets stripped.  Fixing that is a different problem from the untrusted notebook case, which is less aggressive, although that may not be the case in the future.  You would need to render the content in a different format (maybe an image) for the saved notebook to get around losing css entirely.

**Comment by max-sixty** [comment]
Hi @mlhenderson — I don't know this well — if you are confident that @benbovy 's concern is not pressing, then we could merge? (unless @benbovy you are confident that it is a concern!)

**Comment by mlhenderson** [comment]
Unfortunately, I can't predict what the Jupyter project could do in the
future in terms of stripping inline CSS or the html hidden attribute.  I
don't get the sense that this would be happening anytime soon, but I can't
promise it would never happen.

I sent in the PR because I am an author of a JupyterLab extension that we
plan to use at NERSC, which includes Bootstrap, and we ran into the problem
of the xarray repr() returning a hidden div (blank output) in a regular
notebook (trusted).  Any JupyterLab extension that includes Bootstrap or
has a css rule that affects how the browser treats the html hidden
attribute will have similar problems with xarray in notebooks.  It seemed
appropriate to flag it and send in a fix before it becomes a bigger problem.

There is an existing test in xarray (which passes) that checks for the css
content.  If you wanted to add another test that actually spins up a
Jupyter instance to test it further, that is possible but definitely more
involved and may not be a fast test to run.

I think this could be merged as-is, but feedback is always welcome.  If
there are any suggestions for improving this PR further to resolve
the existing issue please let me know.

Longer-term, embedding html/css may not be the way to go, but I think that
falls outside the scope of this PR.  We can arrange to chat with some
Jupyter devs if there is interest in a discussion about longer-term
solutions for the rendering in notebooks and/or JupyterLab, just let me
know if you want to do that. @benbovy

**Comment by max-sixty** [comment]
Many thanks for your thoughtful reply @mlhenderson . It seems like the proposed code is better than the current code, so I would suggest we merge, and we can iterate further if others have thoughts.

And thanks for your first contribution !

**Comment by benbovy** [comment]
Thanks @mlhenderson!

> Longer-term, embedding html/css may not be the way to go, but I think that
falls outside the scope of this PR.  We can arrange to chat with some
Jupyter devs if there is interest in a discussion about longer-term
solutions for the rendering in notebooks and/or JupyterLab, just let me
know if you want to do that. @benbovy

Yeah, now that (since v3) Jupyterlab extensions can simply be installed using conda or pip, we may consider eventually porting this rich-repr feature into a lightweight extension instead. That would be a more robust and extensible solution. The main problem, however, is how to support the variety of notebook front-ends. There seems to be a recent agreement on refactoring Jupyter "official" front-ends (e.g., "classic" notebook) so that they all use Jupyterlab's current machinery, which will certainly help here. Not sure for the other front-ends (e.g., VSCode, GitHub, GitLab, Sphinx themes, etc.), though. Maybe we could have three repr alternatives:

- The full-featured, interactive version: compatible with all official Jupyter front-ends, maintained in a 3rd-party Jupyter extension
- A basic, html-based version (as fallback): less interactive but should work (and be nicely integrated) with all notebook front-ends without relying on ugly hacks (no css, just basic html tags)
- The plain text version 

I agree that it would be worth discussing this general issue with Jupyter devs. There's more and more projects in the Python/PyData ecosystem that provide advanced, html-based reprs.

**Pull request merged**
