### PR TITLE
Fix warning on chunks compatibility

### PR DESCRIPTION
**Pull request by aurghs**
This PR fixes https://github.com/pydata/xarray/issues/4708. It's a very small change.
Changes:
- In `dataset._check_chunks_compatibility` now it doesn't raise a warning if the last chunk % preferred_chunk != 0.
- Update tests
- Style: rename a variable inside `dataset._check_chunks_compatibility` 

 - [x] Closes https://github.com/pydata/xarray/issues/4708
 - [x] Tests added
 - [x] Passes `isort . && black . && mypy . && flake8`

### CODE REVIEW

**Review by alexamici — APPROVED** [review]

**Comment by mathause** [comment]
This leads to [warnings in out test suite](https://dev.azure.com/xarray/xarray/_build/results?buildId=4596&view=logs&j=acc1347f-8235-55b0-95c7-0e2189e61659&t=7284452c-b1fa-561e-b473-09e477cf0d79&l=268
). Could you please suppress them?

Btw & not for here. There are other warnings from the backends refactor. Would be nice if you could hunt them down and either fix or suppress them.

**Comment by mathause** [comment]
I assume you know this, but in case not. I find it's easiest to suppress the message using:

```python
@pytest.mark.filterwarnings("ignore:Specified Dask chunks")
def test_xy():
    ...
```

If you want to test for the warning you can use:

```python
def test_xy():
    with pytest.warns(UserWarning, match="Specified Dask chunks"):
        func(...)
```
note that this also suppresses the warning - i.e. you don't need both.

**Comment by aurghs** [comment]
> Btw & not for here. There are other warnings from the backends refactor. Would be nice if you could hunt them down and either fix or suppress them.

I was just doing that now.

**Comment by dcherian** [comment]
Thanks @aurghs !

**Pull request merged**
